// Resilient coverage-comment posting (issue #4231).
//
// The `coverage` job's "Post coverage comment on PR" step calls three GitHub
// REST APIs (listComments, deleteComment, createComment). With no retry and no
// tolerance, a transient GitHub 5xx failed the whole REQUIRED `coverage` check
// and blocked otherwise-green PRs (observed as coverage:FAILURE on #4230).
//
// This module extracts that logic so `coverage.yml` can load it and so it can be
// unit-tested. It adds:
//   * `retry` — retries ONLY transient failures (>=500, 429, or a network error)
//     with exponential backoff, never retries deterministic 4xx.
//   * `postCoverageComment` — upserts the comment and, on a PERSISTENT API
//     failure, WARNS and returns `{ posted: false, reason: 'api-error' }` WITHOUT
//     throwing, so the comment side effect can never fail the required coverage
//     gate. The coverage threshold gate itself is unaffected (it runs earlier in
//     the job); only this comment-posting step tolerates transient outages.

const MARKER = '## 📊 Coverage Summary';

/**
 * True iff `err` is a transient failure worth retrying: an HTTP 5xx, an HTTP 429
 * (rate limit), or a network-level error (no HTTP status but a `code` such as
 * ECONNRESET / ETIMEDOUT). Deterministic 4xx (403/404/…) are NOT transient.
 */
export function isTransient(err) {
  if (!err) return false;
  const status = err.status;
  if (typeof status === 'number') {
    return status >= 500 || status === 429;
  }
  return typeof err.code === 'string' && err.code.length > 0;
}

/**
 * Await `fn(attempt)` (1-based), returning its value on success. Retries only
 * transient failures (see `isTransient`), up to `retries` total attempts, with
 * exponential backoff. Rethrows the last error on a deterministic failure or
 * once attempts are exhausted. `sleep(ms)` is injectable so tests incur no delay.
 */
export async function retry(fn, opts = {}) {
  const retries = opts.retries ?? 4;
  const baseDelayMs = opts.baseDelayMs ?? 500;
  const sleep = opts.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));

  let lastErr;
  for (let attempt = 1; attempt <= retries; attempt += 1) {
    try {
      return await fn(attempt);
    } catch (err) {
      lastErr = err;
      if (!isTransient(err) || attempt === retries) {
        throw err;
      }
      await sleep(baseDelayMs * 2 ** (attempt - 1));
    }
  }
  throw lastErr;
}

/**
 * Build the coverage-summary markdown body from a parsed
 * `cargo llvm-cov --json --summary-only` payload. Aggregates per top-level
 * `src/<module>` directory and appends an overall total row.
 */
export function buildCommentBody(data) {
  const totals = data.data[0].totals;
  const files = data.data[0].files || [];

  const modules = {};
  for (const f of files) {
    const match = f.filename.match(/^src\/([^/]+)/);
    if (!match) continue;
    const mod = match[1];
    if (!modules[mod]) {
      modules[mod] = { lines: 0, covered: 0 };
    }
    const s = f.summary.lines;
    modules[mod].lines += s.count;
    modules[mod].covered += s.covered;
  }

  const sorted = Object.entries(modules).sort((a, b) => a[0].localeCompare(b[0]));
  let table = '| Module | Lines | Covered | Coverage |\n';
  table += '|--------|------:|--------:|---------:|\n';
  for (const [mod, s] of sorted) {
    const pct = s.lines > 0 ? ((s.covered / s.lines) * 100).toFixed(1) : '0.0';
    table += `| \`${mod}\` | ${s.lines} | ${s.covered} | ${pct}% |\n`;
  }

  const overallPct =
    totals.lines.count > 0
      ? ((totals.lines.covered / totals.lines.count) * 100).toFixed(1)
      : '0.0';
  table += `| **Total** | **${totals.lines.count}** | **${totals.lines.covered}** | **${overallPct}%** |\n`;

  return [
    MARKER,
    '',
    '> Generated by `cargo llvm-cov --workspace --summary-only` (nightly, excluding test files)',
    '',
    table,
    '',
    '<sub>Coverage data from CI run. Test files matching <code>tests?/</code> are excluded from line counts.</sub>',
  ].join('\n');
}

/**
 * Upsert the coverage comment on the PR, tolerating transient GitHub outages.
 *
 * deps: { github, context, fs, summaryPath, log?, sleep? }
 *   * missing summary file    -> { posted: false, reason: 'no-summary' } (no API calls).
 *   * happy path              -> upserts the comment -> { posted: true }.
 *   * persistent API failure  -> warns and returns { posted: false, reason: 'api-error' }
 *                                WITHOUT throwing (a comment must never fail the gate).
 */
export async function postCoverageComment(deps) {
  const {
    github,
    context,
    fs,
    summaryPath,
    log = { warn() {}, info() {} },
    sleep,
  } = deps;

  if (!fs.existsSync(summaryPath)) {
    log.info?.('No coverage summary found, skipping comment.');
    return { posted: false, reason: 'no-summary' };
  }

  const raw = fs.readFileSync(summaryPath, 'utf8');
  const data = JSON.parse(raw);
  const body = buildCommentBody(data);

  const { owner, repo } = context.repo;
  const issueNumber = context.issue.number;
  const retryOpts = { sleep };

  try {
    const { data: comments } = await retry(
      () => github.rest.issues.listComments({
        owner,
        repo,
        issue_number: issueNumber,
        per_page: 100,
      }),
      retryOpts,
    );

    for (const c of comments) {
      if (c.body && c.body.startsWith(MARKER)) {
        await retry(
          () => github.rest.issues.deleteComment({ owner, repo, comment_id: c.id }),
          retryOpts,
        );
      }
    }

    await retry(
      () => github.rest.issues.createComment({
        owner,
        repo,
        issue_number: issueNumber,
        body,
      }),
      retryOpts,
    );

    return { posted: true };
  } catch (err) {
    const detail = err && err.message ? err.message : String(err);
    log.warn(
      `Coverage comment posting failed after retries (non-fatal, coverage gate unaffected): ${detail}`,
    );
    return { posted: false, reason: 'api-error' };
  }
}
