//! Parametric geometry generation.
//!
//! A [`Model`] is a deterministic list of axis-aligned solid boxes derived from
//! a [`ProductBrief`]. The same representation drives:
//!   * the ASCII STL exporter (fabrication mesh),
//!   * the SVG orthographic render,
//!   * the cut list / BOM, and
//!   * an equivalent OpenSCAD program (for the high-fidelity CAD toolchain).
//!
//! All dimensions are millimetres. Geometry is intentionally simple (butt
//! joints, no fillets) so that it is fully deterministic and testable without
//! any external CAD dependency.

use super::brief::{Dimensions, ProductBrief, ProductType};

/// One axis-aligned rectangular solid, positioned by its minimum corner.
#[derive(Clone, Debug, PartialEq)]
pub struct SolidBox {
    /// Logical part name (e.g. "leg", "top", "side"). Groups the cut list.
    pub part: String,
    /// Minimum corner `[x, y, z]`.
    pub origin: [f64; 3],
    /// Extent `[dx, dy, dz]`, all strictly positive.
    pub size: [f64; 3],
}

impl SolidBox {
    fn new(part: impl Into<String>, origin: [f64; 3], size: [f64; 3]) -> Self {
        Self {
            part: part.into(),
            origin,
            size,
        }
    }

    /// The eight corner vertices, ordered for stable STL/rendering output.
    pub fn corners(&self) -> [[f64; 3]; 8] {
        let [x, y, z] = self.origin;
        let [dx, dy, dz] = self.size;
        [
            [x, y, z],
            [x + dx, y, z],
            [x + dx, y + dy, z],
            [x, y + dy, z],
            [x, y, z + dz],
            [x + dx, y, z + dz],
            [x + dx, y + dy, z + dz],
            [x, y + dy, z + dz],
        ]
    }

    /// Volume in mm³.
    pub fn volume(&self) -> f64 {
        self.size[0] * self.size[1] * self.size[2]
    }
}

/// A generated product model.
#[derive(Clone, Debug)]
pub struct Model {
    /// The brief this model was generated from.
    pub brief: ProductBrief,
    /// The solid parts that make up one unit.
    pub solids: Vec<SolidBox>,
}

impl Model {
    /// Generate the model geometry for the given brief.
    pub fn from_brief(brief: &ProductBrief) -> Self {
        let solids = match brief.product_type {
            ProductType::Panel => panel(&brief.dimensions),
            ProductType::Box => open_box(&brief.dimensions),
            ProductType::Table => table(brief),
            ProductType::Shelf => shelf(brief),
        };
        Self {
            brief: brief.clone(),
            solids,
        }
    }

    /// Bounding box `([min_x,min_y,min_z], [max_x,max_y,max_z])`.
    pub fn bounds(&self) -> ([f64; 3], [f64; 3]) {
        let mut min = [f64::INFINITY; 3];
        let mut max = [f64::NEG_INFINITY; 3];
        for s in &self.solids {
            for i in 0..3 {
                min[i] = min[i].min(s.origin[i]);
                max[i] = max[i].max(s.origin[i] + s.size[i]);
            }
        }
        if self.solids.is_empty() {
            (([0.0; 3]), ([0.0; 3]))
        } else {
            (min, max)
        }
    }

    /// Total solid material volume in mm³ (sum of all parts).
    pub fn material_volume_mm3(&self) -> f64 {
        self.solids.iter().map(SolidBox::volume).sum()
    }

    /// Emit an equivalent OpenSCAD program. Running this through `openscad`
    /// reproduces the same geometry as the built-in mesh, so the deterministic
    /// path and the CAD-toolchain path stay in agreement.
    pub fn to_openscad(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Generated by Simard Atelier for \"{}\" ({}).\n",
            self.brief.name.replace('"', "'"),
            self.brief.product_type.label()
        ));
        out.push_str("// Units: millimetres. Do not edit by hand.\n");
        out.push_str("$fn = 32;\n\nunion() {\n");
        for s in &self.solids {
            out.push_str(&format!(
                "  // {part}\n  translate([{x:.3}, {y:.3}, {z:.3}]) cube([{dx:.3}, {dy:.3}, {dz:.3}]);\n",
                part = s.part,
                x = s.origin[0],
                y = s.origin[1],
                z = s.origin[2],
                dx = s.size[0],
                dy = s.size[1],
                dz = s.size[2],
            ));
        }
        out.push_str("}\n");
        out
    }
}

fn panel(d: &Dimensions) -> Vec<SolidBox> {
    vec![SolidBox::new(
        "panel",
        [0.0, 0.0, 0.0],
        [d.length_mm, d.width_mm, d.thickness_mm],
    )]
}

/// Open-top box: a bottom plus four walls sitting on top of the bottom.
fn open_box(d: &Dimensions) -> Vec<SolidBox> {
    let t = d.thickness_mm;
    let (l, w, h) = (d.length_mm, d.width_mm, d.height_mm);
    vec![
        // Bottom panel.
        SolidBox::new("bottom", [0.0, 0.0, 0.0], [l, w, t]),
        // Front and back walls span the full length.
        SolidBox::new("wall-front", [0.0, 0.0, t], [l, t, h - t]),
        SolidBox::new("wall-back", [0.0, w - t, t], [l, t, h - t]),
        // Side walls fit between front and back.
        SolidBox::new("wall-left", [0.0, t, t], [t, w - 2.0 * t, h - t]),
        SolidBox::new("wall-right", [l - t, t, t], [t, w - 2.0 * t, h - t]),
    ]
}

/// Four-legged table: a top with four legs at the corners.
fn table(brief: &ProductBrief) -> Vec<SolidBox> {
    let d = &brief.dimensions;
    let (l, w, h, t) = (d.length_mm, d.width_mm, d.height_mm, d.thickness_mm);
    let leg = brief.leg_section_mm.min(l / 2.0).min(w / 2.0);
    let leg_h = (h - t).max(1.0);
    let mut solids = vec![SolidBox::new("top", [0.0, 0.0, leg_h], [l, w, t])];
    let corners = [
        [0.0, 0.0],
        [l - leg, 0.0],
        [0.0, w - leg],
        [l - leg, w - leg],
    ];
    for [x, y] in corners {
        solids.push(SolidBox::new("leg", [x, y, 0.0], [leg, leg, leg_h]));
    }
    solids
}

/// Bookshelf: two uprights, a top, a bottom, and evenly-spaced interior shelves.
fn shelf(brief: &ProductBrief) -> Vec<SolidBox> {
    let d = &brief.dimensions;
    let (l, depth, h, t) = (d.length_mm, d.width_mm, d.height_mm, d.thickness_mm);
    let mut solids = vec![
        // Left / right uprights span the full height.
        SolidBox::new("side", [0.0, 0.0, 0.0], [t, depth, h]),
        SolidBox::new("side", [l - t, 0.0, 0.0], [t, depth, h]),
        // Bottom and top fixed shelves between the uprights.
        SolidBox::new("bottom", [t, 0.0, 0.0], [l - 2.0 * t, depth, t]),
        SolidBox::new("top", [t, 0.0, h - t], [l - 2.0 * t, depth, t]),
    ];
    // Interior shelves evenly distributed in the clear interior height.
    let n = brief.shelf_count;
    if n > 0 {
        let interior = h - 2.0 * t;
        let gap = interior / (n as f64 + 1.0);
        for i in 1..=n {
            let z = t + gap * i as f64;
            solids.push(SolidBox::new("shelf", [t, 0.0, z], [l - 2.0 * t, depth, t]));
        }
    }
    solids
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::atelier::brief::{Dimensions, ProductType};

    fn brief(pt: ProductType) -> ProductBrief {
        ProductBrief {
            name: "Fixture".into(),
            product_type: pt,
            dimensions: Dimensions {
                length_mm: 1000.0,
                width_mm: 400.0,
                height_mm: 800.0,
                thickness_mm: 18.0,
            },
            material: "18mm plywood".into(),
            quantity: 1,
            shelf_count: 3,
            leg_section_mm: 50.0,
        }
    }

    #[test]
    fn panel_has_single_part() {
        let m = Model::from_brief(&brief(ProductType::Panel));
        assert_eq!(m.solids.len(), 1);
        assert_eq!(m.solids[0].part, "panel");
    }

    #[test]
    fn box_has_bottom_and_four_walls() {
        let m = Model::from_brief(&brief(ProductType::Box));
        assert_eq!(m.solids.len(), 5);
        assert!(m.solids.iter().any(|s| s.part == "bottom"));
        assert_eq!(
            m.solids
                .iter()
                .filter(|s| s.part.starts_with("wall"))
                .count(),
            4
        );
    }

    #[test]
    fn table_has_top_and_four_legs() {
        let m = Model::from_brief(&brief(ProductType::Table));
        assert_eq!(m.solids.iter().filter(|s| s.part == "leg").count(), 4);
        assert_eq!(m.solids.iter().filter(|s| s.part == "top").count(), 1);
    }

    #[test]
    fn shelf_part_count_scales_with_shelf_count() {
        let mut b = brief(ProductType::Shelf);
        b.shelf_count = 4;
        let m = Model::from_brief(&b);
        // 2 sides + bottom + top + 4 interior shelves
        assert_eq!(m.solids.len(), 8);
        assert_eq!(m.solids.iter().filter(|s| s.part == "shelf").count(), 4);
    }

    #[test]
    fn bounds_enclose_outer_dimensions() {
        let m = Model::from_brief(&brief(ProductType::Table));
        let (min, max) = m.bounds();
        assert_eq!(min, [0.0, 0.0, 0.0]);
        assert!((max[0] - 1000.0).abs() < 1e-6);
        assert!((max[1] - 400.0).abs() < 1e-6);
        assert!((max[2] - 800.0).abs() < 1e-6);
    }

    #[test]
    fn material_volume_is_positive() {
        let m = Model::from_brief(&brief(ProductType::Shelf));
        assert!(m.material_volume_mm3() > 0.0);
    }

    #[test]
    fn openscad_is_deterministic_and_has_a_cube_per_solid() {
        let m = Model::from_brief(&brief(ProductType::Table));
        let a = m.to_openscad();
        let b = m.to_openscad();
        assert_eq!(a, b);
        assert_eq!(a.matches("cube(").count(), m.solids.len());
        assert!(a.contains("union()"));
    }

    #[test]
    fn corners_returns_eight_distinct_points() {
        let s = SolidBox::new("x", [0.0, 0.0, 0.0], [10.0, 20.0, 30.0]);
        let c = s.corners();
        assert_eq!(c.len(), 8);
        assert_eq!(c[6], [10.0, 20.0, 30.0]);
    }
}
