//! OpenSCAD source generation.
//!
//! Emits a `.scad` program from an [`Assembly`]. The driving brief parameters
//! are written as named OpenSCAD variables at the top of the file (so the model
//! reads as parametric and is easy to tweak by hand), followed by the concrete
//! geometry — one coloured `translate(...) cube(...)` per placed panel instance,
//! grouped and commented by panel role. Rust remains the single source of truth
//! for geometry; the variables document the brief that produced it.

use std::fmt::Write as _;

use super::brief::ProductBrief;
use super::geometry::Assembly;

/// Deterministic colour per panel role, so renders read clearly.
fn role_color(label: &str) -> &'static str {
    match label {
        "side" => "[0.82, 0.71, 0.55]",
        "top-bottom" | "top" | "seat" => "[0.90, 0.80, 0.62]",
        "shelf" => "[0.76, 0.63, 0.47]",
        "back" | "front-back" | "front" => "[0.70, 0.58, 0.42]",
        "leg" => "[0.55, 0.43, 0.30]",
        "apron" => "[0.62, 0.50, 0.36]",
        _ => "[0.78, 0.68, 0.52]",
    }
}

fn fmt_mm(v: f64) -> String {
    // Trim to 0.001mm; OpenSCAD is millimetre-native.
    let r = (v * 1000.0).round() / 1000.0;
    if r == r.trunc() {
        format!("{}", r as i64)
    } else {
        format!("{r}")
    }
}

/// Sanitize an untrusted brief string for safe interpolation into a single-line
/// OpenSCAD `//` comment. The brief is explicitly untrusted input, so we must
/// prevent a value containing a newline (or other control character) from
/// terminating the comment and injecting executable OpenSCAD statements. We
/// collapse any control character (including `\n`/`\r`/`\t`) to a space and
/// map `"` to `'` so the text also stays inert inside quoted contexts.
fn comment_safe(raw: &str) -> String {
    let cleaned: String = raw
        .chars()
        .map(|c| match c {
            '"' => '\'',
            c if c.is_control() => ' ',
            c => c,
        })
        .collect();
    cleaned.trim().to_string()
}

/// Generate OpenSCAD source for the assembly produced from `brief`.
pub fn generate_scad(brief: &ProductBrief, assembly: &Assembly) -> String {
    let mut out = String::new();
    let d = brief.dimensions_mm;

    let _ = writeln!(
        out,
        "// Generated by Simard Atelier — parametric model for \"{}\".",
        comment_safe(&brief.name)
    );
    let _ = writeln!(out, "// Product kind: {}", assembly.kind.label());
    let _ = writeln!(
        out,
        "// Do not hand-edit geometry; re-run `simard atelier build` after changing the brief.\n"
    );

    // --- Driving parameters (parametric documentation) -----------------------
    let _ = writeln!(out, "// ---- Brief parameters ----");
    let _ = writeln!(out, "overall_width  = {}; // mm", fmt_mm(d.width));
    let _ = writeln!(out, "overall_depth  = {}; // mm", fmt_mm(d.depth));
    let _ = writeln!(out, "overall_height = {}; // mm", fmt_mm(d.height));
    let _ = writeln!(
        out,
        "thickness      = {}; // mm ({})",
        fmt_mm(brief.material.thickness_mm),
        comment_safe(&brief.material.name)
    );
    if let Some(s) = brief.parameters.shelves {
        let _ = writeln!(out, "shelves        = {s};");
    }
    if let Some(b) = brief.parameters.back_panel {
        let _ = writeln!(out, "back_panel     = {b};");
    }
    if let Some(l) = brief.parameters.leg_size_mm {
        let _ = writeln!(out, "leg_size       = {}; // mm", fmt_mm(l));
    }
    let _ = writeln!(out, "$fn = 24;\n");

    // --- Geometry ------------------------------------------------------------
    let _ = writeln!(out, "module panel(pos, size) {{");
    let _ = writeln!(out, "    translate(pos) cube(size);");
    let _ = writeln!(out, "}}\n");

    for panel in &assembly.panels {
        let _ = writeln!(
            out,
            "// {} — {} × {} × {} mm ({} off, grain: {})",
            panel.label,
            fmt_mm(panel.length_mm),
            fmt_mm(panel.width_mm),
            fmt_mm(panel.thickness_mm),
            panel.qty(),
            panel.grain.label(),
        );
        let _ = writeln!(out, "color({}) {{", role_color(&panel.label));
        for inst in &panel.instances {
            let _ = writeln!(
                out,
                "    panel([{}, {}, {}], [{}, {}, {}]);",
                fmt_mm(inst.origin[0]),
                fmt_mm(inst.origin[1]),
                fmt_mm(inst.origin[2]),
                fmt_mm(inst.size[0]),
                fmt_mm(inst.size[1]),
                fmt_mm(inst.size[2]),
            );
        }
        let _ = writeln!(out, "}}\n");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::atelier::brief::ProductBrief;
    use crate::atelier::geometry::generate;

    fn brief(kind: &str) -> ProductBrief {
        let json = format!(
            r#"{{"name":"Demo \"unit\"","kind":"{kind}",
                "dimensions_mm":{{"width":800,"depth":300,"height":1000}},
                "material":{{"name":"Birch ply","thickness_mm":18,"grain":true}},
                "parameters":{{"shelves":2,"back_panel":true}}}}"#
        );
        ProductBrief::from_json_bytes(json.as_bytes()).unwrap()
    }

    #[test]
    fn emits_parameters_and_geometry() {
        let b = brief("bookcase");
        let a = generate(&b);
        let scad = generate_scad(&b, &a);
        assert!(scad.contains("overall_width  = 800;"));
        assert!(scad.contains("overall_height = 1000;"));
        assert!(scad.contains("thickness      = 18;"));
        assert!(scad.contains("shelves        = 2;"));
        assert!(scad.contains("module panel(pos, size)"));
        assert!(scad.contains("translate(pos) cube(size);"));
        // one cube call per instance
        let cube_calls = scad.matches("    panel([").count();
        assert_eq!(cube_calls as u32, a.instance_count());
    }

    #[test]
    fn escapes_quotes_in_name() {
        let b = brief("box");
        let a = generate(&b);
        let scad = generate_scad(&b, &a);
        assert!(!scad.contains(r#"Demo "unit""#));
        assert!(scad.contains("Demo 'unit'"));
    }

    #[test]
    fn sanitizes_newlines_in_untrusted_brief_strings() {
        // A newline in an untrusted brief string must not terminate the `//`
        // comment and inject an executable OpenSCAD statement.
        let json = r#"{"name":"evil\nimport(\"/etc/passwd\");","kind":"box",
            "dimensions_mm":{"width":100,"depth":80,"height":60},
            "material":{"name":"ply\nsphere(999);","thickness_mm":6}}"#;
        let b = ProductBrief::from_json_bytes(json.as_bytes()).unwrap();
        let a = generate(&b);
        let scad = generate_scad(&b, &a);
        // The injected statements must remain inside comment lines — no bare
        // `import(` or `sphere(` at the start of any (trimmed) line.
        for line in scad.lines() {
            let t = line.trim_start();
            assert!(
                !t.starts_with("import("),
                "import() escaped into executable position: {line:?}"
            );
            assert!(
                !t.starts_with("sphere("),
                "sphere() escaped into executable position: {line:?}"
            );
        }
        assert!(comment_safe("a\nb\tc").find(['\n', '\r', '\t']).is_none());
    }

    #[test]
    fn fmt_mm_trims_integers() {
        assert_eq!(fmt_mm(18.0), "18");
        assert_eq!(fmt_mm(18.5), "18.5");
        assert_eq!(fmt_mm(0.0), "0");
    }

    #[test]
    fn colors_are_role_specific() {
        assert_ne!(role_color("leg"), role_color("shelf"));
        assert_eq!(role_color("unknown-role"), role_color("also-unknown"));
    }
}
