//! Dashboard delivery.
//!
//! Renders the interactive dashboard as a self-contained `dashboard.html` that
//! draws every designed chart with [Plotly.js] (loaded from a CDN), plus an
//! optional [Streamlit] `app.py` that re-renders the same analysis. The HTML is
//! the primary, dependency-free deliverable: open it in any browser or serve it
//! with `simard cartographer serve`.
//!
//! [Plotly.js]: https://plotly.com/javascript/
//! [Streamlit]: https://streamlit.io/

use super::brief::DashboardBrief;
use super::dataset::DatasetProfile;
use super::viz::ChartSpec;

/// Pinned Plotly.js version served from the official CDN.
pub const PLOTLY_CDN: &str = "https://cdn.plot.ly/plotly-2.35.2.min.js";

/// Escape a string for inclusion in HTML text / attributes.
fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Escape a JSON string so it can be safely inlined inside a `<script>` tag.
///
/// `serde_json` does not escape `<` or `>`, so a dataset-derived value could
/// otherwise smuggle `</script>`, `<!--`, or `<script` into the raw-text
/// content of the `<script>` element and break (or escape) its framing. Every
/// `<`/`>` inside the JSON is only ever part of a string literal, so replacing
/// them with their `\uXXXX` escapes is loss-less for the parsed value while
/// neutralising all three HTML script-state sequences. U+2028/U+2029 are also
/// escaped because the blob is inlined as a JS object literal.
fn script_safe_json(json: &str) -> String {
    json.replace('<', "\\u003c")
        .replace('>', "\\u003e")
        .replace('\u{2028}', "\\u2028")
        .replace('\u{2029}', "\\u2029")
}

/// Render the interactive dashboard HTML for the designed charts.
pub fn render_html(
    brief: &DashboardBrief,
    profile: &DatasetProfile,
    charts: &[ChartSpec],
) -> String {
    let title = html_escape(brief.title());
    let question = html_escape(brief.question.trim());

    let charts_json = serde_json::to_string(charts).unwrap_or_else(|_| "[]".to_string());
    let charts_json = script_safe_json(&charts_json);

    let mut findings = String::new();
    for chart in charts {
        findings.push_str(&format!("      <li>{}</li>\n", html_escape(&chart.caption)));
    }
    if findings.is_empty() {
        findings.push_str("      <li>No chartable structure was found in this dataset.</li>\n");
    }

    let mut sections = String::new();
    for chart in charts {
        sections.push_str(&format!(
            "    <section class=\"card\">\n      <h2>{}</h2>\n      \
             <div id=\"{}\" class=\"chart\"></div>\n      <p class=\"caption\">{}</p>\n    </section>\n",
            html_escape(&chart.title),
            html_escape(&chart.id),
            html_escape(&chart.caption),
        ));
    }
    if sections.is_empty() {
        sections.push_str(
            "    <section class=\"card\"><p>No charts could be generated for this dataset.</p></section>\n",
        );
    }

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="generator" content="Simard Cartographer" />
  <title>{title}</title>
  <script src="{cdn}" charset="utf-8"></script>
  <style>
    :root {{ color-scheme: light dark; }}
    body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
            margin: 0; padding: 0 1rem 3rem; max-width: 1100px; margin: 0 auto;
            line-height: 1.5; }}
    header {{ padding: 2rem 0 1rem; border-bottom: 1px solid rgba(128,128,128,.3); }}
    h1 {{ margin: 0 0 .25rem; font-size: 1.8rem; }}
    .question {{ font-size: 1.1rem; opacity: .85; margin: .25rem 0 0; }}
    .meta {{ font-size: .9rem; opacity: .7; }}
    .findings {{ margin: 1.5rem 0; }}
    .card {{ border: 1px solid rgba(128,128,128,.3); border-radius: 10px;
             padding: 1rem 1.25rem; margin: 1.5rem 0; }}
    .card h2 {{ margin-top: 0; font-size: 1.2rem; }}
    .chart {{ width: 100%; height: 420px; }}
    .caption {{ opacity: .8; font-size: .95rem; margin: .5rem 0 0; }}
    footer {{ opacity: .6; font-size: .85rem; margin-top: 2rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p class="question"><strong>Question:</strong> {question}</p>
    <p class="meta">{rows} rows &middot; {cols} columns</p>
  </header>

  <div class="findings">
    <h2>Key findings</h2>
    <ul>
{findings}    </ul>
  </div>

{sections}
  <footer>Generated by Simard Cartographer. Charts rendered client-side with Plotly.js.</footer>

  <script>
    const CHARTS = {charts_json};
    const layoutBase = {{
      margin: {{ t: 10, r: 10, b: 50, l: 60 }},
      paper_bgcolor: "rgba(0,0,0,0)",
      plot_bgcolor: "rgba(0,0,0,0)",
      font: {{ family: "inherit" }},
    }};
    function traceFor(c) {{
      const d = c.data;
      switch (d.kind) {{
        case "histogram": return [{{ type: "histogram", x: d.values }}];
        case "bar": return [{{ type: "bar", x: d.labels, y: d.values }}];
        case "line": return [{{ type: "scatter", mode: "lines+markers", x: d.labels, y: d.values }}];
        case "scatter": return [{{ type: "scatter", mode: "markers", x: d.x, y: d.y,
                                   marker: {{ size: 7, opacity: .7 }} }}];
        default: return [];
      }}
    }}
    function render() {{
      if (typeof Plotly === "undefined") return;
      for (const c of CHARTS) {{
        const el = document.getElementById(c.id);
        if (!el) continue;
        const layout = Object.assign({{}}, layoutBase, {{
          xaxis: {{ title: c.x_label }},
          yaxis: {{ title: c.y_label }},
        }});
        Plotly.newPlot(el, traceFor(c), layout, {{ responsive: true, displaylogo: false }});
      }}
    }}
    if (document.readyState === "loading") {{
      document.addEventListener("DOMContentLoaded", render);
    }} else {{
      render();
    }}
  </script>
</body>
</html>
"#,
        title = title,
        cdn = PLOTLY_CDN,
        question = question,
        rows = profile.row_count,
        cols = profile.column_count,
        findings = findings,
        sections = sections,
        charts_json = charts_json,
    )
}

/// Escape a string for inclusion in a Python double-quoted string literal, so a
/// brief field containing a quote, backslash, or newline cannot break (or inject
/// into) the generated `app.py`.
fn py_str_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

/// Render an optional Streamlit app that re-renders the analysis from
/// `analysis.json`. Written to the package as `app.py`; runnable wherever
/// Streamlit + Plotly are installed (`streamlit run app.py`).
pub fn render_streamlit_app(brief: &DashboardBrief) -> String {
    // A Python string, generated at runtime into the output package. No Python
    // source is committed to the (pure-Rust) repo tree.
    let title = py_str_escape(brief.title());
    let question = py_str_escape(brief.question.trim());
    format!(
        r#"# Generated by Simard Cartographer — Streamlit delivery for a data story.
# Run with:  streamlit run app.py
import json
import pathlib

import streamlit as st
import plotly.graph_objects as go

st.set_page_config(page_title="{title}", layout="wide")

DATA = json.loads((pathlib.Path(__file__).parent / "analysis.json").read_text())

st.title("{title}")
st.markdown("**Question:** {question}")

profile = DATA.get("profile", {{}})
st.caption(f"{{profile.get('row_count', 0)}} rows · {{profile.get('column_count', 0)}} columns")

st.subheader("Key findings")
for chart in DATA.get("charts", []):
    st.markdown(f"- {{chart['caption']}}")

def figure(chart):
    d = chart["data"]
    kind = d["kind"]
    if kind == "histogram":
        fig = go.Figure(go.Histogram(x=d["values"]))
    elif kind == "bar":
        fig = go.Figure(go.Bar(x=d["labels"], y=d["values"]))
    elif kind == "line":
        fig = go.Figure(go.Scatter(x=d["labels"], y=d["values"], mode="lines+markers"))
    elif kind == "scatter":
        fig = go.Figure(go.Scatter(x=d["x"], y=d["y"], mode="markers"))
    else:
        fig = go.Figure()
    fig.update_layout(xaxis_title=chart["x_label"], yaxis_title=chart["y_label"], margin=dict(t=10))
    return fig

for chart in DATA.get("charts", []):
    st.subheader(chart["title"])
    st.plotly_chart(figure(chart), use_container_width=True)
    st.caption(chart["caption"])
"#,
        title = title,
        question = question,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cartographer::brief::DatasetFormat;
    use crate::cartographer::dataset::Dataset;
    use crate::cartographer::viz::design_charts;

    const CSV: &str = "region,revenue,date\n\
        North,1200,2024-01-01\n\
        South,950,2024-01-02\n\
        North,1500,2024-01-03\n";

    fn setup() -> (DashboardBrief, DatasetProfile, Vec<ChartSpec>) {
        let brief =
            DashboardBrief::from_dataset_and_question("d.csv", "Which region earns most?").unwrap();
        let ds = Dataset::from_bytes(CSV.as_bytes(), DatasetFormat::Csv, 1000).unwrap();
        let profile = ds.profile();
        let charts = design_charts(&brief, &ds);
        (brief, profile, charts)
    }

    #[test]
    fn html_is_self_contained_and_loads_plotly() {
        let (brief, profile, charts) = setup();
        let html = render_html(&brief, &profile, &charts);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains(PLOTLY_CDN));
        assert!(html.contains("Plotly.newPlot"));
    }

    #[test]
    fn html_embeds_chart_divs_and_data() {
        let (brief, profile, charts) = setup();
        let html = render_html(&brief, &profile, &charts);
        for chart in &charts {
            assert!(html.contains(&format!("id=\"{}\"", chart.id)));
        }
        assert!(html.contains("const CHARTS ="));
    }

    #[test]
    fn html_escapes_question() {
        let brief = DashboardBrief::from_dataset_and_question("d.csv", "a <b> & \"c\"").unwrap();
        let ds = Dataset::from_bytes(CSV.as_bytes(), DatasetFormat::Csv, 1000).unwrap();
        let html = render_html(&brief, &ds.profile(), &[]);
        assert!(html.contains("a &lt;b&gt; &amp; &quot;c&quot;"));
        assert!(!html.contains("a <b> & \"c\""));
    }

    #[test]
    fn script_safe_json_neutralizes_script_state_sequences() {
        // `</script>`, `<!--`, and `<script` must all be defanged, because a
        // dataset-derived label could carry any of them into the <script> body.
        let out = script_safe_json("{\"x\":\"</script><!--<script>\"}");
        assert!(!out.contains("</script>"));
        assert!(!out.contains("<!--"));
        assert!(!out.contains("<script"));
        assert!(!out.contains('<'));
        assert!(!out.contains('>'));
        assert!(out.contains("\\u003c"));
    }

    #[test]
    fn malicious_cell_value_cannot_break_script_framing() {
        // A Bar label crafted to enter the HTML "script data double escaped"
        // state must not leak an unescaped `<` into the rendered <script>.
        let csv = "region,revenue\n<!--<script>,10\nNorth,20\n";
        let brief = DashboardBrief::from_dataset_and_question("d.csv", "q?").unwrap();
        let ds = Dataset::from_bytes(csv.as_bytes(), DatasetFormat::Csv, 1000).unwrap();
        let charts = design_charts(&brief, &ds);
        let html = render_html(&brief, &ds.profile(), &charts);
        let script = html
            .split("<script>")
            .nth(1)
            .and_then(|s| s.split("</script>").next())
            .expect("inline <script> block");
        assert!(!script.contains("<!--"));
        assert!(!script.contains("<script"));
    }

    #[test]
    fn streamlit_app_reads_analysis_json() {
        let (brief, _, _) = setup();
        let app = render_streamlit_app(&brief);
        assert!(app.contains("streamlit run app.py"));
        assert!(app.contains("analysis.json"));
        assert!(app.contains("st.plotly_chart"));
    }

    #[test]
    fn streamlit_app_escapes_dangerous_brief_fields() {
        // A question with a newline, quote, and trailing backslash must not
        // corrupt the generated Python string literals.
        let brief =
            DashboardBrief::from_dataset_and_question("d.csv", "line1\n\"q\" ends\\").unwrap();
        let app = render_streamlit_app(&brief);
        // No raw newline inside the interpolated question literal, and the
        // backslash/quote are escaped.
        assert!(app.contains("**Question:** line1\\n\\\"q\\\" ends\\\\"));
    }
}
