//! Shared types for the OODA loop.

use std::collections::HashMap;
use std::fmt::{self, Display, Formatter};

use crate::cognitive_memory::CognitiveMemoryOps;
use crate::engineer_worktree::EngineerWorktree;
use crate::goal_curation::{ActiveGoal, GoalBoard, GoalProgress};
use crate::gym_client::GymClient;
use crate::gym_scoring::GymSuiteScore;
use crate::knowledge_client::KnowledgeClient;
use crate::memory_cognitive::CognitiveStatistics;
use crate::memory_consolidation::PreparedContext;
use crate::self_improve::ImprovementCycle;

/// The four phases of a single OODA cycle, plus Sleep between cycles.
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OodaPhase {
    Observe,
    Orient,
    Decide,
    Act,
    Sleep,
}

impl Display for OodaPhase {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Observe => f.write_str("observe"),
            Self::Orient => f.write_str("orient"),
            Self::Decide => f.write_str("decide"),
            Self::Act => f.write_str("act"),
            Self::Sleep => f.write_str("sleep"),
        }
    }
}

/// Mutable state carried across OODA cycles.
pub struct OodaState {
    pub current_phase: OodaPhase,
    pub active_goals: GoalBoard,
    pub cycle_count: u32,
    pub last_observation: Option<Observation>,
    /// Improvement proposals generated by post-act review, drained by observe().
    pub review_improvements: Vec<ImprovementCycle>,
    /// Context gathered from cognitive memory during the preparation sub-phase.
    /// Populated each cycle so the Act phase can use recalled facts, triggered
    /// prospectives, and relevant procedures when advancing goals.
    pub prepared_context: Option<PreparedContext>,
    /// Unix epoch (seconds) when the current cycle started.
    pub cycle_start_epoch: u64,
    /// Human-readable summary from the last completed cycle.
    pub last_cycle_summary: Option<String>,
    /// Duration in seconds of the last completed cycle.
    pub last_cycle_duration_secs: Option<u64>,
    /// Per-goal consecutive-failure count. Incremented after each Act phase
    /// when an outcome with `goal_id == Some(g)` has `success == false`,
    /// reset to 0 on success. Used by Orient to demote chronically failing
    /// goals so the daemon stops burning budget on the same broken target.
    pub goal_failure_counts: HashMap<String, u32>,
    /// Per-goal isolated git worktrees owned by spawned engineers (issue #1197).
    /// Keyed by `goal_id`; cleaned up by the reaper path when the engineer's
    /// outcome is validated, or via `EngineerWorktree::Drop` if the entry is
    /// removed before explicit `cleanup()` runs.
    pub engineer_worktrees: HashMap<String, EngineerWorktree>,
    /// Cycle number at which the automatic distillation scheduler last ran a
    /// pass. The scheduler's interval trigger fires when
    /// `cycle_count - last_distill_cycle >= distill_interval_cycles`. Not
    /// persisted across restarts (resets to 0); worst case is an extra
    /// distillation pass shortly after boot. Issue #2327, R4.
    pub last_distill_cycle: u32,
    /// Per-goal consecutive *no-action* count driving the Fix-3 no-progress
    /// breaker. The sibling of [`Self::goal_failure_counts`]: that counter
    /// bounds repeated brain *failures* (`success == false`), this one bounds
    /// repeated `NO ACTION` / "I'll verify concretely…" cycles that record
    /// `success == true` but ship nothing. Incremented after the Act phase for
    /// each goal whose outcome
    /// [`outcome_made_no_progress`](crate::ooda_actions::outcome_made_no_progress),
    /// reset on real progress, and — once the breaker fires — resolved via the
    /// done-gate ladder (mark done / drop / escalate). See
    /// `docs/concepts/steerable-ooda-daemon.md` ("The no-progress breaker (Fix 3)").
    pub no_progress_tracker: crate::goal_curation::NoProgressTracker,
}

impl OodaState {
    pub fn new(goals: GoalBoard) -> Self {
        Self {
            current_phase: OodaPhase::Observe,
            active_goals: goals,
            cycle_count: 0,
            last_observation: None,
            review_improvements: Vec::new(),
            prepared_context: None,
            cycle_start_epoch: 0,
            last_cycle_summary: None,
            last_cycle_duration_secs: None,
            goal_failure_counts: HashMap::new(),
            engineer_worktrees: HashMap::new(),
            last_distill_cycle: 0,
            no_progress_tracker: crate::goal_curation::NoProgressTracker::new(),
        }
    }

    /// Remove `goal_failure_counts` entries for goal IDs that are no longer
    /// present on the active board. Prevents unbounded growth when goals are
    /// archived or removed over many cycles (issue #2167).
    pub fn prune_stale_failure_counts(&mut self) {
        let active_ids: std::collections::HashSet<&str> = self
            .active_goals
            .active
            .iter()
            .map(|g| g.id.as_str())
            .collect();
        self.goal_failure_counts
            .retain(|id, _| active_ids.contains(id.as_str()));
        // Keep the Fix-3 no-progress counters bounded to live goals too.
        self.no_progress_tracker
            .retain_goals(&active_ids.iter().map(|s| s.to_string()).collect());
    }
}

/// A single goal's status snapshot for observation.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct GoalSnapshot {
    pub id: String,
    pub description: String,
    pub progress: GoalProgress,
}

impl From<&ActiveGoal> for GoalSnapshot {
    fn from(g: &ActiveGoal) -> Self {
        Self {
            id: g.id.clone(),
            description: g.description.clone(),
            progress: g.status.clone(),
        }
    }
}

/// Snapshot of the local environment: git state, issues, recent commits.
#[derive(Clone, Debug, Default, serde::Serialize, serde::Deserialize)]
pub struct EnvironmentSnapshot {
    /// Output of `git status --porcelain` (empty string if unavailable).
    pub git_status: String,
    /// Open issue titles from `gh issue list` (empty if unavailable).
    pub open_issues: Vec<String>,
    /// Recent commit one-liners from `git log --oneline -10`.
    pub recent_commits: Vec<String>,
}

/// Everything gathered during the Observe phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Observation {
    pub goal_statuses: Vec<GoalSnapshot>,
    pub gym_health: Option<GymSuiteScore>,
    pub memory_stats: CognitiveStatistics,
    pub pending_improvements: Vec<ImprovementCycle>,
    /// Local environment state for goal assessment.
    pub environment: EnvironmentSnapshot,
    /// Set when the eval watchdog has detected a dead signal — i.e. the
    /// gym progressive suite has been silently producing zeros (or
    /// pixel-identical scores) across multiple distinct scenarios for
    /// long enough that the OODA loop must NOT trust further eval-derived
    /// decisions until an operator investigates.
    ///
    /// Reason text is logged at ERROR level by observe(); orient pushes
    /// a `__eval_watchdog__` priority with maximum urgency so the loop
    /// surfaces the failure instead of marching past it.
    pub eval_watchdog: Option<String>,
}

/// A ranked priority produced during the Orient phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Priority {
    pub goal_id: String,
    pub urgency: f64,
    pub reason: String,
}

/// The kind of action the OODA loop can dispatch.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ActionKind {
    AdvanceGoal,
    RunImprovement,
    ConsolidateMemory,
    ResearchQuery,
    RunGymEval,
    BuildSkill,
    LaunchSession,
    PollDeveloperActivity,
    ExtractIdeas,
    SafeUpdate,
}

impl Display for ActionKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::AdvanceGoal => f.write_str("advance-goal"),
            Self::RunImprovement => f.write_str("run-improvement"),
            Self::ConsolidateMemory => f.write_str("consolidate-memory"),
            Self::ResearchQuery => f.write_str("research-query"),
            Self::RunGymEval => f.write_str("run-gym-eval"),
            Self::BuildSkill => f.write_str("build-skill"),
            Self::LaunchSession => f.write_str("launch-session"),
            Self::PollDeveloperActivity => f.write_str("poll-developer-activity"),
            Self::ExtractIdeas => f.write_str("extract-ideas"),
            Self::SafeUpdate => f.write_str("safe-update"),
        }
    }
}

/// A planned action selected during the Decide phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct PlannedAction {
    pub kind: ActionKind,
    pub goal_id: Option<String>,
    pub description: String,
}

/// Outcome of dispatching a single action.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ActionOutcome {
    pub action: PlannedAction,
    pub success: bool,
    pub detail: String,
}

/// Report for one complete OODA cycle.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct CycleReport {
    pub cycle_number: u32,
    pub observation: Observation,
    pub priorities: Vec<Priority>,
    pub planned_actions: Vec<PlannedAction>,
    pub outcomes: Vec<ActionOutcome>,
    /// Per-cycle forensic trace of prompt-driven OODA brain judgments
    /// (act / decide / orient). Empty when no brain calls fired this cycle
    /// or when reading older reports written before this field existed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub brain_judgments: Vec<crate::ooda_brain::BrainJudgmentRecord>,
}

/// Configuration for the OODA loop.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct OodaConfig {
    pub max_concurrent_actions: u32,
    pub improvement_threshold: f64,
    pub gym_suite_id: String,
    /// Daily budget in USD (from SIMARD_DAILY_BUDGET_USD env or dashboard).
    pub daily_budget_usd: f64,
    /// Weekly budget in USD (from SIMARD_WEEKLY_BUDGET_USD env or dashboard).
    pub weekly_budget_usd: f64,
    /// Automatic distillation scheduler: fire when the undistilled-episode
    /// count reaches this value (`SIMARD_DISTILL_MIN_EPISODES`, default 25).
    /// Issue #2327, R4.
    #[serde(default = "default_distill_min_episodes")]
    pub distill_min_episodes: u32,
    /// Automatic distillation scheduler: fire when this many OODA cycles have
    /// elapsed since the last pass (`SIMARD_DISTILL_INTERVAL_CYCLES`, default
    /// 50). Issue #2327, R4.
    #[serde(default = "default_distill_interval_cycles")]
    pub distill_interval_cycles: u32,
    /// Recurrence threshold before a repeated *verified* failure becomes a
    /// `lesson:` procedure (`SIMARD_LESSON_RECURRENCE_THRESHOLD`, default 2).
    /// Issues #2441/#2458. `1` would distil one-off failures (not recommended).
    #[serde(default = "default_lesson_recurrence_threshold")]
    pub lesson_recurrence_threshold: u32,
    /// AIMD adaptive scaler. Populated when `SIMARD_SCALING=auto`.
    /// Skipped during (de)serialization — reconstructed from env on boot.
    #[serde(skip)]
    pub scaler: Option<std::sync::Arc<super::adaptive_scaling::AdaptiveScaler>>,
}

fn default_distill_min_episodes() -> u32 {
    crate::memory_consolidation::scheduler::DistillSchedule::DEFAULT_MIN_EPISODES
}

fn default_distill_interval_cycles() -> u32 {
    crate::memory_consolidation::scheduler::DistillSchedule::DEFAULT_INTERVAL_CYCLES
}

fn default_lesson_recurrence_threshold() -> u32 {
    crate::memory_consolidation::reflection_lessons::LESSON_RECURRENCE_THRESHOLD
}

impl Default for OodaConfig {
    fn default() -> Self {
        // Issue #2935: per-OODA-cycle goal-coverage parallelism ceiling.
        // Precedence: SIMARD_OODA_MAX_CONCURRENT (preferred) > legacy
        // SIMARD_MAX_CONCURRENT_ACTIONS > default 24. Each source is fail-closed
        // INDEPENDENTLY: a present-but-invalid value uses the default 24 and does
        // NOT fall through to a lower-precedence source, so a typo in the
        // preferred variable can never silently resurrect a stale legacy value.
        // Both are bounds-validated to [MAX_CONCURRENT_MIN, MAX_CONCURRENT_MAX].
        let max_concurrent_actions = if std::env::var("SIMARD_OODA_MAX_CONCURRENT").is_ok() {
            env_u32_bounded(
                "SIMARD_OODA_MAX_CONCURRENT",
                DEFAULT_MAX_CONCURRENT_ACTIONS,
                MAX_CONCURRENT_MIN,
                MAX_CONCURRENT_MAX,
            )
        } else {
            env_u32_bounded(
                "SIMARD_MAX_CONCURRENT_ACTIONS",
                DEFAULT_MAX_CONCURRENT_ACTIONS,
                MAX_CONCURRENT_MIN,
                MAX_CONCURRENT_MAX,
            )
        };
        let scaler = match std::env::var("SIMARD_SCALING").as_deref() {
            Ok("auto") => {
                // Issue #2935: the AIMD ceiling IS the configured max (was 4×).
                // This makes the configured value a TRUE per-cycle ceiling — 24
                // means at most 24, not 96 — while the scaler still backs off on
                // pressure and additively recovers up to, never beyond, the
                // ceiling. It starts at the max so the cap is reached at once.
                let ceiling = max_concurrent_actions.max(MAX_CONCURRENT_MIN);
                Some(std::sync::Arc::new(
                    super::adaptive_scaling::AdaptiveScaler::new(
                        max_concurrent_actions,
                        1,
                        ceiling,
                    ),
                ))
            }
            _ => None,
        };
        Self {
            max_concurrent_actions,
            improvement_threshold: 0.02,
            gym_suite_id: "progressive".to_string(),
            daily_budget_usd: env_f64("SIMARD_DAILY_BUDGET_USD", 500.0),
            weekly_budget_usd: env_f64("SIMARD_WEEKLY_BUDGET_USD", 2500.0),
            distill_min_episodes: env_u32(
                "SIMARD_DISTILL_MIN_EPISODES",
                default_distill_min_episodes(),
            ),
            distill_interval_cycles: env_u32(
                "SIMARD_DISTILL_INTERVAL_CYCLES",
                default_distill_interval_cycles(),
            ),
            lesson_recurrence_threshold: env_u32(
                crate::memory_consolidation::reflection_lessons::LESSON_RECURRENCE_THRESHOLD_ENV,
                default_lesson_recurrence_threshold(),
            ),
            scaler,
        }
    }
}

fn env_f64(key: &str, default: f64) -> f64 {
    std::env::var(key)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

fn env_u32(key: &str, default: u32) -> u32 {
    std::env::var(key)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

/// Default per-OODA-cycle goal-coverage parallelism ceiling (issue #2935).
///
/// Raised from the arbitrary historical value of 5 to 24 so that, when
/// resources allow and goals are genuinely independent, a single cycle can
/// cover up to 24 uncovered incomplete goals instead of the ~6 previously
/// observed live. This is a CEILING, not a guarantee: the resource-aware
/// admission gate and the overlap/dependency gate still bound actual spawns.
pub const DEFAULT_MAX_CONCURRENT_ACTIONS: u32 = 24;

/// Lower bound for a validated concurrency override. Zero would stall the
/// daemon (no action could ever dispatch), so 1 is the minimum sane value.
pub const MAX_CONCURRENT_MIN: u32 = 1;

/// Upper bound for a validated concurrency override. Well above the 24 target
/// yet below anything resource-realistic; values beyond this are treated as an
/// operator misconfiguration and rejected (fail closed).
pub const MAX_CONCURRENT_MAX: u32 = 64;

/// Parses an unsigned-integer env var with fail-closed bounds validation.
///
/// - Absent key → returns `default` silently (an unset var is not a
///   misconfiguration, so it does not warrant a warning).
/// - Present but non-numeric, or numeric yet outside `[min, max]` → logs a
///   `tracing::warn!` and returns `default`. Failing closed means a bad
///   operator value can never silently escalate concurrency or stall the
///   daemon; the effective value is always the known-safe fallback.
fn env_u32_bounded(key: &str, default: u32, min: u32, max: u32) -> u32 {
    match std::env::var(key) {
        Err(_) => default,
        Ok(raw) => match raw.trim().parse::<u32>() {
            Ok(v) if v >= min && v <= max => v,
            _ => {
                tracing::warn!(
                    key,
                    value = %raw,
                    min,
                    max,
                    default,
                    "invalid value for {key}; using default {default}"
                );
                default
            }
        },
    }
}

/// Serializable view of [`OodaState`] suitable for round-tripping through
/// recipe steps via JSON. Excludes:
/// - `engineer_worktrees` — OS handles owning git worktrees; recipe steps
///   re-key these by `goal_id` from the parent process state.
/// - The `OodaClients` (memory store, gym, knowledge) — instantiated per
///   helper-bin invocation from the configured `state_root`.
///
/// Use `OodaStateSnapshot::from(&state)` to capture, and
/// `snapshot.apply_to(&mut state)` to restore the round-tripped fields.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct OodaStateSnapshot {
    pub current_phase: OodaPhase,
    pub active_goals: GoalBoard,
    pub cycle_count: u32,
    pub last_observation: Option<Observation>,
    pub review_improvements: Vec<ImprovementCycle>,
    pub prepared_context: Option<PreparedContext>,
    pub cycle_start_epoch: u64,
    pub last_cycle_summary: Option<String>,
    pub last_cycle_duration_secs: Option<u64>,
    pub goal_failure_counts: HashMap<String, u32>,
    /// Fix-3 no-progress breaker counters. `#[serde(default)]` so snapshots
    /// written before this field existed still deserialize (empty tracker).
    #[serde(default)]
    pub no_progress_tracker: crate::goal_curation::NoProgressTracker,
}

impl From<&OodaState> for OodaStateSnapshot {
    fn from(state: &OodaState) -> Self {
        Self {
            current_phase: state.current_phase,
            active_goals: state.active_goals.clone(),
            cycle_count: state.cycle_count,
            last_observation: state.last_observation.clone(),
            review_improvements: state.review_improvements.clone(),
            prepared_context: state.prepared_context.clone(),
            cycle_start_epoch: state.cycle_start_epoch,
            last_cycle_summary: state.last_cycle_summary.clone(),
            last_cycle_duration_secs: state.last_cycle_duration_secs,
            goal_failure_counts: state.goal_failure_counts.clone(),
            no_progress_tracker: state.no_progress_tracker.clone(),
        }
    }
}

impl OodaStateSnapshot {
    /// Restore the round-tripped fields onto an existing [`OodaState`],
    /// preserving the in-process `engineer_worktrees`.
    pub fn apply_to(self, state: &mut OodaState) {
        state.current_phase = self.current_phase;
        state.active_goals = self.active_goals;
        state.cycle_count = self.cycle_count;
        state.last_observation = self.last_observation;
        state.review_improvements = self.review_improvements;
        state.prepared_context = self.prepared_context;
        state.cycle_start_epoch = self.cycle_start_epoch;
        state.last_cycle_summary = self.last_cycle_summary;
        state.last_cycle_duration_secs = self.last_cycle_duration_secs;
        state.goal_failure_counts = self.goal_failure_counts;
        state.no_progress_tracker = self.no_progress_tracker;
    }

    /// Construct a fresh [`OodaState`] from this snapshot. Worktrees start
    /// empty — recipe steps that need them load from the per-goal worktree
    /// directory under `state_root` instead of in-process handles.
    pub fn into_state(self) -> OodaState {
        let mut state = OodaState::new(self.active_goals.clone());
        self.apply_to(&mut state);
        state
    }
}

/// Mints fresh, independent LLM sessions for concurrent `AdvanceGoal`
/// dispatch.
///
/// The slow goal-action `run_turn` call (~30-90s) used to serialize on the
/// single shared [`OodaClients::session`], so only ~1 engineer started per
/// OODA round even when coverage planned many. A factory lets the Act phase
/// mint one session per spawn-candidate goal so those `run_turn` calls run
/// concurrently. `Send + Sync` so it can be shared across the dispatch
/// threads spawned by `dispatch_actions`.
pub trait OrchestratorSessionFactory: Send + Sync {
    /// Open a fresh orchestrator session for a single goal-advance turn.
    ///
    /// The caller owns the returned session and is responsible for closing
    /// it. Each call must return an independent session that can run a turn
    /// concurrently with sessions returned by other calls.
    fn open_session(
        &self,
    ) -> crate::error::SimardResult<Box<dyn crate::base_types::BaseTypeSession>>;
}

/// All bridges needed by the OODA loop.
pub struct OodaClients {
    pub memory: Box<dyn CognitiveMemoryOps>,
    pub knowledge: KnowledgeClient,
    pub gym: GymClient,
    /// Optional base-type session for real autonomous work (e.g. RustyClawd).
    /// When present, `AdvanceGoal` actions use `run_turn` to delegate work
    /// to an LLM agent instead of just bumping a progress percentage.
    pub session: Option<Box<dyn crate::base_types::BaseTypeSession>>,
    /// Prompt-driven decision brain (issue #1266). Today only the
    /// engineer-lifecycle skip branch consults it; future PRs migrate
    /// observe/orient/decide/curate/review.
    pub brain: std::sync::Arc<dyn crate::ooda_brain::OodaBrain>,
    /// Optional LLM-backed Decide brain (PR #1469). When `Some`, the
    /// cycle's Decide phase routes through it; otherwise it uses the
    /// `DeterministicDecideBrain` floor.
    pub decide_brain: Option<std::sync::Arc<dyn crate::ooda_brain::OodaDecideBrain>>,
    /// Optional LLM-backed Orient brain (PR #1471). When `Some`, the
    /// cycle's Orient phase routes through it; otherwise it uses the
    /// `DeterministicOrientBrain` floor.
    pub orient_brain: Option<std::sync::Arc<dyn crate::ooda_brain::OodaOrientBrain>>,
    /// Repository root used by engineer loops and review persistence.
    /// Defaults to `std::env::current_dir()` at daemon boot.
    pub repo_root: std::path::PathBuf,
    /// Gatekeeper for goal-progress increases (issue #1967). Production
    /// boot wires [`crate::goal_curation::progress_reviewer::LlmReviewerProgressChecker`];
    /// tests and `SIMARD_PROGRESS_EVIDENCE=off` wire
    /// [`crate::goal_curation::progress_evidence::NoopProgressEvidenceChecker`].
    pub progress_evidence:
        std::sync::Arc<dyn crate::goal_curation::progress_evidence::ProgressEvidenceChecker>,
    /// Deploy-aware done-gate for the curate phase (issue #2419). When `Some`,
    /// completed goals are archived only with hard evidence (merged PR, closed
    /// issue, and — for self-affecting changes — a verified deploy); blocked
    /// goals stay active with a recorded blocker. Production boot wires
    /// [`crate::goal_curation::GhCliEvidenceSource`] unless
    /// `SIMARD_COMPLETION_EVIDENCE=off`; tests and non-daemon callers leave it
    /// `None`, preserving the legacy unguarded
    /// [`archive_completed`](crate::goal_curation::archive_completed).
    pub completion_evidence:
        Option<std::sync::Arc<dyn crate::goal_curation::completion_gate::EvidenceSource>>,
    /// Optional factory that mints a fresh, independent LLM session per
    /// concurrent `AdvanceGoal` dispatch.
    ///
    /// When `Some`, the Act phase opens one session per spawn-candidate goal
    /// so their slow goal-action `run_turn` calls run concurrently instead of
    /// serializing on the single shared [`Self::session`]. When `None`,
    /// concurrent dispatch falls back to the shared [`Self::session`] under a
    /// lock (serialized) — preserving today's behavior for tests and
    /// non-daemon callers. Bounded by the AIMD `cap` (`scaler.current_max()`)
    /// so concurrency stays resource-aware.
    pub session_factory: Option<std::sync::Arc<dyn OrchestratorSessionFactory>>,
    /// Optional structured-reasoning brain for closed-loop live outcome
    /// verification (issue #2751). When `Some` (paired with [`Self::live_signals`]),
    /// a completion-candidate goal is verified LIVE at the curate seam before it
    /// can archive — the goal is "achieved" only once a verified live signal
    /// corroborates its real success criteria, not merely because a PR landed.
    /// When `None` the legacy curate path is unchanged. Production boot wires
    /// the recipe brain unless `SIMARD_OUTCOME_VERIFY=off`; tests inject a stub.
    pub outcome_verify_brain: Option<std::sync::Arc<dyn crate::ooda_brain::OodaBrain>>,
    /// Optional live-signal source paired with [`Self::outcome_verify_brain`].
    /// Composes the thin adapters over telemetry / journald / deploy-reconcile
    /// state the daemon already emits; tests inject a hermetic double. `None`
    /// leaves the legacy curate path in place (both fields must be `Some` for
    /// verification to run).
    pub live_signals:
        Option<std::sync::Arc<dyn crate::goal_curation::live_signal::LiveSignalSource>>,
}

// ---------------------------------------------------------------------------
// Issue #2182: OodaConfig env-var scaler wiring tests
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests_ooda_config {
    use super::*;
    use std::sync::Mutex;

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_creates_scaler_when_scaling_auto() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::set_var("SIMARD_SCALING", "auto") };
        let config = OodaConfig::default();
        unsafe { std::env::remove_var("SIMARD_SCALING") };
        assert!(
            config.scaler.is_some(),
            "SIMARD_SCALING=auto must populate config.scaler"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_no_scaler_when_scaling_fixed() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::set_var("SIMARD_SCALING", "fixed") };
        let config = OodaConfig::default();
        unsafe { std::env::remove_var("SIMARD_SCALING") };
        assert!(
            config.scaler.is_none(),
            "SIMARD_SCALING=fixed must leave config.scaler as None"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_no_scaler_when_scaling_unset() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::remove_var("SIMARD_SCALING") };
        let config = OodaConfig::default();
        assert!(
            config.scaler.is_none(),
            "no SIMARD_SCALING env must leave config.scaler as None"
        );
    }

    // Issue #2327 (RED): the automatic promotion scheduler is configured via
    // two new OodaConfig fields. With the env overrides unset, they default to
    // the canonical 25-episode threshold and 50-cycle interval.
    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_default_distill_thresholds() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::remove_var("SIMARD_DISTILL_MIN_EPISODES") };
        unsafe { std::env::remove_var("SIMARD_DISTILL_INTERVAL_CYCLES") };
        let config = OodaConfig::default();
        assert_eq!(
            config.distill_min_episodes, 25,
            "default distill threshold must be 25 episodes"
        );
        assert_eq!(
            config.distill_interval_cycles, 50,
            "default distill interval must be 50 cycles"
        );
    }

    // Issues #2441/#2458: the lesson recurrence threshold defaults to 2 (the
    // smallest value that excludes one-off failures) with its env override unset.
    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_default_lesson_recurrence_threshold() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::remove_var("SIMARD_LESSON_RECURRENCE_THRESHOLD") };
        let config = OodaConfig::default();
        assert_eq!(
            config.lesson_recurrence_threshold, 2,
            "default lesson recurrence threshold must be 2"
        );
    }

    // Issue #2935: the AIMD ceiling is now the *configured max* itself (was
    // `4 × max`). This makes the configured value a TRUE per-cycle ceiling —
    // e.g. 24 means at most 24, not 96 — while the scaler still backs off on
    // pressure and recovers back up to the ceiling. The scaler therefore also
    // starts AT the configured max, so the per-cycle cap reaches it immediately.
    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_auto_scaler_ceiling_equals_configured_max() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_SCALING", "auto") };
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "8") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        let scaler = config.scaler.expect("scaler must be Some under auto");
        assert_eq!(
            scaler.ceiling(),
            8,
            "AIMD ceiling must equal the configured max (issue #2935), not a 4x multiple"
        );
        assert_eq!(
            config.max_concurrent_actions, 8,
            "SIMARD_OODA_MAX_CONCURRENT must seed max_concurrent_actions"
        );
        assert_eq!(
            scaler.current_max(),
            8,
            "the scaler starts at the configured max so the per-cycle cap reaches it immediately"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_auto_scaler_adjust_returns_within_bounds() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::set_var("SIMARD_SCALING", "auto") };
        unsafe { std::env::set_var("SIMARD_MAX_CONCURRENT_ACTIONS", "5") };
        let config = OodaConfig::default();
        unsafe { std::env::remove_var("SIMARD_SCALING") };
        unsafe { std::env::remove_var("SIMARD_MAX_CONCURRENT_ACTIONS") };
        let scaler = config.scaler.expect("scaler must be Some");
        let val = scaler.adjust();
        assert!(
            val >= scaler.floor() && val <= scaler.ceiling(),
            "adjust()={val} must be in [{}, {}]",
            scaler.floor(),
            scaler.ceiling()
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn ooda_config_scaler_skipped_on_serde_roundtrip() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        unsafe { std::env::set_var("SIMARD_SCALING", "auto") };
        let config = OodaConfig::default();
        unsafe { std::env::remove_var("SIMARD_SCALING") };
        assert!(config.scaler.is_some(), "precondition: scaler must be Some");

        let json = serde_json::to_string(&config).expect("serialize");
        let deserialized: OodaConfig = serde_json::from_str(&json).expect("deserialize");
        assert!(
            deserialized.scaler.is_none(),
            "scaler must be None after serde round-trip (#[serde(skip)])"
        );
    }

    // -----------------------------------------------------------------------
    // Issue #2935: SIMARD_OODA_MAX_CONCURRENT parsing, precedence, and
    // fail-closed validation. The per-OODA-cycle goal-coverage parallelism
    // ceiling is raised from the arbitrary 5 to 24 and made env-configurable.
    //
    // All assertions go through the public `OodaConfig::default()` contract
    // (not the private parser) so the crate keeps compiling in the red phase
    // and the tests exercise the real end-to-end wiring.
    // -----------------------------------------------------------------------

    /// Remove every env var that influences the per-cycle concurrency ceiling so
    /// each test starts from a known-clean baseline (order-independent, no leakage).
    fn clear_concurrency_env() {
        unsafe { std::env::remove_var("SIMARD_OODA_MAX_CONCURRENT") };
        unsafe { std::env::remove_var("SIMARD_MAX_CONCURRENT_ACTIONS") };
        unsafe { std::env::remove_var("SIMARD_SCALING") };
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn max_concurrent_defaults_to_24_when_unset() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        let config = OodaConfig::default();
        assert_eq!(
            config.max_concurrent_actions, 24,
            "with no override, the per-cycle concurrency default must be 24 (issue #2935)"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn simard_ooda_max_concurrent_overrides_default() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "30") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 30,
            "a valid SIMARD_OODA_MAX_CONCURRENT must override the default"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn legacy_simard_max_concurrent_actions_still_honored() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_MAX_CONCURRENT_ACTIONS", "10") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 10,
            "the legacy var remains functional when the new var is unset (additive change)"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn new_var_takes_precedence_over_legacy_var() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "30") };
        unsafe { std::env::set_var("SIMARD_MAX_CONCURRENT_ACTIONS", "10") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 30,
            "SIMARD_OODA_MAX_CONCURRENT must take precedence over the legacy var"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn non_numeric_override_fails_closed_to_default_24() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "not-a-number") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 24,
            "a non-numeric override must fail closed to the default 24 (and log a warning)"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn invalid_preferred_var_does_not_fall_through_to_legacy() {
        // Documented fail-closed-INDEPENDENT contract (issue #2935): when the
        // preferred var is PRESENT but invalid, resolution fails closed to the
        // default 24 and must NOT resurrect an otherwise-valid legacy value — a
        // typo in SIMARD_OODA_MAX_CONCURRENT should not silently apply stale
        // SIMARD_MAX_CONCURRENT_ACTIONS config.
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "not-a-number") };
        unsafe { std::env::set_var("SIMARD_MAX_CONCURRENT_ACTIONS", "10") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 24,
            "an invalid PRESENT preferred var must fail closed to 24, not fall through to the legacy 10"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn zero_override_is_rejected_and_fails_closed_to_24() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "0") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 24,
            "0 is below the minimum of 1; fail closed to 24 (a zero cap would stall the daemon)"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn over_max_override_is_rejected_and_fails_closed_to_24() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "9999") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            config.max_concurrent_actions, 24,
            "a value above the sane maximum (64) must fail closed to 24"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn boundary_values_1_and_64_are_accepted() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "1") };
        let low = OodaConfig::default();
        assert_eq!(
            low.max_concurrent_actions, 1,
            "the minimum boundary (1) must be accepted"
        );
        unsafe { std::env::set_var("SIMARD_OODA_MAX_CONCURRENT", "64") };
        let high = OodaConfig::default();
        clear_concurrency_env();
        assert_eq!(
            high.max_concurrent_actions, 64,
            "the maximum boundary (64) must be accepted"
        );
    }

    // ── The per-cycle coverage cap actually reaches 24 (cycle.rs:316) ───────

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn default_coverage_cap_reaches_24_under_auto_scaling() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env();
        unsafe { std::env::set_var("SIMARD_SCALING", "auto") };
        let config = OodaConfig::default();
        clear_concurrency_env();
        // Mirror the per-cycle coverage-cap derivation in cycle.rs (issue #2935
        // target site): the AIMD scaler's current_max, else max_concurrent_actions.
        let cap = config
            .scaler
            .as_ref()
            .map(|s| s.current_max() as usize)
            .unwrap_or(config.max_concurrent_actions as usize);
        assert_eq!(
            cap, 24,
            "with the raised ceiling, the AIMD per-cycle coverage cap must reach 24"
        );
    }

    #[serial_test::serial(cognitive_memory)]
    #[test]
    fn default_coverage_cap_reaches_24_under_fixed_scaling() {
        let _lock = ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        clear_concurrency_env(); // SIMARD_SCALING unset ⇒ scaler is None
        let config = OodaConfig::default();
        let cap = config
            .scaler
            .as_ref()
            .map(|s| s.current_max() as usize)
            .unwrap_or(config.max_concurrent_actions as usize);
        assert_eq!(
            cap, 24,
            "with fixed scaling the cap is max_concurrent_actions, which now defaults to 24"
        );
    }
}
