//! Shared types for the OODA loop.

use std::collections::HashMap;
use std::fmt::{self, Display, Formatter};

use crate::cognitive_memory::CognitiveMemoryOps;
use crate::engineer_worktree::EngineerWorktree;
use crate::goal_curation::{ActiveGoal, GoalBoard, GoalProgress};
use crate::gym_bridge::GymBridge;
use crate::gym_scoring::GymSuiteScore;
use crate::knowledge_bridge::KnowledgeBridge;
use crate::memory_cognitive::CognitiveStatistics;
use crate::memory_consolidation::PreparedContext;
use crate::self_improve::ImprovementCycle;

/// The four phases of a single OODA cycle, plus Sleep between cycles.
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum OodaPhase {
    Observe,
    Orient,
    Decide,
    Act,
    Sleep,
}

impl Display for OodaPhase {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Observe => f.write_str("observe"),
            Self::Orient => f.write_str("orient"),
            Self::Decide => f.write_str("decide"),
            Self::Act => f.write_str("act"),
            Self::Sleep => f.write_str("sleep"),
        }
    }
}

/// Mutable state carried across OODA cycles.
pub struct OodaState {
    pub current_phase: OodaPhase,
    pub active_goals: GoalBoard,
    pub cycle_count: u32,
    pub last_observation: Option<Observation>,
    /// Improvement proposals generated by post-act review, drained by observe().
    pub review_improvements: Vec<ImprovementCycle>,
    /// Context gathered from cognitive memory during the preparation sub-phase.
    /// Populated each cycle so the Act phase can use recalled facts, triggered
    /// prospectives, and relevant procedures when advancing goals.
    pub prepared_context: Option<PreparedContext>,
    /// Unix epoch (seconds) when the current cycle started.
    pub cycle_start_epoch: u64,
    /// Human-readable summary from the last completed cycle.
    pub last_cycle_summary: Option<String>,
    /// Duration in seconds of the last completed cycle.
    pub last_cycle_duration_secs: Option<u64>,
    /// Per-goal consecutive-failure count. Incremented after each Act phase
    /// when an outcome with `goal_id == Some(g)` has `success == false`,
    /// reset to 0 on success. Used by Orient to demote chronically failing
    /// goals so the daemon stops burning budget on the same broken target.
    pub goal_failure_counts: HashMap<String, u32>,
    /// Per-goal isolated git worktrees owned by spawned engineers (issue #1197).
    /// Keyed by `goal_id`; cleaned up by the reaper path when the engineer's
    /// outcome is validated, or via `EngineerWorktree::Drop` if the entry is
    /// removed before explicit `cleanup()` runs.
    pub engineer_worktrees: HashMap<String, EngineerWorktree>,
}

impl OodaState {
    pub fn new(goals: GoalBoard) -> Self {
        Self {
            current_phase: OodaPhase::Observe,
            active_goals: goals,
            cycle_count: 0,
            last_observation: None,
            review_improvements: Vec::new(),
            prepared_context: None,
            cycle_start_epoch: 0,
            last_cycle_summary: None,
            last_cycle_duration_secs: None,
            goal_failure_counts: HashMap::new(),
            engineer_worktrees: HashMap::new(),
        }
    }
}

/// A single goal's status snapshot for observation.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct GoalSnapshot {
    pub id: String,
    pub description: String,
    pub progress: GoalProgress,
}

impl From<&ActiveGoal> for GoalSnapshot {
    fn from(g: &ActiveGoal) -> Self {
        Self {
            id: g.id.clone(),
            description: g.description.clone(),
            progress: g.status.clone(),
        }
    }
}

/// Snapshot of the local environment: git state, issues, recent commits.
#[derive(Clone, Debug, Default, serde::Serialize, serde::Deserialize)]
pub struct EnvironmentSnapshot {
    /// Output of `git status --porcelain` (empty string if unavailable).
    pub git_status: String,
    /// Open issue titles from `gh issue list` (empty if unavailable).
    pub open_issues: Vec<String>,
    /// Recent commit one-liners from `git log --oneline -10`.
    pub recent_commits: Vec<String>,
}

/// Everything gathered during the Observe phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Observation {
    pub goal_statuses: Vec<GoalSnapshot>,
    pub gym_health: Option<GymSuiteScore>,
    pub memory_stats: CognitiveStatistics,
    pub pending_improvements: Vec<ImprovementCycle>,
    /// Local environment state for goal assessment.
    pub environment: EnvironmentSnapshot,
    /// Set when the eval watchdog has detected a dead signal — i.e. the
    /// gym progressive suite has been silently producing zeros (or
    /// pixel-identical scores) across multiple distinct scenarios for
    /// long enough that the OODA loop must NOT trust further eval-derived
    /// decisions until an operator investigates.
    ///
    /// Reason text is logged at ERROR level by observe(); orient pushes
    /// a `__eval_watchdog__` priority with maximum urgency so the loop
    /// surfaces the failure instead of marching past it.
    pub eval_watchdog: Option<String>,
}

/// A ranked priority produced during the Orient phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Priority {
    pub goal_id: String,
    pub urgency: f64,
    pub reason: String,
}

/// The kind of action the OODA loop can dispatch.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ActionKind {
    AdvanceGoal,
    RunImprovement,
    ConsolidateMemory,
    ResearchQuery,
    RunGymEval,
    BuildSkill,
    LaunchSession,
    PollDeveloperActivity,
    ExtractIdeas,
}

impl Display for ActionKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::AdvanceGoal => f.write_str("advance-goal"),
            Self::RunImprovement => f.write_str("run-improvement"),
            Self::ConsolidateMemory => f.write_str("consolidate-memory"),
            Self::ResearchQuery => f.write_str("research-query"),
            Self::RunGymEval => f.write_str("run-gym-eval"),
            Self::BuildSkill => f.write_str("build-skill"),
            Self::LaunchSession => f.write_str("launch-session"),
            Self::PollDeveloperActivity => f.write_str("poll-developer-activity"),
            Self::ExtractIdeas => f.write_str("extract-ideas"),
        }
    }
}

/// A planned action selected during the Decide phase.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct PlannedAction {
    pub kind: ActionKind,
    pub goal_id: Option<String>,
    pub description: String,
}

/// Outcome of dispatching a single action.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ActionOutcome {
    pub action: PlannedAction,
    pub success: bool,
    pub detail: String,
}

/// Report for one complete OODA cycle.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct CycleReport {
    pub cycle_number: u32,
    pub observation: Observation,
    pub priorities: Vec<Priority>,
    pub planned_actions: Vec<PlannedAction>,
    pub outcomes: Vec<ActionOutcome>,
}

/// Configuration for the OODA loop.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct OodaConfig {
    pub max_concurrent_actions: u32,
    pub improvement_threshold: f64,
    pub gym_suite_id: String,
    /// Daily budget in USD (from SIMARD_DAILY_BUDGET_USD env or dashboard).
    pub daily_budget_usd: f64,
    /// Weekly budget in USD (from SIMARD_WEEKLY_BUDGET_USD env or dashboard).
    pub weekly_budget_usd: f64,
}

impl Default for OodaConfig {
    fn default() -> Self {
        Self {
            max_concurrent_actions: 3,
            improvement_threshold: 0.02,
            gym_suite_id: "progressive".to_string(),
            daily_budget_usd: env_f64("SIMARD_DAILY_BUDGET_USD", 500.0),
            weekly_budget_usd: env_f64("SIMARD_WEEKLY_BUDGET_USD", 2500.0),
        }
    }
}

fn env_f64(key: &str, default: f64) -> f64 {
    std::env::var(key)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

/// Serializable view of [`OodaState`] suitable for round-tripping through
/// recipe steps via JSON. Excludes:
/// - `engineer_worktrees` — OS handles owning git worktrees; recipe steps
///   re-key these by `goal_id` from the parent process state.
/// - The `OodaBridges` (memory store, gym, knowledge) — instantiated per
///   helper-bin invocation from the configured `state_root`.
///
/// Use `OodaStateSnapshot::from(&state)` to capture, and
/// `snapshot.apply_to(&mut state)` to restore the round-tripped fields.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct OodaStateSnapshot {
    pub current_phase: OodaPhase,
    pub active_goals: GoalBoard,
    pub cycle_count: u32,
    pub last_observation: Option<Observation>,
    pub review_improvements: Vec<ImprovementCycle>,
    pub prepared_context: Option<PreparedContext>,
    pub cycle_start_epoch: u64,
    pub last_cycle_summary: Option<String>,
    pub last_cycle_duration_secs: Option<u64>,
    pub goal_failure_counts: HashMap<String, u32>,
}

impl From<&OodaState> for OodaStateSnapshot {
    fn from(state: &OodaState) -> Self {
        Self {
            current_phase: state.current_phase,
            active_goals: state.active_goals.clone(),
            cycle_count: state.cycle_count,
            last_observation: state.last_observation.clone(),
            review_improvements: state.review_improvements.clone(),
            prepared_context: state.prepared_context.clone(),
            cycle_start_epoch: state.cycle_start_epoch,
            last_cycle_summary: state.last_cycle_summary.clone(),
            last_cycle_duration_secs: state.last_cycle_duration_secs,
            goal_failure_counts: state.goal_failure_counts.clone(),
        }
    }
}

impl OodaStateSnapshot {
    /// Restore the round-tripped fields onto an existing [`OodaState`],
    /// preserving the in-process `engineer_worktrees`.
    pub fn apply_to(self, state: &mut OodaState) {
        state.current_phase = self.current_phase;
        state.active_goals = self.active_goals;
        state.cycle_count = self.cycle_count;
        state.last_observation = self.last_observation;
        state.review_improvements = self.review_improvements;
        state.prepared_context = self.prepared_context;
        state.cycle_start_epoch = self.cycle_start_epoch;
        state.last_cycle_summary = self.last_cycle_summary;
        state.last_cycle_duration_secs = self.last_cycle_duration_secs;
        state.goal_failure_counts = self.goal_failure_counts;
    }

    /// Construct a fresh [`OodaState`] from this snapshot. Worktrees start
    /// empty — recipe steps that need them load from the per-goal worktree
    /// directory under `state_root` instead of in-process handles.
    pub fn into_state(self) -> OodaState {
        let mut state = OodaState::new(self.active_goals.clone());
        self.apply_to(&mut state);
        state
    }
}

/// All bridges needed by the OODA loop.
pub struct OodaBridges {
    pub memory: Box<dyn CognitiveMemoryOps>,
    pub knowledge: KnowledgeBridge,
    pub gym: GymBridge,
    /// Optional base-type session for real autonomous work (e.g. RustyClawd).
    /// When present, `AdvanceGoal` actions use `run_turn` to delegate work
    /// to an LLM agent instead of just bumping a progress percentage.
    pub session: Option<Box<dyn crate::base_types::BaseTypeSession>>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::goal_curation::{ActiveGoal, GoalBoard, GoalProgress};

    // --- OodaPhase Display ---

    #[test]
    fn ooda_phase_display_all_variants() {
        assert_eq!(OodaPhase::Observe.to_string(), "observe");
        assert_eq!(OodaPhase::Orient.to_string(), "orient");
        assert_eq!(OodaPhase::Decide.to_string(), "decide");
        assert_eq!(OodaPhase::Act.to_string(), "act");
        assert_eq!(OodaPhase::Sleep.to_string(), "sleep");
    }

    #[test]
    fn ooda_phase_equality() {
        assert_eq!(OodaPhase::Observe, OodaPhase::Observe);
        assert_ne!(OodaPhase::Observe, OodaPhase::Orient);
    }

    #[test]
    fn ooda_phase_clone() {
        let phase = OodaPhase::Decide;
        let cloned = phase;
        assert_eq!(phase, cloned);
    }

    // --- OodaState ---

    #[test]
    fn ooda_state_new_defaults() {
        let state = OodaState::new(GoalBoard::new());
        assert_eq!(state.current_phase, OodaPhase::Observe);
        assert_eq!(state.cycle_count, 0);
        assert!(state.last_observation.is_none());
        assert!(state.review_improvements.is_empty());
        assert!(state.active_goals.active.is_empty());
        assert!(state.prepared_context.is_none());
        assert_eq!(state.cycle_start_epoch, 0);
        assert!(state.last_cycle_summary.is_none());
        assert!(state.last_cycle_duration_secs.is_none());
    }

    #[test]
    fn ooda_state_new_with_goals() {
        let mut board = GoalBoard::new();
        board.active.push(ActiveGoal {
            id: "goal-1".to_string(),
            description: "Test goal".to_string(),
            priority: 1,
            status: GoalProgress::NotStarted,
            assigned_to: None,
            current_activity: None,
            wip_refs: vec![],
        });
        let state = OodaState::new(board);
        assert_eq!(state.active_goals.active.len(), 1);
    }

    // --- OodaStateSnapshot round-trip ---

    fn populated_state() -> OodaState {
        let mut board = GoalBoard::new();
        board.active.push(ActiveGoal {
            id: "goal-snap".to_string(),
            description: "Snapshot test".to_string(),
            priority: 3,
            status: GoalProgress::InProgress { percent: 25 },
            assigned_to: Some("engineer-7".to_string()),
            current_activity: Some("doing things".to_string()),
            wip_refs: vec![],
        });
        let mut state = OodaState::new(board);
        state.current_phase = OodaPhase::Decide;
        state.cycle_count = 7;
        state.cycle_start_epoch = 1_700_000_000;
        state.last_cycle_summary = Some("prior summary".to_string());
        state.last_cycle_duration_secs = Some(42);
        state
            .goal_failure_counts
            .insert("goal-snap".to_string(), 2);
        state
    }

    #[test]
    fn snapshot_captures_serializable_fields() {
        let state = populated_state();
        let snap = OodaStateSnapshot::from(&state);
        assert_eq!(snap.current_phase, OodaPhase::Decide);
        assert_eq!(snap.cycle_count, 7);
        assert_eq!(snap.cycle_start_epoch, 1_700_000_000);
        assert_eq!(snap.last_cycle_summary.as_deref(), Some("prior summary"));
        assert_eq!(snap.last_cycle_duration_secs, Some(42));
        assert_eq!(snap.goal_failure_counts.get("goal-snap"), Some(&2));
        assert_eq!(snap.active_goals.active.len(), 1);
        assert_eq!(snap.active_goals.active[0].id, "goal-snap");
    }

    #[test]
    fn snapshot_json_roundtrip_preserves_state() {
        let state = populated_state();
        let snap = OodaStateSnapshot::from(&state);
        let json = serde_json::to_string(&snap).expect("serialize snapshot");
        let parsed: OodaStateSnapshot =
            serde_json::from_str(&json).expect("deserialize snapshot");

        let mut restored = OodaState::new(GoalBoard::new());
        parsed.apply_to(&mut restored);

        assert_eq!(restored.current_phase, state.current_phase);
        assert_eq!(restored.cycle_count, state.cycle_count);
        assert_eq!(restored.cycle_start_epoch, state.cycle_start_epoch);
        assert_eq!(restored.last_cycle_summary, state.last_cycle_summary);
        assert_eq!(
            restored.last_cycle_duration_secs,
            state.last_cycle_duration_secs
        );
        assert_eq!(
            restored.goal_failure_counts.get("goal-snap"),
            state.goal_failure_counts.get("goal-snap")
        );
        assert_eq!(
            restored.active_goals.active.len(),
            state.active_goals.active.len()
        );
        assert_eq!(
            restored.active_goals.active[0].id,
            state.active_goals.active[0].id
        );
    }

    #[test]
    fn snapshot_apply_preserves_in_process_worktrees() {
        // worktrees are NOT round-tripped — applying a snapshot must not
        // touch them. Verify by leaving HashMap untouched after apply.
        let mut state = OodaState::new(GoalBoard::new());
        // We can't easily construct EngineerWorktree in tests (it owns a
        // real git path), so just assert the field stays an empty map
        // after a no-op snapshot apply.
        assert!(state.engineer_worktrees.is_empty());
        let snap = OodaStateSnapshot::from(&state);
        snap.apply_to(&mut state);
        assert!(
            state.engineer_worktrees.is_empty(),
            "apply_to must not clobber engineer_worktrees"
        );
    }

    #[test]
    fn snapshot_into_state_constructs_fresh_state() {
        let original = populated_state();
        let snap = OodaStateSnapshot::from(&original);
        let restored = snap.into_state();
        assert_eq!(restored.cycle_count, original.cycle_count);
        assert_eq!(restored.current_phase, original.current_phase);
        assert!(restored.engineer_worktrees.is_empty());
    }

    // --- GoalSnapshot ---

    #[test]
    fn goal_snapshot_from_active_goal() {
        let goal = ActiveGoal {
            id: "g-1".to_string(),
            description: "Build widget".to_string(),
            priority: 2,
            status: GoalProgress::InProgress { percent: 50 },
            assigned_to: Some("engineer".to_string()),
            current_activity: None,
            wip_refs: vec![],
        };
        let snapshot = GoalSnapshot::from(&goal);
        assert_eq!(snapshot.id, "g-1");
        assert_eq!(snapshot.description, "Build widget");
        assert!(matches!(
            snapshot.progress,
            GoalProgress::InProgress { percent: 50 }
        ));
    }

    #[test]
    fn goal_snapshot_from_blocked_goal() {
        let goal = ActiveGoal {
            id: "g-blocked".to_string(),
            description: "Blocked task".to_string(),
            priority: 1,
            status: GoalProgress::Blocked("dependency missing".to_string()),
            assigned_to: None,
            current_activity: None,
            wip_refs: vec![],
        };
        let snapshot = GoalSnapshot::from(&goal);
        assert!(matches!(snapshot.progress, GoalProgress::Blocked(_)));
    }

    // --- EnvironmentSnapshot ---

    #[test]
    fn environment_snapshot_default() {
        let env = EnvironmentSnapshot::default();
        assert!(env.git_status.is_empty());
        assert!(env.open_issues.is_empty());
        assert!(env.recent_commits.is_empty());
    }

    // --- ActionKind Display ---

    #[test]
    fn action_kind_display_all_variants() {
        assert_eq!(ActionKind::AdvanceGoal.to_string(), "advance-goal");
        assert_eq!(ActionKind::RunImprovement.to_string(), "run-improvement");
        assert_eq!(
            ActionKind::ConsolidateMemory.to_string(),
            "consolidate-memory"
        );
        assert_eq!(ActionKind::ResearchQuery.to_string(), "research-query");
        assert_eq!(ActionKind::RunGymEval.to_string(), "run-gym-eval");
        assert_eq!(ActionKind::BuildSkill.to_string(), "build-skill");
        assert_eq!(ActionKind::LaunchSession.to_string(), "launch-session");
    }

    #[test]
    fn action_kind_equality() {
        assert_eq!(ActionKind::AdvanceGoal, ActionKind::AdvanceGoal);
        assert_ne!(ActionKind::AdvanceGoal, ActionKind::RunImprovement);
    }

    // --- OodaConfig ---

    #[test]
    fn ooda_config_default_values() {
        let config = OodaConfig::default();
        assert_eq!(config.max_concurrent_actions, 3);
        assert!((config.improvement_threshold - 0.02).abs() < f64::EPSILON);
        assert_eq!(config.gym_suite_id, "progressive");
    }

    // --- Observation / PlannedAction / CycleReport: struct construction ---

    #[test]
    fn planned_action_construction() {
        let action = PlannedAction {
            kind: ActionKind::BuildSkill,
            goal_id: Some("skill-1".to_string()),
            description: "Build skill".to_string(),
        };
        assert_eq!(action.kind, ActionKind::BuildSkill);
        assert_eq!(action.goal_id.unwrap(), "skill-1");
    }

    #[test]
    fn action_outcome_construction() {
        let outcome = ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::LaunchSession,
                goal_id: None,
                description: "launch".to_string(),
            },
            success: true,
            detail: "session launched".to_string(),
        };
        assert!(outcome.success);
        assert_eq!(outcome.detail, "session launched");
    }
}
