//! Recipe-runner-backed disk health check (issue #2020, fix #2212).
//!
//! Two-tier approach:
//!   1. **Deterministic emergency cleanup** — pure Rust, no LLM, runs when disk
//!      is critically full (≥95%). Deletes known-safe build artifacts immediately.
//!   2. **Recipe-based cleanup** — LLM agent for intelligent cleanup when disk
//!      is moderately full (≥80%). Can make nuanced decisions.
//!
//! The emergency tier exists because the recipe tier needs disk space to spawn
//! an agent process. At 100% disk, the recipe deadlocks.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;
use tracing::{info, warn};

use crate::error::{SimardError, SimardResult};
use crate::runtime_config::RuntimeConfig;

const ADAPTER_TAG: &str = "disk-health-check";
const RECIPE_FILENAME: &str = "disk-health-check.yaml";

/// JSON envelope returned by `recipe-runner-rs --output-format json`.
#[derive(Debug, Deserialize)]
pub(crate) struct RecipeOutput {
    pub success: bool,
    pub step_results: Vec<StepResult>,
}

/// A single step's result inside the [`RecipeOutput`] envelope.
#[derive(Debug, Deserialize)]
pub(crate) struct StepResult {
    #[allow(dead_code)] // Part of JSON contract; used in tests.
    pub step_id: String,
    pub output: String,
}

/// Structured report returned by the disk-health-check recipe.
///
/// Built by parsing text markers (`DISK_USED_PCT=`, `FREED_BYTES=`,
/// `ACTION:`) from the agent step output extracted from the JSON envelope.
#[derive(Debug, Clone, PartialEq)]
pub struct DiskHealthReport {
    /// Current disk usage percentage (0–100).
    pub disk_used_pct: u8,
    /// Total bytes freed during this check (0 if no cleanup needed).
    pub freed_bytes: u64,
    /// Human-readable list of cleanup actions taken.
    pub actions_taken: Vec<String>,
}

impl DiskHealthReport {
    /// Whether cleanup was actually performed (usage was above threshold).
    pub fn cleanup_performed(&self) -> bool {
        self.freed_bytes > 0 || !self.actions_taken.is_empty()
    }

    /// One-line summary suitable for daemon log.
    pub fn summary(&self) -> String {
        if self.cleanup_performed() {
            format!(
                "disk health: {}% used, freed {} bytes, {} actions",
                self.disk_used_pct,
                self.freed_bytes,
                self.actions_taken.len()
            )
        } else {
            format!(
                "disk health: {}% used, no cleanup needed",
                self.disk_used_pct
            )
        }
    }
}

/// Resolve the recipe YAML path. Checks, in order:
///   1. `~/.simard/prompt_assets/simard/recipes/<name>` (hot-reload path)
///   2. `<repo_root>/prompt_assets/simard/recipes/<name>` (in-tree)
fn resolve_recipe_path(repo_root: &Path) -> Option<PathBuf> {
    if let Some(home) = dirs::home_dir() {
        let hot = home
            .join(".simard")
            .join("prompt_assets/simard/recipes")
            .join(RECIPE_FILENAME);
        if hot.is_file() {
            return Some(hot);
        }
    }
    let in_tree = repo_root
        .join("prompt_assets/simard/recipes")
        .join(RECIPE_FILENAME);
    if in_tree.is_file() {
        return Some(in_tree);
    }
    None
}

/// Deterministic emergency disk cleanup — no LLM, no recipe, just rm.
///
/// Runs when disk usage is critically high (≥95%). Deletes known-safe build
/// artifacts that can always be regenerated by `cargo build`:
///   - `repo_root/target/debug/` (main build cache)
///   - `repo_root/worktrees/*/target/` (engineer worktree build caches)
///   - `repo_root/target/llvm-cov-target/` (coverage artifacts)
///   - `state_root/cargo-target/` and `state_root/shared-target/`
///   - stale backups beyond the 2 most recent
///
/// Returns a report of what was done, or None if disk is below threshold.
pub fn emergency_cleanup(repo_root: &Path, state_root: &Path) -> Option<DiskHealthReport> {
    let pct = get_disk_usage_pct(repo_root)?;

    if pct < 95 {
        return None;
    }

    warn!(disk_pct = pct, "Emergency disk cleanup triggered (≥95%)");
    let mut freed: u64 = 0;
    let mut actions: Vec<String> = Vec::new();

    // 1. Main target/debug/ — the single biggest consumer
    let debug_dir = repo_root.join("target/debug");
    if debug_dir.is_dir() {
        let size = dir_size_bytes(&debug_dir);
        if std::fs::remove_dir_all(&debug_dir).is_ok() {
            freed += size;
            actions.push(format!("Removed target/debug/ ({} MB)", size / 1_000_000));
        }
    }

    // 2. target/llvm-cov-target/
    let cov_dir = repo_root.join("target/llvm-cov-target");
    if cov_dir.is_dir() {
        let size = dir_size_bytes(&cov_dir);
        if std::fs::remove_dir_all(&cov_dir).is_ok() {
            freed += size;
            actions.push(format!(
                "Removed target/llvm-cov-target/ ({} MB)",
                size / 1_000_000
            ));
        }
    }

    // 3. Engineer worktree target/ dirs
    let worktrees_dir = repo_root.join("worktrees");
    if worktrees_dir.is_dir()
        && let Ok(entries) = std::fs::read_dir(&worktrees_dir)
    {
        for entry in entries.flatten() {
            let target = entry.path().join("target");
            if target.is_dir() {
                let size = dir_size_bytes(&target);
                if std::fs::remove_dir_all(&target).is_ok() {
                    freed += size;
                    actions.push(format!(
                        "Removed worktrees/{}/target/ ({} MB)",
                        entry.file_name().to_string_lossy(),
                        size / 1_000_000
                    ));
                }
            }
        }
    }

    // 4. State root cargo dirs
    for name in &["cargo-target", "shared-target"] {
        let dir = state_root.join(name);
        if dir.is_dir() {
            let size = dir_size_bytes(&dir);
            if std::fs::remove_dir_all(&dir).is_ok() {
                freed += size;
                actions.push(format!("Removed {name}/ ({} MB)", size / 1_000_000));
            }
        }
    }

    // 5. Stale backups (keep 2 most recent)
    let backup_dir = state_root.join("backups");
    if backup_dir.is_dir()
        && let Ok(mut entries) = std::fs::read_dir(&backup_dir)
    {
        let mut files: Vec<_> = entries
            .by_ref()
            .flatten()
            .filter(|e| e.path().is_file())
            .collect();
        files.sort_by_key(|e| {
            std::cmp::Reverse(
                e.metadata()
                    .ok()
                    .and_then(|m| m.modified().ok())
                    .unwrap_or(std::time::SystemTime::UNIX_EPOCH),
            )
        });
        for old in files.into_iter().skip(2) {
            let size = old.metadata().map(|m| m.len()).unwrap_or(0);
            if std::fs::remove_file(old.path()).is_ok() {
                freed += size;
            }
        }
        if freed > 0 {
            actions.push("Pruned old backups (kept 2 most recent)".to_string());
        }
    }

    let final_pct = get_disk_usage_pct(repo_root).unwrap_or(pct);
    info!(
        freed_mb = freed / 1_000_000,
        before_pct = pct,
        after_pct = final_pct,
        "Emergency cleanup complete"
    );

    Some(DiskHealthReport {
        disk_used_pct: final_pct,
        freed_bytes: freed,
        actions_taken: actions,
    })
}

/// Get disk usage percentage for the filesystem containing `path`.
fn get_disk_usage_pct(path: &Path) -> Option<u8> {
    let output = Command::new("df")
        .arg("--output=pcent")
        .arg(path)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&output.stdout);
    text.lines()
        .nth(1)?
        .trim()
        .trim_end_matches('%')
        .parse::<u8>()
        .ok()
}

/// Estimate directory size in bytes (non-recursive stat, uses du).
fn dir_size_bytes(path: &Path) -> u64 {
    Command::new("du")
        .arg("-sb")
        .arg(path)
        .output()
        .ok()
        .and_then(|o| {
            String::from_utf8_lossy(&o.stdout)
                .split_whitespace()
                .next()?
                .parse::<u64>()
                .ok()
        })
        .unwrap_or(0)
}

/// Run the disk health check recipe via `recipe-runner-rs`.
///
/// `state_root` is the Simard state directory (typically `~/.simard`),
/// passed to the recipe as a context var so the bash script knows where
/// to find worktrees, backups, and cargo target dirs.
///
/// `repo_root` is used to locate the recipe YAML file.
///
/// Returns the parsed [`DiskHealthReport`] on success, or a
/// [`SimardError::AdapterInvocationFailed`] on any failure.
pub fn run_disk_health_check(
    repo_root: &Path,
    state_root: &Path,
) -> SimardResult<DiskHealthReport> {
    let recipe_path =
        resolve_recipe_path(repo_root).ok_or_else(|| SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!(
                "recipe file {RECIPE_FILENAME} not found in hot-reload or in-tree paths"
            ),
        })?;

    let agent_binary = RuntimeConfig::load()?.llm_provider.agent_binary_value();

    let output = Command::new("recipe-runner-rs")
        .arg(recipe_path.as_os_str())
        .arg("--output-format")
        .arg("json")
        .env("AMPLIHACK_AGENT_BINARY", agent_binary)
        .arg("-c")
        .arg(format!("state_root={}", state_root.display()))
        .arg("-c")
        .arg(format!("repo_path={}", repo_root.display()))
        .output()
        .map_err(|e| SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!("recipe-runner-rs spawn failed: {e}"),
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!(
                "recipe exited with {}: {}",
                output.status,
                truncate(&stderr, 500)
            ),
        });
    }

    let envelope: RecipeOutput = serde_json::from_slice(&output.stdout).map_err(|e| {
        SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!("failed to deserialize recipe JSON output: {e}"),
        }
    })?;

    if !envelope.success {
        return Err(SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: "recipe reported success=false in JSON output".to_string(),
        });
    }

    let step_output = envelope
        .step_results
        .first()
        .map(|s| s.output.as_str())
        .ok_or_else(|| SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: "no step results in recipe JSON output".to_string(),
        })?;

    parse_disk_health_text(step_output).map_err(|e| SimardError::AdapterInvocationFailed {
        base_type: ADAPTER_TAG.to_string(),
        reason: format!("failed to parse recipe text output: {e}"),
    })
}

fn truncate(s: &str, max: usize) -> String {
    let mut chars = s.chars();
    let prefix: String = chars.by_ref().take(max).collect();
    if chars.next().is_some() {
        prefix + "…"
    } else {
        prefix
    }
}

/// Parse key=value and ACTION: lines from recipe stdout text.
///
/// Expected format (bash recipe outputs this directly):
/// ```text
/// DISK_USED_PCT=87
/// FREED_BYTES=1024
/// ACTION: removed stale worktrees
/// ACTION: cleaned cargo target dirs
/// ```
///
/// This replaces the brittle `serde_json::from_slice::<DiskHealthReport>`
/// pattern — the recipe is a bash step, not an LLM. Bash can emit key=value
/// lines trivially; asking it to emit valid JSON was the source of fragility.
pub fn parse_disk_health_text(stdout: &str) -> Result<DiskHealthReport, String> {
    let mut disk_used_pct: Option<u8> = None;
    let mut freed_bytes: u64 = 0;
    let mut actions_taken: Vec<String> = Vec::new();

    for line in stdout.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(val) = trimmed.strip_prefix("DISK_USED_PCT=") {
            disk_used_pct = Some(
                val.trim()
                    .parse::<u8>()
                    .map_err(|e| format!("invalid DISK_USED_PCT value '{val}': {e}"))?,
            );
        } else if let Some(val) = trimmed.strip_prefix("FREED_BYTES=") {
            freed_bytes = val
                .trim()
                .parse::<u64>()
                .map_err(|e| format!("invalid FREED_BYTES value '{val}': {e}"))?;
        } else if let Some(action) = trimmed.strip_prefix("ACTION:") {
            let action = action.trim();
            if !action.is_empty() {
                actions_taken.push(action.to_string());
            }
        }
        // Unknown lines are silently ignored (forward-compat).
    }

    let disk_used_pct =
        disk_used_pct.ok_or_else(|| "missing DISK_USED_PCT line in recipe output".to_string())?;

    Ok(DiskHealthReport {
        disk_used_pct,
        freed_bytes,
        actions_taken,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------
    // Text-based parser (issue #1980 — replaces JSON deserialization)
    // ------------------------------------------------------------------

    #[test]
    fn text_parse_no_cleanup() {
        let text = "DISK_USED_PCT=65\nFREED_BYTES=0\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 65);
        assert_eq!(report.freed_bytes, 0);
        assert!(report.actions_taken.is_empty());
    }

    #[test]
    fn text_parse_with_cleanup_actions() {
        let text = "\
DISK_USED_PCT=87
FREED_BYTES=53687091200
ACTION: removed 12 stale engineer worktrees
ACTION: cleaned cargo target dirs in worktrees
ACTION: pruned LadybugDB backups to 5 most recent
ACTION: cleaned shared-target dir
";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 87);
        assert_eq!(report.freed_bytes, 53_687_091_200);
        assert_eq!(report.actions_taken.len(), 4);
        assert!(report.actions_taken[0].contains("worktrees"));
    }

    #[test]
    fn text_parse_boundary_100_percent() {
        let text = "DISK_USED_PCT=100\nFREED_BYTES=1024\nACTION: emergency cleanup\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 100);
        assert_eq!(report.freed_bytes, 1024);
        assert_eq!(report.actions_taken.len(), 1);
    }

    #[test]
    fn text_parse_boundary_0_percent() {
        let text = "DISK_USED_PCT=0\nFREED_BYTES=0\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 0);
    }

    #[test]
    fn text_parse_missing_disk_used_pct_is_error() {
        let text = "FREED_BYTES=0\n";
        let result = parse_disk_health_text(text);
        assert!(result.is_err(), "should reject missing DISK_USED_PCT");
        assert!(result.unwrap_err().contains("missing DISK_USED_PCT"));
    }

    #[test]
    fn text_parse_invalid_pct_value_is_error() {
        let text = "DISK_USED_PCT=high\nFREED_BYTES=0\n";
        let result = parse_disk_health_text(text);
        assert!(result.is_err(), "should reject non-numeric DISK_USED_PCT");
    }

    #[test]
    fn text_parse_empty_string_is_error() {
        let result = parse_disk_health_text("");
        assert!(result.is_err());
    }

    #[test]
    fn text_parse_freed_bytes_defaults_to_zero_when_absent() {
        let text = "DISK_USED_PCT=50\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.freed_bytes, 0);
        assert!(report.actions_taken.is_empty());
    }

    #[test]
    fn text_parse_ignores_unknown_lines() {
        let text = "DISK_USED_PCT=42\nSOME_OTHER_KEY=foo\nFREED_BYTES=100\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 42);
        assert_eq!(report.freed_bytes, 100);
    }

    #[test]
    fn text_parse_handles_whitespace_around_values() {
        let text = "  DISK_USED_PCT=42  \n  FREED_BYTES=100  \n  ACTION: did things  \n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 42);
        assert_eq!(report.freed_bytes, 100);
        assert_eq!(report.actions_taken, vec!["did things"]);
    }

    #[test]
    fn text_parse_skips_blank_lines() {
        let text = "\n\nDISK_USED_PCT=50\n\nFREED_BYTES=0\n\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.disk_used_pct, 50);
    }

    #[test]
    fn text_parse_action_without_text_is_skipped() {
        let text = "DISK_USED_PCT=50\nACTION:\nACTION: real action\n";
        let report = parse_disk_health_text(text).unwrap();
        assert_eq!(report.actions_taken, vec!["real action"]);
    }

    // ------------------------------------------------------------------
    // DiskHealthReport methods
    // ------------------------------------------------------------------

    #[test]
    fn cleanup_performed_true_when_freed_bytes_nonzero() {
        let report = DiskHealthReport {
            disk_used_pct: 85,
            freed_bytes: 1024,
            actions_taken: vec![],
        };
        assert!(report.cleanup_performed());
    }

    #[test]
    fn cleanup_performed_true_when_actions_nonempty() {
        let report = DiskHealthReport {
            disk_used_pct: 85,
            freed_bytes: 0,
            actions_taken: vec!["did something".to_string()],
        };
        assert!(report.cleanup_performed());
    }

    #[test]
    fn cleanup_performed_false_when_nothing_happened() {
        let report = DiskHealthReport {
            disk_used_pct: 50,
            freed_bytes: 0,
            actions_taken: vec![],
        };
        assert!(!report.cleanup_performed());
    }

    #[test]
    fn summary_no_cleanup() {
        let report = DiskHealthReport {
            disk_used_pct: 42,
            freed_bytes: 0,
            actions_taken: vec![],
        };
        let s = report.summary();
        assert!(s.contains("42%"), "summary should contain pct: {s}");
        assert!(
            s.contains("no cleanup"),
            "summary should say no cleanup: {s}"
        );
    }

    #[test]
    fn summary_with_cleanup() {
        let report = DiskHealthReport {
            disk_used_pct: 87,
            freed_bytes: 53_000_000_000,
            actions_taken: vec!["removed worktrees".to_string(), "cleaned cargo".to_string()],
        };
        let s = report.summary();
        assert!(s.contains("87%"), "summary should contain pct: {s}");
        assert!(s.contains("2 actions"), "summary should count actions: {s}");
        assert!(
            s.contains("53000000000"),
            "summary should contain freed bytes: {s}"
        );
    }

    // ------------------------------------------------------------------
    // resolve_recipe_path
    // ------------------------------------------------------------------

    #[test]
    fn resolve_recipe_path_returns_none_for_nonexistent_dir() {
        let result = resolve_recipe_path(Path::new("/nonexistent/repo"));
        assert!(result.is_none());
    }

    #[test]
    fn resolve_recipe_path_finds_in_tree_recipe() {
        let tmp = tempfile::tempdir().unwrap();
        let recipe_dir = tmp.path().join("prompt_assets/simard/recipes");
        std::fs::create_dir_all(&recipe_dir).unwrap();
        std::fs::write(recipe_dir.join(RECIPE_FILENAME), "name: test").unwrap();

        let result = resolve_recipe_path(tmp.path());
        assert!(result.is_some());
        assert!(result.unwrap().ends_with(RECIPE_FILENAME));
    }

    // ------------------------------------------------------------------
    // run_disk_health_check — error paths (no recipe-runner-rs needed)
    // ------------------------------------------------------------------

    #[test]
    fn run_returns_error_when_recipe_not_found() {
        let result = run_disk_health_check(
            Path::new("/nonexistent/repo"),
            Path::new("/nonexistent/state"),
        );
        assert!(result.is_err());
        let err = result.unwrap_err();
        match &err {
            SimardError::AdapterInvocationFailed { base_type, reason } => {
                assert_eq!(base_type, ADAPTER_TAG);
                assert!(
                    reason.contains("not found"),
                    "reason should mention not found: {reason}"
                );
            }
            other => panic!("expected AdapterInvocationFailed, got: {other:?}"),
        }
    }

    #[test]
    fn run_returns_error_when_recipe_runner_unavailable_or_recipe_invalid() {
        // Create a syntactically-invalid recipe file. If recipe-runner-rs
        // is installed it will reject it (non-zero exit); if it's missing
        // the spawn itself fails. Either way we get AdapterInvocationFailed.
        let tmp = tempfile::tempdir().unwrap();
        let recipe_dir = tmp.path().join("prompt_assets/simard/recipes");
        std::fs::create_dir_all(&recipe_dir).unwrap();
        std::fs::write(recipe_dir.join(RECIPE_FILENAME), "name: test").unwrap();

        // Ensure RuntimeConfig::load() succeeds (CI has no config.toml).
        // SAFETY: test-only, single-threaded access to env var.
        unsafe { std::env::set_var("SIMARD_LLM_PROVIDER", "copilot") };
        let result = run_disk_health_check(tmp.path(), tmp.path());
        unsafe { std::env::remove_var("SIMARD_LLM_PROVIDER") };
        assert!(result.is_err());
        let err = result.unwrap_err();
        match &err {
            SimardError::AdapterInvocationFailed { base_type, reason } => {
                assert_eq!(base_type, ADAPTER_TAG);
                // Either "spawn failed" (binary missing) or "recipe exited"
                // (binary found, recipe invalid).
                assert!(
                    reason.contains("spawn failed") || reason.contains("recipe exited"),
                    "reason should mention spawn failure or recipe exit: {reason}"
                );
            }
            other => panic!("expected AdapterInvocationFailed, got: {other:?}"),
        }
    }

    // ------------------------------------------------------------------
    // JSON envelope deserialization (issue #2212 — TDD: tests written first)
    // ------------------------------------------------------------------

    #[test]
    fn json_envelope_deserialization() {
        // Full pipeline: JSON envelope → RecipeOutput → step_results[0].output → parse_disk_health_text → DiskHealthReport
        let json = r#"{
            "success": true,
            "step_results": [{
                "step_id": "disk-health-step",
                "output": "DISK_USED_PCT=72\nFREED_BYTES=1024\nACTION: cleaned worktrees\n"
            }]
        }"#;
        let envelope: RecipeOutput = serde_json::from_str(json).unwrap();
        assert!(envelope.success);
        assert_eq!(envelope.step_results.len(), 1);
        assert_eq!(envelope.step_results[0].step_id, "disk-health-step");

        let report = parse_disk_health_text(&envelope.step_results[0].output).unwrap();
        assert_eq!(report.disk_used_pct, 72);
        assert_eq!(report.freed_bytes, 1024);
        assert_eq!(report.actions_taken, vec!["cleaned worktrees"]);
    }

    #[test]
    fn json_envelope_empty_step_results() {
        // When step_results is empty, extracting step output should fail gracefully.
        let json = r#"{"success": true, "step_results": []}"#;
        let envelope: RecipeOutput = serde_json::from_str(json).unwrap();
        assert!(envelope.step_results.is_empty());
    }

    #[test]
    fn json_envelope_multiple_steps_uses_first() {
        // Only step_results[0].output is used for parsing.
        let json = r#"{
            "success": true,
            "step_results": [
                {"step_id": "step-1", "output": "DISK_USED_PCT=55\nFREED_BYTES=0\n"},
                {"step_id": "step-2", "output": "some other output"}
            ]
        }"#;
        let envelope: RecipeOutput = serde_json::from_str(json).unwrap();
        assert_eq!(envelope.step_results.len(), 2);

        let report = parse_disk_health_text(&envelope.step_results[0].output).unwrap();
        assert_eq!(report.disk_used_pct, 55);
    }

    // ------------------------------------------------------------------
    // Noisy agent output (issue #2212 — markers in LLM conversation text)
    // ------------------------------------------------------------------

    #[test]
    fn parse_markers_from_agent_output_with_noise() {
        // The agent's step output contains LLM reasoning, df output, and
        // bash prompts — the parser must extract markers from this noise.
        let noisy_output = "\
I'll check the disk usage now.

Running df -h to check disk space...

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       100G   72G   28G  72% /

The disk is at 72% usage, which is below the 80% threshold.
No cleanup actions are needed.

DISK_USED_PCT=72
FREED_BYTES=0
";
        let report = parse_disk_health_text(noisy_output).unwrap();
        assert_eq!(report.disk_used_pct, 72);
        assert_eq!(report.freed_bytes, 0);
        assert!(report.actions_taken.is_empty());
    }

    #[test]
    fn parse_markers_from_noisy_output_with_cleanup() {
        let noisy_output = "\
Checking disk usage...

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       100G   87G   13G  87% /

Disk usage is at 87%, exceeding 80% threshold. Performing cleanup.

Removing stale worktrees...
Done. Removed 12 worktrees.

Cleaning cargo target directories...
Done.

DISK_USED_PCT=87
FREED_BYTES=53687091200
ACTION: removed 12 stale engineer worktrees
ACTION: cleaned cargo target dirs
";
        let report = parse_disk_health_text(noisy_output).unwrap();
        assert_eq!(report.disk_used_pct, 87);
        assert_eq!(report.freed_bytes, 53_687_091_200);
        assert_eq!(report.actions_taken.len(), 2);
        assert!(report.actions_taken[0].contains("worktrees"));
        assert!(report.actions_taken[1].contains("cargo"));
    }

    // ------------------------------------------------------------------
    // truncate helper
    // ------------------------------------------------------------------

    #[test]
    fn truncate_short_string_unchanged() {
        assert_eq!(truncate("hello", 10), "hello");
    }

    #[test]
    fn truncate_exact_length_unchanged() {
        assert_eq!(truncate("hello", 5), "hello");
    }

    #[test]
    fn truncate_long_string_adds_ellipsis() {
        let result = truncate("hello world", 5);
        assert_eq!(result, "hello…");
    }

    #[test]
    fn truncate_empty_string() {
        assert_eq!(truncate("", 5), "");
    }

    #[test]
    fn truncate_zero_max() {
        let result = truncate("hello", 0);
        assert_eq!(result, "…");
    }
}
