//! Recipe-runner-backed disk health check (issue #2020; reworked in #4722).
//!
//! Two-tier approach:
//!   1. **Deterministic emergency cleanup** — pure Rust, no LLM, runs when disk
//!      is critically full (≥95%). Deletes known-safe build artifacts immediately.
//!   2. **Agentic recipe trigger** — when disk is moderately full, the daemon
//!      runs the `disk-health-check` recipe. The recipe *acts* through the
//!      safety-enforcing `simard disk` tool and prints no envelope; this module
//!      is a **thin trigger** that records success/failure by the recipe child's
//!      exit status alone (issue #4722). It no longer parses recipe stdout.
//!
//! The emergency tier exists because the recipe tier needs disk space to spawn
//! an agent process. At 100% disk, the recipe deadlocks.

use std::path::{Path, PathBuf};
use std::process::Command;

use tracing::{info, warn};

use crate::error::{SimardError, SimardResult};
use crate::runtime_config::RuntimeConfig;

const ADAPTER_TAG: &str = "disk-health-check";
const RECIPE_FILENAME: &str = "disk-health-check.yaml";

/// Deterministic result of the Tier-1 emergency cleanup (pure Rust, no recipe,
/// no LLM). This is **not** recipe-output scraping — it is the direct return of
/// the in-process `rm` pass, so it stays after the issue #4722 rework that
/// removed all recipe-stdout parsing from this file.
#[derive(Debug, Clone, PartialEq)]
pub struct DiskHealthReport {
    /// Current disk usage percentage (0–100).
    pub disk_used_pct: u8,
    /// Total bytes freed during this check (0 if no cleanup needed).
    pub freed_bytes: u64,
    /// Human-readable list of cleanup actions taken.
    pub actions_taken: Vec<String>,
}

/// Resolve the recipe YAML path. Checks, in order:
///   1. `~/.simard/prompt_assets/simard/recipes/<name>` (hot-reload path)
///   2. `<repo_root>/prompt_assets/simard/recipes/<name>` (in-tree)
///
/// `home_override` allows tests to supply a fake home directory without
/// mutating the process-wide `HOME` environment variable.
fn resolve_recipe_path(repo_root: &Path, home_override: Option<&Path>) -> Option<PathBuf> {
    let home = home_override.map(PathBuf::from).or_else(dirs::home_dir);
    if let Some(home) = home {
        let hot = home
            .join(".simard")
            .join("prompt_assets/simard/recipes")
            .join(RECIPE_FILENAME);
        if hot.is_file() {
            return Some(hot);
        }
    }
    let in_tree = repo_root
        .join("prompt_assets/simard/recipes")
        .join(RECIPE_FILENAME);
    if in_tree.is_file() {
        return Some(in_tree);
    }
    None
}

/// Deterministic emergency disk cleanup — no LLM, no recipe, just rm.
///
/// Runs when disk usage is critically high (≥95%). Deletes known-safe build
/// artifacts that can always be regenerated by `cargo build`:
///   - `repo_root/target/debug/` (main build cache)
///   - `repo_root/worktrees/*/target/` (engineer worktree build caches)
///   - `repo_root/target/llvm-cov-target/` (coverage artifacts)
///   - `state_root/cargo-target/` and `state_root/shared-target/`
///   - stale backups beyond the 2 most recent
///
/// Returns a report of what was done, or None if disk is below threshold.
pub fn emergency_cleanup(repo_root: &Path, state_root: &Path) -> Option<DiskHealthReport> {
    let pct = get_disk_usage_pct(repo_root)?;

    if pct < 95 {
        return None;
    }

    warn!(disk_pct = pct, "Emergency disk cleanup triggered (≥95%)");
    let mut freed: u64 = 0;
    let mut actions: Vec<String> = Vec::new();

    // 1. Main target/debug/ — the single biggest consumer
    let debug_dir = repo_root.join("target/debug");
    if debug_dir.is_dir() {
        let size = dir_size_bytes(&debug_dir);
        if std::fs::remove_dir_all(&debug_dir).is_ok() {
            freed += size;
            actions.push(format!("Removed target/debug/ ({} MB)", size / 1_000_000));
        }
    }

    // 2. target/llvm-cov-target/
    let cov_dir = repo_root.join("target/llvm-cov-target");
    if cov_dir.is_dir() {
        let size = dir_size_bytes(&cov_dir);
        if std::fs::remove_dir_all(&cov_dir).is_ok() {
            freed += size;
            actions.push(format!(
                "Removed target/llvm-cov-target/ ({} MB)",
                size / 1_000_000
            ));
        }
    }

    // 3. Engineer worktree target/ dirs
    let worktrees_dir = repo_root.join("worktrees");
    if worktrees_dir.is_dir()
        && let Ok(entries) = std::fs::read_dir(&worktrees_dir)
    {
        for entry in entries.flatten() {
            let target = entry.path().join("target");
            if target.is_dir() {
                let size = dir_size_bytes(&target);
                if std::fs::remove_dir_all(&target).is_ok() {
                    freed += size;
                    actions.push(format!(
                        "Removed worktrees/{}/target/ ({} MB)",
                        entry.file_name().to_string_lossy(),
                        size / 1_000_000
                    ));
                }
            }
        }
    }

    // 4. State root cargo dirs
    for name in &["cargo-target", "shared-target"] {
        let dir = state_root.join(name);
        if dir.is_dir() {
            let size = dir_size_bytes(&dir);
            if std::fs::remove_dir_all(&dir).is_ok() {
                freed += size;
                actions.push(format!("Removed {name}/ ({} MB)", size / 1_000_000));
            }
        }
    }

    // 5. Stale backups (keep 2 most recent)
    let backup_dir = state_root.join("backups");
    if backup_dir.is_dir()
        && let Ok(mut entries) = std::fs::read_dir(&backup_dir)
    {
        let mut files: Vec<_> = entries
            .by_ref()
            .flatten()
            .filter(|e| e.path().is_file())
            .collect();
        files.sort_by_key(|e| {
            std::cmp::Reverse(
                e.metadata()
                    .ok()
                    .and_then(|m| m.modified().ok())
                    .unwrap_or(std::time::SystemTime::UNIX_EPOCH),
            )
        });
        for old in files.into_iter().skip(2) {
            let size = old.metadata().map(|m| m.len()).unwrap_or(0);
            if std::fs::remove_file(old.path()).is_ok() {
                freed += size;
            }
        }
        if freed > 0 {
            actions.push("Pruned old backups (kept 2 most recent)".to_string());
        }
    }

    let final_pct = get_disk_usage_pct(repo_root).unwrap_or(pct);
    info!(
        freed_mb = freed / 1_000_000,
        before_pct = pct,
        after_pct = final_pct,
        "Emergency cleanup complete"
    );

    Some(DiskHealthReport {
        disk_used_pct: final_pct,
        freed_bytes: freed,
        actions_taken: actions,
    })
}

/// Get disk usage percentage for the filesystem containing `path`.
fn get_disk_usage_pct(path: &Path) -> Option<u8> {
    let output = Command::new("df")
        .arg("--output=pcent")
        .arg(path)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&output.stdout);
    text.lines()
        .nth(1)?
        .trim()
        .trim_end_matches('%')
        .parse::<u8>()
        .ok()
}

/// Estimate directory size in bytes (non-recursive stat, uses du).
fn dir_size_bytes(path: &Path) -> u64 {
    Command::new("du")
        .arg("-sb")
        .arg(path)
        .output()
        .ok()
        .and_then(|o| {
            String::from_utf8_lossy(&o.stdout)
                .split_whitespace()
                .next()?
                .parse::<u64>()
                .ok()
        })
        .unwrap_or(0)
}

/// Run the disk-health-check recipe via `recipe-runner-rs` as a thin trigger
/// (issue #4722).
///
/// The recipe now *acts* through the `simard disk` tool (which enforces the
/// disk-safety heuristic internally) and prints **no** JSON envelope. This
/// function therefore no longer parses recipe stdout: it records success/failure
/// by the child's **exit status alone**.
///
/// `state_root` is the Simard state directory (typically `~/.simard`), passed to
/// the recipe as a context var. `repo_root` is used to locate the recipe YAML.
/// `home_override` lets tests supply a fake home directory without mutating the
/// process-wide `HOME`.
///
/// Returns:
///   - `Ok(true)`  — the recipe child exited `0`.
///   - `Ok(false)` — the recipe child exited non-zero (recorded as a failure;
///     stderr is warn-logged for diagnostics but never parsed).
///   - `Err(..)`   — the recipe file could not be resolved or the child could
///     not be spawned. These are structural failures, distinct from a recipe
///     that ran and reported failure.
pub fn run_disk_health_check(
    repo_root: &Path,
    state_root: &Path,
    home_override: Option<&Path>,
) -> SimardResult<bool> {
    let recipe_path = resolve_recipe_path(repo_root, home_override).ok_or_else(|| {
        SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!(
                "recipe file {RECIPE_FILENAME} not found in hot-reload or in-tree paths"
            ),
        }
    })?;

    let agent_binary = RuntimeConfig::load()?.llm_provider.agent_binary_value();

    // No `--output-format json`: the recipe acts via the `simard disk` tool and
    // prints no envelope. We interpret the run by exit status only.
    let output = Command::new("recipe-runner-rs")
        .arg(recipe_path.as_os_str())
        .env("AMPLIHACK_AGENT_BINARY", agent_binary)
        .arg("-c")
        .arg(format!("state_root={}", state_root.display()))
        .arg("-c")
        .arg(format!("repo_path={}", repo_root.display()))
        .output()
        .map_err(|e| SimardError::AdapterInvocationFailed {
            base_type: ADAPTER_TAG.to_string(),
            reason: format!("recipe-runner-rs spawn failed: {e}"),
        })?;

    let success = child_exit_indicates_success(&output.status);
    if !success {
        let stderr = String::from_utf8_lossy(&output.stderr);
        warn!(
            status = %output.status,
            stderr = %truncate(stderr.trim(), 500),
            "disk-health recipe exited non-zero"
        );
    }
    Ok(success)
}

/// The exit-status → success contract for the reworked thin trigger (issue
/// #4722). `run_disk_health_check` records success/failure by the recipe child's
/// **exit status alone** — it no longer parses recipe stdout. The recipe acts
/// via the `simard disk` tool and prints no JSON envelope.
///
/// `true` iff the child exited `0`; `false` for any non-zero exit (including
/// signals). A spawn failure is a distinct `Err` at the call site, never mapped
/// here.
pub(crate) fn child_exit_indicates_success(status: &std::process::ExitStatus) -> bool {
    status.success()
}

fn truncate(s: &str, max: usize) -> String {
    let mut chars = s.chars();
    let prefix: String = chars.by_ref().take(max).collect();
    if chars.next().is_some() {
        prefix + "…"
    } else {
        prefix
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;

    // ------------------------------------------------------------------
    // Thin exit-status trigger contract (issue #4722 — TDD, written first)
    //
    // After the rework the disk-health trigger records success/failure by the
    // recipe child's EXIT STATUS alone; it no longer parses recipe stdout. These
    // tests pin that contract on the pure `child_exit_indicates_success` seam so
    // the reworked `run_disk_health_check` can adopt `SimardResult<bool>` without
    // reintroducing any output scraping.
    // ------------------------------------------------------------------

    #[test]
    fn child_exit_zero_is_success() {
        let status = std::process::Command::new("true")
            .status()
            .expect("spawn `true`");
        assert!(
            child_exit_indicates_success(&status),
            "exit 0 must record success"
        );
    }

    #[test]
    fn child_exit_nonzero_is_failure() {
        let status = std::process::Command::new("false")
            .status()
            .expect("spawn `false`");
        assert!(
            !child_exit_indicates_success(&status),
            "a non-zero exit must record failure"
        );
    }

    // ------------------------------------------------------------------
    // resolve_recipe_path
    // ------------------------------------------------------------------

    #[test]
    fn resolve_recipe_path_returns_none_for_nonexistent_dir() {
        let guard = tempfile::tempdir().unwrap();
        let result = resolve_recipe_path(Path::new("/nonexistent/repo"), Some(guard.path()));
        assert!(result.is_none());
    }

    #[test]
    fn resolve_recipe_path_finds_in_tree_recipe() {
        let tmp = tempfile::tempdir().unwrap();
        let recipe_dir = tmp.path().join("prompt_assets/simard/recipes");
        std::fs::create_dir_all(&recipe_dir).unwrap();
        std::fs::write(recipe_dir.join(RECIPE_FILENAME), "name: test").unwrap();

        let result = resolve_recipe_path(tmp.path(), Some(tmp.path()));
        assert!(result.is_some());
        assert!(result.unwrap().ends_with(RECIPE_FILENAME));
    }

    // ------------------------------------------------------------------
    // run_disk_health_check — error paths (no recipe-runner-rs needed)
    // ------------------------------------------------------------------

    #[test]
    fn run_returns_error_when_recipe_not_found() {
        let guard = tempfile::tempdir().unwrap();
        let result = run_disk_health_check(
            Path::new("/nonexistent/repo"),
            Path::new("/nonexistent/state"),
            Some(guard.path()),
        );
        assert!(result.is_err());
        let err = result.unwrap_err();
        match &err {
            SimardError::AdapterInvocationFailed { base_type, reason } => {
                assert_eq!(base_type, ADAPTER_TAG);
                assert!(
                    reason.contains("not found"),
                    "reason should mention not found: {reason}"
                );
            }
            other => panic!("expected AdapterInvocationFailed, got: {other:?}"),
        }
    }

    #[test]
    // #2360: mutates SIMARD_LLM_PROVIDER (process-global). Keyed into the
    // cognitive_memory serial group so it never runs concurrently with a
    // provider/state-root env reader.
    #[serial(cognitive_memory)]
    fn run_records_failure_when_recipe_runner_unavailable_or_recipe_invalid() {
        // Create a syntactically-invalid recipe file. Under the thin-trigger
        // contract (issue #4722): if recipe-runner-rs is missing the spawn fails
        // -> Err; if it's installed it rejects the recipe with a non-zero exit
        // -> Ok(false). Either way this is a *failure* outcome, never Ok(true).
        let tmp = tempfile::tempdir().unwrap();
        let recipe_dir = tmp.path().join("prompt_assets/simard/recipes");
        std::fs::create_dir_all(&recipe_dir).unwrap();
        std::fs::write(recipe_dir.join(RECIPE_FILENAME), "name: test").unwrap();

        // Ensure RuntimeConfig::load() succeeds (CI has no config.toml).
        // SAFETY: SIMARD_LLM_PROVIDER is not related to HOME; it controls
        // which LLM provider the runtime selects. This is still env-var
        // mutation but not the HOME-related UB that Finding 2 targets.
        unsafe { std::env::set_var("SIMARD_LLM_PROVIDER", "copilot") };
        let result = run_disk_health_check(tmp.path(), tmp.path(), Some(tmp.path()));
        unsafe { std::env::remove_var("SIMARD_LLM_PROVIDER") };

        match result {
            // recipe-runner-rs missing: spawn failure surfaces as a structural Err.
            Err(SimardError::AdapterInvocationFailed { base_type, reason }) => {
                assert_eq!(base_type, ADAPTER_TAG);
                assert!(
                    reason.contains("spawn failed"),
                    "spawn-failure reason expected: {reason}"
                );
            }
            // recipe-runner-rs present: the invalid recipe exits non-zero, which
            // the thin trigger records as Ok(false) (no stdout parsing).
            Ok(false) => {}
            other => panic!("expected Err(spawn failed) or Ok(false), got: {other:?}"),
        }
    }

    // ------------------------------------------------------------------
    // truncate helper
    // ------------------------------------------------------------------

    #[test]
    fn truncate_short_string_unchanged() {
        assert_eq!(truncate("hello", 10), "hello");
    }

    #[test]
    fn truncate_exact_length_unchanged() {
        assert_eq!(truncate("hello", 5), "hello");
    }

    #[test]
    fn truncate_long_string_adds_ellipsis() {
        let result = truncate("hello world", 5);
        assert_eq!(result, "hello…");
    }

    #[test]
    fn truncate_empty_string() {
        assert_eq!(truncate("", 5), "");
    }

    #[test]
    fn truncate_zero_max() {
        let result = truncate("hello", 0);
        assert_eq!(result, "…");
    }
}
