//! OODA (Observe-Orient-Decide-Act) loop for continuous autonomous operation.
//!
//! The outer OODA cycle gathers observations from all subsystems, orients by
//! ranking priorities, decides on actions within concurrency limits, and
//! dispatches them. If any bridge is unavailable, the cycle degrades honestly
//! (Pillar 11): the observation records `None` for that subsystem.

use std::fmt::{self, Display, Formatter};
use std::time::Instant;

use crate::error::SimardResult;
use crate::goal_curation::{ActiveGoal, GoalBoard, GoalProgress, load_goal_board};
use crate::goals::GoalStatus;
use crate::gym_bridge::{GymBridge, ScoreDimensions};
use crate::gym_history::{GymSignal, ScoreHistory, generate_signals};
use crate::gym_scoring::{GymSuiteScore, detect_regression};
use crate::improvements::ImprovementDirective;
use crate::knowledge_bridge::KnowledgeBridge;
use crate::meeting_facilitator::load_meeting_handoff;
use crate::memory_bridge::CognitiveMemoryBridge;
use crate::memory_cognitive::CognitiveStatistics;
use crate::self_improve::{ImprovementCycle, ImprovementPhase};

/// The four phases of a single OODA cycle.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OodaPhase {
    Observe,
    Orient,
    Decide,
    Act,
}

impl Display for OodaPhase {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Observe => f.write_str("observe"),
            Self::Orient => f.write_str("orient"),
            Self::Decide => f.write_str("decide"),
            Self::Act => f.write_str("act"),
        }
    }
}

/// Mutable state carried across OODA cycles.
pub struct OodaState {
    pub current_phase: OodaPhase,
    pub active_goals: GoalBoard,
    pub cycle_count: u32,
    pub last_observation: Option<Observation>,
    /// Improvement proposals generated by post-act review, drained by observe().
    pub review_improvements: Vec<ImprovementCycle>,
}

impl OodaState {
    pub fn new(goals: GoalBoard) -> Self {
        Self {
            current_phase: OodaPhase::Observe,
            active_goals: goals,
            cycle_count: 0,
            last_observation: None,
            review_improvements: Vec::new(),
        }
    }
}

/// A single goal's status snapshot for observation.
#[derive(Clone, Debug)]
pub struct GoalSnapshot {
    pub id: String,
    pub description: String,
    pub progress: GoalProgress,
}

impl From<&ActiveGoal> for GoalSnapshot {
    fn from(g: &ActiveGoal) -> Self {
        Self {
            id: g.id.clone(),
            description: g.description.clone(),
            progress: g.status.clone(),
        }
    }
}

/// Snapshot of the local environment: git state, issues, recent commits.
#[derive(Clone, Debug, Default)]
pub struct EnvironmentSnapshot {
    /// Output of `git status --porcelain` (empty string if unavailable).
    pub git_status: String,
    /// Open issue titles from `gh issue list` (empty if unavailable).
    pub open_issues: Vec<String>,
    /// Recent commit one-liners from `git log --oneline -10`.
    pub recent_commits: Vec<String>,
}

/// Everything gathered during the Observe phase.
#[derive(Clone, Debug)]
pub struct Observation {
    pub goal_statuses: Vec<GoalSnapshot>,
    pub gym_health: Option<GymSuiteScore>,
    pub memory_stats: CognitiveStatistics,
    pub pending_improvements: Vec<ImprovementCycle>,
    /// Local environment state for goal assessment.
    pub environment: EnvironmentSnapshot,
}

/// A ranked priority produced during the Orient phase.
#[derive(Clone, Debug)]
pub struct Priority {
    pub goal_id: String,
    pub urgency: f64,
    pub reason: String,
}

/// The kind of action the OODA loop can dispatch.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ActionKind {
    AdvanceGoal,
    RunImprovement,
    ConsolidateMemory,
    ResearchQuery,
    RunGymEval,
    BuildSkill,
    LaunchSession,
}

impl Display for ActionKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::AdvanceGoal => f.write_str("advance-goal"),
            Self::RunImprovement => f.write_str("run-improvement"),
            Self::ConsolidateMemory => f.write_str("consolidate-memory"),
            Self::ResearchQuery => f.write_str("research-query"),
            Self::RunGymEval => f.write_str("run-gym-eval"),
            Self::BuildSkill => f.write_str("build-skill"),
            Self::LaunchSession => f.write_str("launch-session"),
        }
    }
}

/// A planned action selected during the Decide phase.
#[derive(Clone, Debug)]
pub struct PlannedAction {
    pub kind: ActionKind,
    pub goal_id: Option<String>,
    pub description: String,
}

/// Outcome of dispatching a single action.
#[derive(Clone, Debug)]
pub struct ActionOutcome {
    pub action: PlannedAction,
    pub success: bool,
    pub detail: String,
}

/// Report for one complete OODA cycle.
#[derive(Clone, Debug)]
pub struct CycleReport {
    pub cycle_number: u32,
    pub observation: Observation,
    pub priorities: Vec<Priority>,
    pub planned_actions: Vec<PlannedAction>,
    pub outcomes: Vec<ActionOutcome>,
}

/// Configuration for the OODA loop.
#[derive(Clone, Debug)]
pub struct OodaConfig {
    pub max_concurrent_actions: u32,
    pub improvement_threshold: f64,
    pub gym_suite_id: String,
}

impl Default for OodaConfig {
    fn default() -> Self {
        Self {
            max_concurrent_actions: 3,
            improvement_threshold: 0.02,
            gym_suite_id: "progressive".to_string(),
        }
    }
}

/// All bridges needed by the OODA loop.
pub struct OodaBridges {
    pub memory: CognitiveMemoryBridge,
    pub knowledge: KnowledgeBridge,
    pub gym: GymBridge,
    /// Optional base-type session for real autonomous work (e.g. RustyClawd).
    /// When present, `AdvanceGoal` actions use `run_turn` to delegate work
    /// to an LLM agent instead of just bumping a progress percentage.
    pub session: Option<Box<dyn crate::base_types::BaseTypeSession>>,
}

/// Gather a snapshot of the local environment (git status, issues, commits).
///
/// Each sub-command degrades honestly: if the tool is unavailable the
/// corresponding field is empty rather than causing a cycle failure.
pub fn gather_environment() -> EnvironmentSnapshot {
    let git_status = std::process::Command::new("git")
        .args(["status", "--porcelain"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();

    let open_issues = std::process::Command::new("gh")
        .args([
            "issue",
            "list",
            "--state",
            "open",
            "--limit",
            "20",
            "--json",
            "title",
            "--jq",
            ".[].title",
        ])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    let recent_commits = std::process::Command::new("git")
        .args(["log", "--oneline", "-10"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    EnvironmentSnapshot {
        git_status,
        open_issues,
        recent_commits,
    }
}

/// Observe: gather goal statuses, environment state, gym health, memory stats,
/// and pending improvement signals from gym regressions and unprocessed handoffs.
/// Sub-system failures produce degraded fields rather than aborting (Pillar 11).
pub fn observe(state: &mut OodaState, bridges: &OodaBridges) -> SimardResult<Observation> {
    let goal_statuses: Vec<GoalSnapshot> = state
        .active_goals
        .active
        .iter()
        .map(GoalSnapshot::from)
        .collect();

    let environment = gather_environment();

    let gym_health = match bridges.gym.run_suite("progressive") {
        Ok(result) => {
            use crate::gym_scoring::suite_score_from_result;
            Some(suite_score_from_result(&result))
        }
        Err(e) => {
            eprintln!("[simard] OODA observe: gym bridge unavailable: {e}");
            None
        }
    };
    let memory_stats = match bridges.memory.get_statistics() {
        Ok(stats) => stats,
        Err(e) => {
            eprintln!("[simard] OODA observe: memory bridge unavailable: {e}");
            CognitiveStatistics::default()
        }
    };

    let pending_improvements = collect_pending_improvements(state, &gym_health);

    Ok(Observation {
        goal_statuses,
        gym_health,
        memory_stats,
        pending_improvements,
        environment,
    })
}

/// Collect pending improvement signals from gym regressions, unprocessed
/// meeting handoffs, and OODA review proposals. Each source degrades
/// independently — a failure in one does not prevent others from contributing.
fn collect_pending_improvements(
    state: &mut OodaState,
    current_gym: &Option<GymSuiteScore>,
) -> Vec<ImprovementCycle> {
    let mut improvements = Vec::new();

    // Signal 1: gym regressions vs last observation.
    if let (Some(current), Some(prev_obs)) = (current_gym, &state.last_observation)
        && let Some(baseline) = &prev_obs.gym_health
    {
        let regressions = detect_regression(current, baseline);
        if !regressions.is_empty() {
            improvements.push(ImprovementCycle {
                baseline: baseline.clone(),
                proposed_changes: Vec::new(),
                post_score: Some(current.clone()),
                regressions,
                decision: None,
                final_phase: ImprovementPhase::Eval,
            });
        }
    }

    // Signal 2: unprocessed meeting handoffs.
    match scan_unprocessed_handoffs() {
        Ok(true) => {
            let baseline = current_gym.clone().unwrap_or_else(|| GymSuiteScore {
                suite_id: "handoff-signal".to_string(),
                overall: 0.0,
                dimensions: ScoreDimensions::default(),
                scenario_count: 0,
                scenarios_passed: 0,
                pass_rate: 0.0,
                recorded_at_unix_ms: None,
            });
            improvements.push(ImprovementCycle {
                baseline,
                proposed_changes: Vec::new(),
                post_score: None,
                regressions: Vec::new(),
                decision: None,
                final_phase: ImprovementPhase::Eval,
            });
        }
        Ok(false) => {}
        Err(e) => {
            eprintln!("[simard] OODA observe: handoff scan failed: {e}");
        }
    }

    // Signal 3: improvement proposals from post-act review analysis.
    if !state.review_improvements.is_empty() {
        eprintln!(
            "[simard] OODA observe: draining {} review improvement(s) from prior cycle",
            state.review_improvements.len()
        );
        improvements.append(&mut state.review_improvements);
    }

    // Signal 4: persistent gym score history (regression / promotion signals).
    let history_path = std::path::Path::new("gym_history.db");
    if history_path.exists() {
        let history = ScoreHistory::open(history_path);
        let signals = generate_signals(&history, "progressive");
        for sig in &signals {
            if matches!(sig.signal, GymSignal::Regression { .. }) {
                let baseline = current_gym.clone().unwrap_or_else(|| GymSuiteScore {
                    suite_id: "history-regression".to_string(),
                    overall: 0.0,
                    dimensions: ScoreDimensions::default(),
                    scenario_count: 0,
                    scenarios_passed: 0,
                    pass_rate: 0.0,
                    recorded_at_unix_ms: None,
                });
                eprintln!(
                    "[simard] OODA observe: gym history regression on scenario {}",
                    sig.scenario_id,
                );
                improvements.push(ImprovementCycle {
                    baseline,
                    proposed_changes: Vec::new(),
                    post_score: None,
                    regressions: Vec::new(),
                    decision: None,
                    final_phase: ImprovementPhase::Eval,
                });
            }
        }
    }

    improvements
}

/// Check whether there is an unprocessed meeting handoff in the default
/// handoff directory. Returns `true` when one exists.
fn scan_unprocessed_handoffs() -> SimardResult<bool> {
    let dir = crate::meeting_facilitator::default_handoff_dir();
    scan_unprocessed_handoffs_in(&dir)
}

fn scan_unprocessed_handoffs_in(dir: &std::path::Path) -> SimardResult<bool> {
    match load_meeting_handoff(dir) {
        Ok(Some(h)) if !h.processed => Ok(true),
        Ok(_) => Ok(false),
        Err(e) => Err(e),
    }
}

/// Orient: rank goals by urgency, informed by environment context.
///
/// Base urgency: Blocked > not-started > in-progress > completed.
/// Environment signals (dirty working tree, open issues mentioning a goal)
/// can boost a goal's urgency so the OODA loop prioritises actionable work.
pub fn orient(observation: &Observation, goals: &GoalBoard) -> SimardResult<Vec<Priority>> {
    let env = &observation.environment;
    let has_dirty_tree = !env.git_status.is_empty();

    let mut priorities: Vec<Priority> = goals
        .active
        .iter()
        .map(|g| {
            let (mut urgency, mut reason) = match &g.status {
                GoalProgress::Blocked(r) => (1.0, format!("blocked: {r}")),
                GoalProgress::NotStarted => (0.8, "not yet started".to_string()),
                GoalProgress::InProgress { percent } => (
                    0.6 * (1.0 - (*percent as f64 / 100.0)),
                    format!("{percent}% complete"),
                ),
                GoalProgress::Completed => (0.0, "completed".to_string()),
            };

            // Boost urgency if an open issue mentions this goal.
            let mentioned_in_issues = env
                .open_issues
                .iter()
                .any(|title| title.to_lowercase().contains(&g.id.to_lowercase()));
            if mentioned_in_issues {
                urgency = (urgency + 0.1).min(1.0);
                reason = format!("{reason}; mentioned in open issue");
            }

            // Slight boost for in-progress goals when the tree is dirty
            // (indicates active development that may relate to this goal).
            if has_dirty_tree && matches!(g.status, GoalProgress::InProgress { .. }) {
                urgency = (urgency + 0.05).min(1.0);
                reason = format!("{reason}; dirty working tree");
            }

            Priority {
                goal_id: g.id.clone(),
                urgency,
                reason,
            }
        })
        .collect();

    if observation.memory_stats.episodic_count > 100 {
        priorities.push(Priority {
            goal_id: "__memory__".to_string(),
            urgency: 0.5,
            reason: format!(
                "episodic memory has {} entries, consolidation needed",
                observation.memory_stats.episodic_count
            ),
        });
    }

    if let Some(ref score) = observation.gym_health
        && score.overall < 0.7
    {
        priorities.push(Priority {
            goal_id: "__improvement__".to_string(),
            urgency: 0.7,
            reason: format!("gym overall {:.1}% below 70% target", score.overall * 100.0),
        });
    }

    priorities.sort_by(|a, b| {
        b.urgency
            .partial_cmp(&a.urgency)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    Ok(priorities)
}

/// Decide: select actions from priorities, capped by `max_concurrent_actions`.
pub fn decide(priorities: &[Priority], config: &OodaConfig) -> SimardResult<Vec<PlannedAction>> {
    let limit = config.max_concurrent_actions as usize;
    let mut actions = Vec::with_capacity(limit);
    for priority in priorities {
        if actions.len() >= limit {
            break;
        }
        if priority.urgency < f64::EPSILON {
            continue;
        }
        let kind = match priority.goal_id.as_str() {
            "__memory__" => ActionKind::ConsolidateMemory,
            "__improvement__" => ActionKind::RunImprovement,
            _ => ActionKind::AdvanceGoal,
        };
        actions.push(PlannedAction {
            kind,
            goal_id: if priority.goal_id.starts_with("__") {
                None
            } else {
                Some(priority.goal_id.clone())
            },
            description: priority.reason.clone(),
        });
    }
    Ok(actions)
}

/// Act: dispatch actions. Failures are per-action, not cycle-wide (Pillar 11).
///
/// Delegates to [`crate::ooda_actions::dispatch_actions`] which calls the
/// real subsystems (gym bridge, supervisor, skill builder, etc.).
/// Takes `&mut OodaBridges` so that the optional session can be used for
/// `run_turn` calls during `AdvanceGoal` actions.
pub fn act(
    actions: &[PlannedAction],
    bridges: &mut OodaBridges,
    state: &mut OodaState,
) -> SimardResult<Vec<ActionOutcome>> {
    crate::ooda_actions::dispatch_actions(actions, bridges, state)
}

/// Run one complete OODA cycle: Observe -> Orient -> Decide -> Act -> Curate.
///
/// After dispatching actions, the cycle archives completed goals and promotes
/// the highest-scoring backlog items to fill any freed active slots. This
/// implements the meta-goal of continually seeking the best goals to pursue.
///
/// Takes `&mut OodaBridges` so that the optional session can be used for
/// `run_turn` calls during `AdvanceGoal` dispatch.
pub fn run_ooda_cycle(
    state: &mut OodaState,
    bridges: &mut OodaBridges,
    config: &OodaConfig,
) -> SimardResult<CycleReport> {
    // Only replace board if loaded one is non-empty (cold memory = keep local).
    if let Ok(board) = load_goal_board(&bridges.memory)
        && !board.active.is_empty()
    {
        state.active_goals = board;
    }

    // Seed with default goals if the board is still empty.
    let seeded = crate::goal_curation::seed_default_board(&mut state.active_goals);
    if seeded > 0 {
        eprintln!("[simard] OODA start: seeded {seeded} default goal(s)");
    }

    // Ingest meeting handoff decisions as new goals.
    let handoff_dir = crate::meeting_facilitator::default_handoff_dir();
    match check_meeting_handoffs(&mut state.active_goals, &handoff_dir) {
        Ok(n) if n > 0 => {
            eprintln!(
                "[simard] OODA start: ingested {n} goal/backlog item(s) from meeting handoff"
            );
        }
        Err(e) => {
            eprintln!("[simard] OODA start: meeting handoff check failed: {e}");
        }
        _ => {}
    }

    // --- Observe ---
    state.current_phase = OodaPhase::Observe;
    eprintln!("[simard] OODA cycle: entering Observe phase");
    let observation = observe(state, bridges)?;
    eprintln!("[simard] OODA cycle: Observe complete");

    // --- Orient ---
    state.current_phase = OodaPhase::Orient;
    eprintln!("[simard] OODA cycle: entering Orient phase");
    let priorities = orient(&observation, &state.active_goals)?;
    eprintln!(
        "[simard] OODA cycle: Orient complete ({} priorities)",
        priorities.len()
    );

    // --- Decide ---
    state.current_phase = OodaPhase::Decide;
    eprintln!("[simard] OODA cycle: entering Decide phase");
    let planned_actions = decide(&priorities, config)?;
    eprintln!(
        "[simard] OODA cycle: Decide complete ({} actions)",
        planned_actions.len()
    );

    // --- Act ---
    state.current_phase = OodaPhase::Act;
    eprintln!("[simard] OODA cycle: entering Act phase");
    let act_start = Instant::now();
    let outcomes = act(&planned_actions, bridges, state)?;
    let act_elapsed = act_start.elapsed();
    eprintln!(
        "[simard] OODA cycle: Act complete ({} outcomes, {:.1}s)",
        outcomes.len(),
        act_elapsed.as_secs_f64()
    );

    // --- Review: analyze outcomes and propose improvements ---
    let review_proposals = review_outcomes(&outcomes, act_elapsed);
    if !review_proposals.is_empty() {
        eprintln!(
            "[simard] OODA review: generated {} improvement proposal(s)",
            review_proposals.len()
        );
        // Persist proposals to cognitive memory (best-effort).
        for directive in &review_proposals {
            if let Err(e) = bridges.memory.store_fact(
                &format!("improvement-{}", crate::goals::goal_slug(&directive.title)),
                &format!(
                    "priority={} status={} rationale={}",
                    directive.priority, directive.status, directive.rationale
                ),
                0.8,
                &["improvement".to_string(), "ooda-review".to_string()],
                "ooda-review",
            ) {
                eprintln!("[simard] OODA review: failed to persist proposal: {e}");
            }
        }
        // Convert to ImprovementCycle signals for the next observe() pass.
        let gym_baseline = observation
            .gym_health
            .clone()
            .unwrap_or_else(|| GymSuiteScore {
                suite_id: "ooda-review".to_string(),
                overall: 0.0,
                dimensions: ScoreDimensions::default(),
                scenario_count: 0,
                scenarios_passed: 0,
                pass_rate: 0.0,
                recorded_at_unix_ms: None,
            });
        for _proposal in &review_proposals {
            state.review_improvements.push(ImprovementCycle {
                baseline: gym_baseline.clone(),
                proposed_changes: Vec::new(),
                post_score: None,
                regressions: Vec::new(),
                decision: None,
                final_phase: ImprovementPhase::Eval,
            });
        }
    }

    // --- Curate: archive completed goals, promote from backlog ---
    let archived = crate::goal_curation::archive_completed(&mut state.active_goals);
    if !archived.is_empty() {
        eprintln!(
            "[simard] OODA curate: archived {} completed goal(s): {}",
            archived.len(),
            archived
                .iter()
                .map(|g| g.id.as_str())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }

    // Promote highest-scoring backlog items to fill freed slots.
    promote_from_backlog(&mut state.active_goals);

    // Persist the updated board to cognitive memory (best-effort).
    if let Err(e) = crate::goal_curation::persist_board(&state.active_goals, &bridges.memory) {
        eprintln!("[simard] OODA curate: failed to persist goal board: {e}");
    }

    state.cycle_count += 1;
    Ok(CycleReport {
        cycle_number: state.cycle_count,
        observation,
        priorities,
        planned_actions,
        outcomes,
    })
}

/// Threshold in seconds above which an action is considered slow.
const SLOW_ACTION_THRESHOLD_SECS: u64 = 60;

/// Analyze action outcomes from the Act phase and generate improvement
/// proposals. Three categories:
/// - **fix**: action failed with an error
/// - **optimization**: total act phase took longer than the threshold
/// - **quality**: action succeeded but the detail suggests issues
fn review_outcomes(
    outcomes: &[ActionOutcome],
    act_elapsed: std::time::Duration,
) -> Vec<ImprovementDirective> {
    let mut proposals = Vec::new();

    for outcome in outcomes {
        if !outcome.success {
            // Failed action → propose a fix.
            proposals.push(ImprovementDirective {
                title: format!("Fix failed {} action", outcome.action.kind),
                priority: 2,
                status: GoalStatus::Proposed,
                rationale: format!(
                    "Action '{}' failed: {}. Investigate root cause and add resilience.",
                    outcome.action.description, outcome.detail
                ),
            });
        } else if outcome.detail.to_lowercase().contains("warning")
            || outcome.detail.to_lowercase().contains("partial")
            || outcome.detail.to_lowercase().contains("degraded")
        {
            // Succeeded with quality concerns → propose quality improvement.
            proposals.push(ImprovementDirective {
                title: format!("Improve quality of {} action", outcome.action.kind),
                priority: 3,
                status: GoalStatus::Proposed,
                rationale: format!(
                    "Action '{}' succeeded but detail indicates issues: {}",
                    outcome.action.description, outcome.detail
                ),
            });
        }
    }

    // If the entire act phase was slow, propose an optimization.
    if act_elapsed.as_secs() > SLOW_ACTION_THRESHOLD_SECS {
        proposals.push(ImprovementDirective {
            title: "Optimize slow OODA act phase".to_string(),
            priority: 3,
            status: GoalStatus::Proposed,
            rationale: format!(
                "Act phase took {:.1}s (threshold: {}s). Consider parallelizing actions or reducing scope.",
                act_elapsed.as_secs_f64(),
                SLOW_ACTION_THRESHOLD_SECS
            ),
        });
    }

    proposals
}

/// Promote the highest-scoring backlog items into free active slots.
///
/// Backlog items are sorted by score descending and promoted until the
/// active board is at capacity or the backlog is empty.
fn promote_from_backlog(board: &mut GoalBoard) {
    // Sort backlog by score descending so we promote the best first.
    board.backlog.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    while board.active_slots_remaining() > 0 && !board.backlog.is_empty() {
        let item_id = board.backlog[0].id.clone();
        match crate::goal_curation::promote_to_active(board, &item_id, 3, None) {
            Ok(()) => {
                eprintln!("[simard] OODA curate: promoted backlog item '{item_id}' to active");
            }
            Err(e) => {
                eprintln!("[simard] OODA curate: failed to promote '{item_id}': {e}");
                break;
            }
        }
    }
}

/// Check for unprocessed meeting handoff artifacts in `handoff_dir`, convert
/// their decisions into active goals (or backlog items when at capacity) and
/// action items into backlog items on the board. Marks the handoff processed.
/// Returns the number of goals + backlog items created.
pub fn check_meeting_handoffs(
    board: &mut GoalBoard,
    handoff_dir: &std::path::Path,
) -> SimardResult<u32> {
    use crate::goal_curation::BacklogItem;
    use crate::meeting_facilitator::{load_meeting_handoff, mark_handoff_processed_in_place};

    let mut handoff = match load_meeting_handoff(handoff_dir)? {
        Some(h) if !h.processed => h,
        _ => return Ok(0),
    };

    let mut created = 0u32;

    // Convert decisions to active goals; overflow goes to backlog.
    for (i, decision) in handoff.decisions.iter().enumerate() {
        let goal_id = crate::goals::goal_slug(&decision.description);
        let description = format!("[meeting] {}", decision.description);

        // Deduplicate against existing active goals and backlog.
        if board.active.iter().any(|g| g.id == goal_id)
            || board.backlog.iter().any(|b| b.id == goal_id)
        {
            continue;
        }

        if board.active.len() < crate::goal_curation::MAX_ACTIVE_GOALS {
            // Priority based on position: earlier decisions = higher priority.
            let priority = (i as u32).saturating_add(1).min(5);
            board.active.push(ActiveGoal {
                id: goal_id,
                description,
                priority,
                status: GoalProgress::NotStarted,
                assigned_to: None,
            });
        } else {
            // Board full — route to backlog with score based on position.
            let score = 1.0 - (i as f64 * 0.1).min(0.9);
            board.backlog.push(BacklogItem {
                id: goal_id,
                description,
                source: format!("meeting:{}", handoff.topic),
                score,
            });
        }
        created += 1;
    }

    // Convert action items with priority >= 2 to backlog items.
    for item in &handoff.action_items {
        if item.priority < 2 {
            continue;
        }
        let item_id = crate::goals::goal_slug(&item.description);
        if board.backlog.iter().any(|b| b.id == item_id)
            || board.active.iter().any(|g| g.id == item_id)
        {
            continue;
        }
        // Higher action-item priority → higher backlog score.
        let score = (item.priority as f64 * 0.2).min(1.0);
        board.backlog.push(BacklogItem {
            id: item_id,
            description: format!("[action] {} (owner: {})", item.description, item.owner),
            source: format!("meeting:{}", handoff.topic),
            score,
        });
        created += 1;
    }

    mark_handoff_processed_in_place(handoff_dir, &mut handoff)?;
    Ok(created)
}

/// Summarize a cycle report for logging/persistence.
pub fn summarize_cycle_report(report: &CycleReport) -> String {
    let succeeded = report.outcomes.iter().filter(|o| o.success).count();
    let total = report.outcomes.len();
    let env = &report.observation.environment;
    let dirty = if env.git_status.is_empty() {
        "clean"
    } else {
        "dirty"
    };
    format!(
        "OODA cycle #{}: {} priorities, {} actions ({}/{} succeeded), goals={}, issues={}, tree={}",
        report.cycle_number,
        report.priorities.len(),
        total,
        succeeded,
        total,
        report.observation.goal_statuses.len(),
        env.open_issues.len(),
        dirty,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::goal_curation::GoalBoard;
    use crate::meeting_facilitator::{
        ActionItem, MeetingDecision, MeetingHandoff, load_meeting_handoff, write_meeting_handoff,
    };
    use tempfile::TempDir;

    fn sample_handoff(decisions: Vec<MeetingDecision>) -> MeetingHandoff {
        MeetingHandoff {
            topic: "Sprint planning".to_string(),
            closed_at: "2026-04-03T00:00:00Z".to_string(),
            decisions,
            action_items: Vec::new(),
            open_questions: Vec::new(),
            processed: false,
        }
    }

    fn sample_handoff_with_actions(
        decisions: Vec<MeetingDecision>,
        action_items: Vec<ActionItem>,
    ) -> MeetingHandoff {
        MeetingHandoff {
            topic: "Sprint planning".to_string(),
            closed_at: "2026-04-03T00:00:00Z".to_string(),
            decisions,
            action_items,
            open_questions: Vec::new(),
            processed: false,
        }
    }

    fn sample_decision(desc: &str) -> MeetingDecision {
        MeetingDecision {
            description: desc.to_string(),
            rationale: format!("Rationale for {desc}"),
            participants: vec!["alice".to_string()],
        }
    }

    fn sample_action(desc: &str, owner: &str, priority: u32) -> ActionItem {
        ActionItem {
            description: desc.to_string(),
            owner: owner.to_string(),
            priority,
            due_description: None,
        }
    }

    #[test]
    fn check_meeting_handoffs_converts_decisions_to_goals() {
        let dir = TempDir::new().unwrap();
        let handoff = sample_handoff(vec![
            sample_decision("Migrate to async runtime"),
            sample_decision("Add integration tests"),
        ]);
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        let count = check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(count, 2);
        assert_eq!(board.active.len(), 2);
        assert_eq!(
            board.active[0].description,
            "[meeting] Migrate to async runtime"
        );
        assert_eq!(
            board.active[1].description,
            "[meeting] Add integration tests"
        );
        assert!(matches!(board.active[0].status, GoalProgress::NotStarted));
    }

    #[test]
    fn check_meeting_handoffs_assigns_position_based_priority() {
        let dir = TempDir::new().unwrap();
        let handoff = sample_handoff(vec![
            sample_decision("First decision"),
            sample_decision("Second decision"),
            sample_decision("Third decision"),
        ]);
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(board.active[0].priority, 1);
        assert_eq!(board.active[1].priority, 2);
        assert_eq!(board.active[2].priority, 3);
    }

    #[test]
    fn check_meeting_handoffs_marks_handoff_processed() {
        let dir = TempDir::new().unwrap();
        let handoff = sample_handoff(vec![sample_decision("Ship v2")]);
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        check_meeting_handoffs(&mut board, dir.path()).unwrap();

        let reloaded = load_meeting_handoff(dir.path()).unwrap().unwrap();
        assert!(reloaded.processed);
    }

    #[test]
    fn check_meeting_handoffs_skips_already_processed() {
        let dir = TempDir::new().unwrap();
        let mut handoff = sample_handoff(vec![sample_decision("Already done")]);
        handoff.processed = true;
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        let count = check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(count, 0);
        assert!(board.active.is_empty());
    }

    #[test]
    fn check_meeting_handoffs_no_file_returns_zero() {
        let dir = TempDir::new().unwrap();
        let mut board = GoalBoard::new();
        let count = check_meeting_handoffs(&mut board, dir.path()).unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn check_meeting_handoffs_overflow_goes_to_backlog() {
        let dir = TempDir::new().unwrap();
        // 7 decisions: 5 fit active, 2 overflow to backlog.
        let decisions: Vec<MeetingDecision> = (1..=7)
            .map(|i| sample_decision(&format!("Goal {i}")))
            .collect();
        write_meeting_handoff(dir.path(), &sample_handoff(decisions)).unwrap();

        let mut board = GoalBoard::new();
        let count = check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(count, 7);
        assert_eq!(board.active.len(), crate::goal_curation::MAX_ACTIVE_GOALS);
        assert_eq!(board.backlog.len(), 2);
        assert!(board.backlog[0].description.starts_with("[meeting]"));
        assert_eq!(board.backlog[0].source, "meeting:Sprint planning");
    }

    #[test]
    fn check_meeting_handoffs_skips_duplicate_goal_ids() {
        let dir = TempDir::new().unwrap();
        let handoff = sample_handoff(vec![
            sample_decision("Ship v2"),
            sample_decision("Ship v2"), // duplicate
        ]);
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(board.active.len(), 1);
    }

    #[test]
    fn check_meeting_handoffs_converts_action_items_to_backlog() {
        let dir = TempDir::new().unwrap();
        let handoff = sample_handoff_with_actions(
            vec![sample_decision("Main decision")],
            vec![
                sample_action("Write docs", "alice", 3), // priority >= 2 → backlog
                sample_action("Quick fix", "bob", 1),    // priority < 2 → skipped
                sample_action("Add metrics", "carol", 2), // priority >= 2 → backlog
            ],
        );
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let mut board = GoalBoard::new();
        let count = check_meeting_handoffs(&mut board, dir.path()).unwrap();

        assert_eq!(count, 3); // 1 decision + 2 qualifying action items
        assert_eq!(board.active.len(), 1);
        assert_eq!(board.backlog.len(), 2);
        assert!(
            board.backlog[0]
                .description
                .contains("[action] Write docs (owner: alice)")
        );
        assert!(
            board.backlog[1]
                .description
                .contains("[action] Add metrics (owner: carol)")
        );
        assert_eq!(board.backlog[0].source, "meeting:Sprint planning");
    }

    // -----------------------------------------------------------------------
    // Tests for collect_pending_improvements
    // -----------------------------------------------------------------------

    fn make_gym_score(overall: f64, factual_accuracy: f64) -> GymSuiteScore {
        use crate::gym_bridge::ScoreDimensions;
        GymSuiteScore {
            suite_id: "progressive".to_string(),
            overall,
            dimensions: ScoreDimensions {
                factual_accuracy,
                specificity: 0.8,
                temporal_awareness: 0.7,
                source_attribution: 0.6,
                confidence_calibration: 0.5,
            },
            scenario_count: 5,
            scenarios_passed: 4,
            pass_rate: 0.8,
            recorded_at_unix_ms: None,
        }
    }

    #[test]
    fn collect_pending_improvements_empty_when_no_signals() {
        let dir = TempDir::new().unwrap();
        // Isolate from any leftover handoff files in the default directory.
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let mut state = OodaState::new(GoalBoard::new());
        let current = Some(make_gym_score(0.8, 0.9));
        let result = collect_pending_improvements(&mut state, &current);
        // (Handoff signals may appear due to env var races in parallel tests.)
        let has_regression = result.iter().any(|c| !c.regressions.is_empty());
        assert!(!has_regression, "no signals should yield no regressions");

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    #[test]
    fn collect_pending_improvements_detects_gym_regression() {
        let dir = TempDir::new().unwrap();
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let baseline = make_gym_score(0.9, 0.95);
        let current_score = make_gym_score(0.7, 0.70); // factual_accuracy dropped 0.25

        let mut state = OodaState::new(GoalBoard::new());
        state.last_observation = Some(Observation {
            goal_statuses: Vec::new(),
            gym_health: Some(baseline.clone()),
            memory_stats: CognitiveStatistics::default(),
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        });

        let result = collect_pending_improvements(&mut state, &Some(current_score.clone()));

        assert_eq!(
            result.len(),
            1,
            "regression should produce exactly one improvement signal"
        );
        let cycle = &result[0];
        assert_eq!(cycle.baseline.overall, 0.9);
        assert!(cycle.post_score.is_some());
        assert!(!cycle.regressions.is_empty());
        assert!(cycle.decision.is_none());
        assert_eq!(cycle.final_phase, ImprovementPhase::Eval);

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    #[test]
    fn collect_pending_improvements_no_regression_when_scores_stable() {
        let dir = TempDir::new().unwrap();
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let baseline = make_gym_score(0.8, 0.85);
        let current_score = make_gym_score(0.8, 0.85);

        let mut state = OodaState::new(GoalBoard::new());
        state.last_observation = Some(Observation {
            goal_statuses: Vec::new(),
            gym_health: Some(baseline),
            memory_stats: CognitiveStatistics::default(),
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        });

        let result = collect_pending_improvements(&mut state, &Some(current_score));
        // Stable scores should not produce gym *regression* signals.
        // (Handoff signals may appear due to env var races in parallel tests.)
        let has_regression = result.iter().any(|c| !c.regressions.is_empty());
        assert!(
            !has_regression,
            "stable scores should not produce gym regression signals"
        );

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    #[test]
    fn collect_pending_improvements_no_crash_when_no_gym_health() {
        let dir = TempDir::new().unwrap();
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let mut state = OodaState::new(GoalBoard::new());
        let result = collect_pending_improvements(&mut state, &None);
        // Should not panic — graceful degradation.
        // (Handoff signals may appear due to env var races in parallel tests.)
        let has_regression = result.iter().any(|c| !c.regressions.is_empty());
        assert!(
            !has_regression,
            "no gym health should not produce regressions"
        );

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    #[test]
    fn collect_pending_improvements_no_crash_when_no_last_observation() {
        let dir = TempDir::new().unwrap();
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let mut state = OodaState::new(GoalBoard::new());
        let current = Some(make_gym_score(0.8, 0.9));
        // No last_observation means no baseline for regression comparison.
        let result = collect_pending_improvements(&mut state, &current);
        // (Handoff signals may appear due to env var races in parallel tests.)
        let has_regression = result.iter().any(|c| !c.regressions.is_empty());
        assert!(
            !has_regression,
            "no last observation should not produce regressions"
        );

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    #[test]
    fn scan_unprocessed_handoffs_returns_true_for_unprocessed() {
        let dir = TempDir::new().unwrap();

        let handoff = sample_handoff(vec![sample_decision("Ship v3")]);
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let result = scan_unprocessed_handoffs_in(dir.path()).unwrap();
        assert!(result, "unprocessed handoff should return true");
    }

    #[test]
    fn scan_unprocessed_handoffs_returns_false_when_processed() {
        let dir = TempDir::new().unwrap();

        let mut handoff = sample_handoff(vec![sample_decision("Done")]);
        handoff.processed = true;
        write_meeting_handoff(dir.path(), &handoff).unwrap();

        let result = scan_unprocessed_handoffs_in(dir.path()).unwrap();
        assert!(!result, "processed handoff should return false");
    }

    #[test]
    fn scan_unprocessed_handoffs_returns_false_when_no_file() {
        let dir = TempDir::new().unwrap();

        let result = scan_unprocessed_handoffs_in(dir.path()).unwrap();
        assert!(!result, "no handoff file should return false");
    }

    // --- OodaPhase Display ---

    #[test]
    fn ooda_phase_display_all_variants() {
        assert_eq!(OodaPhase::Observe.to_string(), "observe");
        assert_eq!(OodaPhase::Orient.to_string(), "orient");
        assert_eq!(OodaPhase::Decide.to_string(), "decide");
        assert_eq!(OodaPhase::Act.to_string(), "act");
    }

    #[test]
    fn ooda_phase_equality() {
        assert_eq!(OodaPhase::Observe, OodaPhase::Observe);
        assert_ne!(OodaPhase::Observe, OodaPhase::Orient);
    }

    #[test]
    fn ooda_phase_clone() {
        let phase = OodaPhase::Decide;
        let cloned = phase;
        assert_eq!(phase, cloned);
    }

    // --- OodaState ---

    #[test]
    fn ooda_state_new_defaults() {
        let state = OodaState::new(GoalBoard::new());
        assert_eq!(state.current_phase, OodaPhase::Observe);
        assert_eq!(state.cycle_count, 0);
        assert!(state.last_observation.is_none());
        assert!(state.review_improvements.is_empty());
        assert!(state.active_goals.active.is_empty());
    }

    #[test]
    fn ooda_state_new_with_goals() {
        let mut board = GoalBoard::new();
        board.active.push(ActiveGoal {
            id: "goal-1".to_string(),
            description: "Test goal".to_string(),
            priority: 1,
            status: GoalProgress::NotStarted,
            assigned_to: None,
        });
        let state = OodaState::new(board);
        assert_eq!(state.active_goals.active.len(), 1);
    }

    // --- GoalSnapshot ---

    #[test]
    fn goal_snapshot_from_active_goal() {
        let goal = ActiveGoal {
            id: "g-1".to_string(),
            description: "Build widget".to_string(),
            priority: 2,
            status: GoalProgress::InProgress { percent: 50 },
            assigned_to: Some("engineer".to_string()),
        };
        let snapshot = GoalSnapshot::from(&goal);
        assert_eq!(snapshot.id, "g-1");
        assert_eq!(snapshot.description, "Build widget");
        assert!(matches!(
            snapshot.progress,
            GoalProgress::InProgress { percent: 50 }
        ));
    }

    #[test]
    fn goal_snapshot_from_blocked_goal() {
        let goal = ActiveGoal {
            id: "g-blocked".to_string(),
            description: "Blocked task".to_string(),
            priority: 1,
            status: GoalProgress::Blocked("dependency missing".to_string()),
            assigned_to: None,
        };
        let snapshot = GoalSnapshot::from(&goal);
        assert!(matches!(snapshot.progress, GoalProgress::Blocked(_)));
    }

    // --- EnvironmentSnapshot ---

    #[test]
    fn environment_snapshot_default() {
        let env = EnvironmentSnapshot::default();
        assert!(env.git_status.is_empty());
        assert!(env.open_issues.is_empty());
        assert!(env.recent_commits.is_empty());
    }

    // --- ActionKind Display ---

    #[test]
    fn action_kind_display_all_variants() {
        assert_eq!(ActionKind::AdvanceGoal.to_string(), "advance-goal");
        assert_eq!(ActionKind::RunImprovement.to_string(), "run-improvement");
        assert_eq!(
            ActionKind::ConsolidateMemory.to_string(),
            "consolidate-memory"
        );
        assert_eq!(ActionKind::ResearchQuery.to_string(), "research-query");
        assert_eq!(ActionKind::RunGymEval.to_string(), "run-gym-eval");
        assert_eq!(ActionKind::BuildSkill.to_string(), "build-skill");
        assert_eq!(ActionKind::LaunchSession.to_string(), "launch-session");
    }

    #[test]
    fn action_kind_equality() {
        assert_eq!(ActionKind::AdvanceGoal, ActionKind::AdvanceGoal);
        assert_ne!(ActionKind::AdvanceGoal, ActionKind::RunImprovement);
    }

    // --- OodaConfig ---

    #[test]
    fn ooda_config_default_values() {
        let config = OodaConfig::default();
        assert_eq!(config.max_concurrent_actions, 3);
        assert!((config.improvement_threshold - 0.02).abs() < f64::EPSILON);
        assert_eq!(config.gym_suite_id, "progressive");
    }

    // --- orient ---

    fn make_board_with_goals(goals: Vec<ActiveGoal>) -> GoalBoard {
        let mut board = GoalBoard::new();
        board.active = goals;
        board
    }

    fn make_observation(env: EnvironmentSnapshot) -> Observation {
        Observation {
            goal_statuses: Vec::new(),
            gym_health: None,
            memory_stats: CognitiveStatistics::default(),
            pending_improvements: Vec::new(),
            environment: env,
        }
    }

    #[test]
    fn orient_blocked_goals_have_highest_urgency() {
        let goals = vec![
            ActiveGoal {
                id: "blocked".to_string(),
                description: "Blocked".to_string(),
                priority: 1,
                status: GoalProgress::Blocked("dependency".to_string()),
                assigned_to: None,
            },
            ActiveGoal {
                id: "not-started".to_string(),
                description: "Not started".to_string(),
                priority: 1,
                status: GoalProgress::NotStarted,
                assigned_to: None,
            },
        ];
        let board = make_board_with_goals(goals);
        let obs = make_observation(EnvironmentSnapshot::default());
        let priorities = orient(&obs, &board).unwrap();
        assert_eq!(priorities[0].goal_id, "blocked");
        assert!(priorities[0].urgency > priorities[1].urgency);
    }

    #[test]
    fn orient_completed_goals_have_zero_urgency() {
        let goals = vec![ActiveGoal {
            id: "done".to_string(),
            description: "Done".to_string(),
            priority: 1,
            status: GoalProgress::Completed,
            assigned_to: None,
        }];
        let board = make_board_with_goals(goals);
        let obs = make_observation(EnvironmentSnapshot::default());
        let priorities = orient(&obs, &board).unwrap();
        assert!(
            priorities[0].urgency < f64::EPSILON,
            "completed goals should have zero urgency"
        );
    }

    #[test]
    fn orient_not_started_higher_urgency_than_in_progress() {
        let goals = vec![
            ActiveGoal {
                id: "new".to_string(),
                description: "New".to_string(),
                priority: 1,
                status: GoalProgress::NotStarted,
                assigned_to: None,
            },
            ActiveGoal {
                id: "wip".to_string(),
                description: "WIP".to_string(),
                priority: 1,
                status: GoalProgress::InProgress { percent: 50 },
                assigned_to: None,
            },
        ];
        let board = make_board_with_goals(goals);
        let obs = make_observation(EnvironmentSnapshot::default());
        let priorities = orient(&obs, &board).unwrap();
        let new_prio = priorities.iter().find(|p| p.goal_id == "new").unwrap();
        let wip_prio = priorities.iter().find(|p| p.goal_id == "wip").unwrap();
        assert!(new_prio.urgency > wip_prio.urgency);
    }

    #[test]
    fn orient_in_progress_urgency_decreases_with_percent() {
        let goals = vec![
            ActiveGoal {
                id: "early".to_string(),
                description: "Early".to_string(),
                priority: 1,
                status: GoalProgress::InProgress { percent: 10 },
                assigned_to: None,
            },
            ActiveGoal {
                id: "late".to_string(),
                description: "Late".to_string(),
                priority: 1,
                status: GoalProgress::InProgress { percent: 90 },
                assigned_to: None,
            },
        ];
        let board = make_board_with_goals(goals);
        let obs = make_observation(EnvironmentSnapshot::default());
        let priorities = orient(&obs, &board).unwrap();
        let early = priorities.iter().find(|p| p.goal_id == "early").unwrap();
        let late = priorities.iter().find(|p| p.goal_id == "late").unwrap();
        assert!(early.urgency > late.urgency);
    }

    #[test]
    fn orient_boosts_urgency_when_goal_mentioned_in_issues() {
        let goals = vec![ActiveGoal {
            id: "auth".to_string(),
            description: "Auth system".to_string(),
            priority: 1,
            status: GoalProgress::InProgress { percent: 50 },
            assigned_to: None,
        }];
        let board = make_board_with_goals(goals.clone());
        let env_with_issue = EnvironmentSnapshot {
            git_status: String::new(),
            open_issues: vec!["Fix auth bug".to_string()],
            recent_commits: Vec::new(),
        };
        let env_without = EnvironmentSnapshot::default();

        let prio_with = orient(&make_observation(env_with_issue), &board).unwrap();
        let prio_without = orient(&make_observation(env_without), &board).unwrap();
        assert!(prio_with[0].urgency > prio_without[0].urgency);
        assert!(prio_with[0].reason.contains("open issue"));
    }

    #[test]
    fn orient_boosts_in_progress_when_dirty_tree() {
        let goals = vec![ActiveGoal {
            id: "wip".to_string(),
            description: "WIP".to_string(),
            priority: 1,
            status: GoalProgress::InProgress { percent: 50 },
            assigned_to: None,
        }];
        let board = make_board_with_goals(goals);
        let env_dirty = EnvironmentSnapshot {
            git_status: "M src/main.rs".to_string(),
            open_issues: Vec::new(),
            recent_commits: Vec::new(),
        };
        let env_clean = EnvironmentSnapshot::default();
        let prio_dirty = orient(&make_observation(env_dirty), &board).unwrap();
        let prio_clean = orient(&make_observation(env_clean), &board).unwrap();
        assert!(prio_dirty[0].urgency > prio_clean[0].urgency);
        assert!(prio_dirty[0].reason.contains("dirty"));
    }

    #[test]
    fn orient_adds_memory_consolidation_when_episodic_exceeds_100() {
        let goals = vec![ActiveGoal {
            id: "g1".to_string(),
            description: "Goal".to_string(),
            priority: 1,
            status: GoalProgress::NotStarted,
            assigned_to: None,
        }];
        let board = make_board_with_goals(goals);
        let obs = Observation {
            goal_statuses: Vec::new(),
            gym_health: None,
            memory_stats: CognitiveStatistics {
                episodic_count: 101,
                ..Default::default()
            },
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        };
        let priorities = orient(&obs, &board).unwrap();
        assert!(
            priorities.iter().any(|p| p.goal_id == "__memory__"),
            "should add memory consolidation priority"
        );
    }

    #[test]
    fn orient_no_memory_consolidation_when_episodic_at_100() {
        let board = make_board_with_goals(vec![]);
        let obs = Observation {
            goal_statuses: Vec::new(),
            gym_health: None,
            memory_stats: CognitiveStatistics {
                episodic_count: 100,
                ..Default::default()
            },
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        };
        let priorities = orient(&obs, &board).unwrap();
        assert!(
            !priorities.iter().any(|p| p.goal_id == "__memory__"),
            "should not add memory priority at exactly 100"
        );
    }

    #[test]
    fn orient_adds_improvement_priority_when_gym_below_70() {
        let board = make_board_with_goals(vec![]);
        let obs = Observation {
            goal_statuses: Vec::new(),
            gym_health: Some(make_gym_score(0.5, 0.6)),
            memory_stats: CognitiveStatistics::default(),
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        };
        let priorities = orient(&obs, &board).unwrap();
        assert!(
            priorities.iter().any(|p| p.goal_id == "__improvement__"),
            "should add improvement priority when gym < 70%"
        );
    }

    #[test]
    fn orient_no_improvement_priority_when_gym_above_70() {
        let board = make_board_with_goals(vec![]);
        let obs = Observation {
            goal_statuses: Vec::new(),
            gym_health: Some(make_gym_score(0.8, 0.9)),
            memory_stats: CognitiveStatistics::default(),
            pending_improvements: Vec::new(),
            environment: EnvironmentSnapshot::default(),
        };
        let priorities = orient(&obs, &board).unwrap();
        assert!(
            !priorities.iter().any(|p| p.goal_id == "__improvement__"),
            "should not add improvement priority when gym >= 70%"
        );
    }

    #[test]
    fn orient_priorities_sorted_by_urgency_descending() {
        let goals = vec![
            ActiveGoal {
                id: "low".to_string(),
                description: "Low".to_string(),
                priority: 1,
                status: GoalProgress::Completed,
                assigned_to: None,
            },
            ActiveGoal {
                id: "high".to_string(),
                description: "High".to_string(),
                priority: 1,
                status: GoalProgress::Blocked("x".to_string()),
                assigned_to: None,
            },
            ActiveGoal {
                id: "mid".to_string(),
                description: "Mid".to_string(),
                priority: 1,
                status: GoalProgress::NotStarted,
                assigned_to: None,
            },
        ];
        let board = make_board_with_goals(goals);
        let obs = make_observation(EnvironmentSnapshot::default());
        let priorities = orient(&obs, &board).unwrap();
        for i in 0..priorities.len() - 1 {
            assert!(priorities[i].urgency >= priorities[i + 1].urgency);
        }
    }

    // --- decide ---

    #[test]
    fn decide_respects_max_concurrent_actions() {
        let priorities = vec![
            Priority {
                goal_id: "g1".to_string(),
                urgency: 0.9,
                reason: "a".to_string(),
            },
            Priority {
                goal_id: "g2".to_string(),
                urgency: 0.8,
                reason: "b".to_string(),
            },
            Priority {
                goal_id: "g3".to_string(),
                urgency: 0.7,
                reason: "c".to_string(),
            },
            Priority {
                goal_id: "g4".to_string(),
                urgency: 0.6,
                reason: "d".to_string(),
            },
        ];
        let config = OodaConfig {
            max_concurrent_actions: 2,
            ..Default::default()
        };
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions.len(), 2);
    }

    #[test]
    fn decide_skips_zero_urgency_priorities() {
        let priorities = vec![
            Priority {
                goal_id: "g1".to_string(),
                urgency: 0.5,
                reason: "a".to_string(),
            },
            Priority {
                goal_id: "g2".to_string(),
                urgency: 0.0,
                reason: "done".to_string(),
            },
        ];
        let config = OodaConfig::default();
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions.len(), 1);
        assert_eq!(actions[0].goal_id, Some("g1".to_string()));
    }

    #[test]
    fn decide_maps_memory_priority_to_consolidate_action() {
        let priorities = vec![Priority {
            goal_id: "__memory__".to_string(),
            urgency: 0.5,
            reason: "too many memories".to_string(),
        }];
        let config = OodaConfig::default();
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions.len(), 1);
        assert_eq!(actions[0].kind, ActionKind::ConsolidateMemory);
        assert!(actions[0].goal_id.is_none());
    }

    #[test]
    fn decide_maps_improvement_priority_to_run_improvement() {
        let priorities = vec![Priority {
            goal_id: "__improvement__".to_string(),
            urgency: 0.7,
            reason: "gym below target".to_string(),
        }];
        let config = OodaConfig::default();
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions[0].kind, ActionKind::RunImprovement);
        assert!(actions[0].goal_id.is_none());
    }

    #[test]
    fn decide_maps_regular_goal_to_advance_goal() {
        let priorities = vec![Priority {
            goal_id: "ship-v1".to_string(),
            urgency: 0.9,
            reason: "high priority".to_string(),
        }];
        let config = OodaConfig::default();
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions[0].kind, ActionKind::AdvanceGoal);
        assert_eq!(actions[0].goal_id, Some("ship-v1".to_string()));
    }

    #[test]
    fn decide_empty_priorities_returns_empty() {
        let config = OodaConfig::default();
        let actions = decide(&[], &config).unwrap();
        assert!(actions.is_empty());
    }

    #[test]
    fn decide_preserves_reason_as_description() {
        let priorities = vec![Priority {
            goal_id: "g1".to_string(),
            urgency: 0.5,
            reason: "important task".to_string(),
        }];
        let config = OodaConfig::default();
        let actions = decide(&priorities, &config).unwrap();
        assert_eq!(actions[0].description, "important task");
    }

    // --- review_outcomes ---

    #[test]
    fn review_outcomes_generates_fix_for_failed_action() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::AdvanceGoal,
                goal_id: Some("g1".to_string()),
                description: "advance g1".to_string(),
            },
            success: false,
            detail: "timeout during execution".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(5));
        assert_eq!(proposals.len(), 1);
        assert!(proposals[0].title.contains("Fix failed"));
        assert_eq!(proposals[0].priority, 2);
        assert_eq!(proposals[0].status, GoalStatus::Proposed);
    }

    #[test]
    fn review_outcomes_generates_quality_for_warning() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::RunImprovement,
                goal_id: None,
                description: "run improvement".to_string(),
            },
            success: true,
            detail: "completed with warning: unstable test".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(5));
        assert_eq!(proposals.len(), 1);
        assert!(proposals[0].title.contains("Improve quality"));
        assert_eq!(proposals[0].priority, 3);
    }

    #[test]
    fn review_outcomes_generates_quality_for_partial() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::AdvanceGoal,
                goal_id: Some("g1".to_string()),
                description: "partial work".to_string(),
            },
            success: true,
            detail: "partial success: only 2 of 5 steps completed".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(5));
        assert_eq!(proposals.len(), 1);
        assert!(proposals[0].title.contains("quality"));
    }

    #[test]
    fn review_outcomes_generates_quality_for_degraded() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::ConsolidateMemory,
                goal_id: None,
                description: "memory work".to_string(),
            },
            success: true,
            detail: "degraded performance observed".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(5));
        assert_eq!(proposals.len(), 1);
    }

    #[test]
    fn review_outcomes_generates_optimization_for_slow_phase() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::AdvanceGoal,
                goal_id: Some("g1".to_string()),
                description: "normal".to_string(),
            },
            success: true,
            detail: "done".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(120));
        assert_eq!(proposals.len(), 1);
        assert!(proposals[0].title.contains("Optimize slow"));
    }

    #[test]
    fn review_outcomes_no_proposals_for_clean_fast_success() {
        let outcomes = vec![ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::AdvanceGoal,
                goal_id: Some("g1".to_string()),
                description: "advance".to_string(),
            },
            success: true,
            detail: "completed successfully".to_string(),
        }];
        let proposals = review_outcomes(&outcomes, std::time::Duration::from_secs(10));
        assert!(proposals.is_empty());
    }

    #[test]
    fn review_outcomes_empty_outcomes() {
        let proposals = review_outcomes(&[], std::time::Duration::from_secs(5));
        assert!(proposals.is_empty());
    }

    // --- summarize_cycle_report ---

    #[test]
    fn summarize_cycle_report_format() {
        let report = CycleReport {
            cycle_number: 1,
            observation: Observation {
                goal_statuses: vec![GoalSnapshot {
                    id: "g1".to_string(),
                    description: "Goal 1".to_string(),
                    progress: GoalProgress::NotStarted,
                }],
                gym_health: None,
                memory_stats: CognitiveStatistics::default(),
                pending_improvements: Vec::new(),
                environment: EnvironmentSnapshot::default(),
            },
            priorities: vec![Priority {
                goal_id: "g1".to_string(),
                urgency: 0.8,
                reason: "not started".to_string(),
            }],
            planned_actions: vec![PlannedAction {
                kind: ActionKind::AdvanceGoal,
                goal_id: Some("g1".to_string()),
                description: "advance g1".to_string(),
            }],
            outcomes: vec![ActionOutcome {
                action: PlannedAction {
                    kind: ActionKind::AdvanceGoal,
                    goal_id: Some("g1".to_string()),
                    description: "advance g1".to_string(),
                },
                success: true,
                detail: "done".to_string(),
            }],
        };
        let summary = summarize_cycle_report(&report);
        assert!(summary.contains("cycle #1"));
        assert!(summary.contains("1 priorities"));
        assert!(summary.contains("1/1 succeeded"));
        assert!(summary.contains("goals=1"));
        assert!(summary.contains("tree=clean"));
    }

    #[test]
    fn summarize_cycle_report_dirty_tree() {
        let report = CycleReport {
            cycle_number: 2,
            observation: Observation {
                goal_statuses: Vec::new(),
                gym_health: None,
                memory_stats: CognitiveStatistics::default(),
                pending_improvements: Vec::new(),
                environment: EnvironmentSnapshot {
                    git_status: "M file.rs".to_string(),
                    open_issues: vec!["issue 1".to_string()],
                    recent_commits: Vec::new(),
                },
            },
            priorities: Vec::new(),
            planned_actions: Vec::new(),
            outcomes: Vec::new(),
        };
        let summary = summarize_cycle_report(&report);
        assert!(summary.contains("tree=dirty"));
        assert!(summary.contains("issues=1"));
    }

    #[test]
    fn summarize_cycle_report_mixed_outcomes() {
        let report = CycleReport {
            cycle_number: 3,
            observation: Observation {
                goal_statuses: Vec::new(),
                gym_health: None,
                memory_stats: CognitiveStatistics::default(),
                pending_improvements: Vec::new(),
                environment: EnvironmentSnapshot::default(),
            },
            priorities: Vec::new(),
            planned_actions: Vec::new(),
            outcomes: vec![
                ActionOutcome {
                    action: PlannedAction {
                        kind: ActionKind::AdvanceGoal,
                        goal_id: None,
                        description: "a".to_string(),
                    },
                    success: true,
                    detail: "ok".to_string(),
                },
                ActionOutcome {
                    action: PlannedAction {
                        kind: ActionKind::RunImprovement,
                        goal_id: None,
                        description: "b".to_string(),
                    },
                    success: false,
                    detail: "fail".to_string(),
                },
            ],
        };
        let summary = summarize_cycle_report(&report);
        assert!(summary.contains("1/2 succeeded"));
    }

    // --- promote_from_backlog ---

    #[test]
    fn promote_from_backlog_fills_slots() {
        use crate::goal_curation::BacklogItem;
        let mut board = GoalBoard::new();
        board.backlog.push(BacklogItem {
            id: "item-1".to_string(),
            description: "First".to_string(),
            source: "test".to_string(),
            score: 0.9,
        });
        board.backlog.push(BacklogItem {
            id: "item-2".to_string(),
            description: "Second".to_string(),
            source: "test".to_string(),
            score: 0.5,
        });
        promote_from_backlog(&mut board);
        assert!(board.active.len() <= crate::goal_curation::MAX_ACTIVE_GOALS);
        assert!(!board.active.is_empty());
    }

    #[test]
    fn promote_from_backlog_does_nothing_when_at_capacity() {
        use crate::goal_curation::BacklogItem;
        let mut board = GoalBoard::new();
        for i in 0..crate::goal_curation::MAX_ACTIVE_GOALS {
            board.active.push(ActiveGoal {
                id: format!("g-{i}"),
                description: format!("Goal {i}"),
                priority: 1,
                status: GoalProgress::NotStarted,
                assigned_to: None,
            });
        }
        board.backlog.push(BacklogItem {
            id: "overflow".to_string(),
            description: "Overflow".to_string(),
            source: "test".to_string(),
            score: 0.9,
        });
        promote_from_backlog(&mut board);
        assert_eq!(board.active.len(), crate::goal_curation::MAX_ACTIVE_GOALS);
        assert_eq!(board.backlog.len(), 1, "backlog item should remain");
    }

    #[test]
    fn promote_from_backlog_empty_backlog() {
        let mut board = GoalBoard::new();
        promote_from_backlog(&mut board);
        assert!(board.active.is_empty());
    }

    // --- collect_pending_improvements drains review_improvements ---

    #[test]
    fn collect_pending_improvements_drains_review_improvements() {
        let dir = TempDir::new().unwrap();
        unsafe { std::env::set_var("SIMARD_HANDOFF_DIR", dir.path()) };

        let mut state = OodaState::new(GoalBoard::new());
        state.review_improvements.push(ImprovementCycle {
            baseline: make_gym_score(0.8, 0.9),
            proposed_changes: Vec::new(),
            post_score: None,
            regressions: Vec::new(),
            decision: None,
            final_phase: ImprovementPhase::Eval,
        });
        let result = collect_pending_improvements(&mut state, &None);
        assert!(
            result
                .iter()
                .any(|c| c.final_phase == ImprovementPhase::Eval),
            "should include drained review improvement"
        );
        assert!(
            state.review_improvements.is_empty(),
            "review improvements should be drained"
        );

        unsafe { std::env::remove_var("SIMARD_HANDOFF_DIR") };
    }

    // --- Observation / PlannedAction / CycleReport: struct construction ---

    #[test]
    fn planned_action_construction() {
        let action = PlannedAction {
            kind: ActionKind::BuildSkill,
            goal_id: Some("skill-1".to_string()),
            description: "Build skill".to_string(),
        };
        assert_eq!(action.kind, ActionKind::BuildSkill);
        assert_eq!(action.goal_id.unwrap(), "skill-1");
    }

    #[test]
    fn action_outcome_construction() {
        let outcome = ActionOutcome {
            action: PlannedAction {
                kind: ActionKind::LaunchSession,
                goal_id: None,
                description: "launch".to_string(),
            },
            success: true,
            detail: "session launched".to_string(),
        };
        assert!(outcome.success);
        assert_eq!(outcome.detail, "session launched");
    }
}
