//! Build bespoke skills from procedural memory patterns.
//!
//! When the agent repeatedly uses the same procedures, those patterns can be
//! extracted into standalone skill definitions (markdown files). This module
//! provides the extraction, generation, and installation pipeline.
//!
//! A skill template captures the name, description, steps, and trigger
//! patterns from procedural memory. The generator produces a markdown skill
//! file that can be loaded by Claude Code or similar tools.

use std::path::{Path, PathBuf};

use crate::cognitive_memory::CognitiveMemoryOps;
use crate::error::{SimardError, SimardResult};
use crate::memory_cognitive::CognitiveProcedure;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// A candidate skill extracted from procedural memory.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SkillTemplate {
    /// Skill name derived from the procedure name.
    pub name: String,
    /// Human-readable description of what the skill does.
    pub description: String,
    /// Ordered steps that define the skill.
    pub steps: Vec<String>,
    /// Patterns that should trigger this skill.
    pub trigger_patterns: Vec<String>,
}

// ---------------------------------------------------------------------------
// Extraction
// ---------------------------------------------------------------------------

/// Extract skill candidates from procedural memory.
///
/// Queries the cognitive memory bridge for procedures that have been used
/// at least `min_usage` times. Procedures with fewer uses are considered
/// too infrequent to warrant a dedicated skill.
///
/// Returns templates sorted by usage count (highest first).
pub fn extract_skill_candidates(
    bridge: &dyn CognitiveMemoryOps,
    min_usage: u32,
) -> SimardResult<Vec<SkillTemplate>> {
    // Recall all procedures with a broad query.
    let procedures = bridge.recall_procedure("*", 100)?;

    let mut candidates: Vec<SkillTemplate> = procedures
        .iter()
        .filter(|p| p.usage_count >= min_usage as i64)
        .map(procedure_to_template)
        .collect();

    // Sort by usage count descending (implicit from the procedure data).
    candidates.sort_by_key(|b| std::cmp::Reverse(b.steps.len()));

    Ok(candidates)
}

/// Convert a cognitive procedure into a skill template.
fn procedure_to_template(procedure: &CognitiveProcedure) -> SkillTemplate {
    let description = format!(
        "Skill derived from procedure '{}' (used {} times)",
        procedure.name, procedure.usage_count
    );

    // Derive trigger patterns from the procedure name and prerequisites.
    let mut triggers = vec![procedure.name.clone()];
    for prereq in &procedure.prerequisites {
        triggers.push(prereq.clone());
    }

    SkillTemplate {
        name: slugify(&procedure.name),
        description,
        steps: procedure.steps.clone(),
        trigger_patterns: triggers,
    }
}

/// Convert a name to a kebab-case slug suitable for file names.
fn slugify(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<&str>>()
        .join("-")
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// Generate a markdown skill definition from a template.
///
/// The output format is compatible with Claude Code skill loading:
/// a markdown file with frontmatter-style metadata and step-by-step
/// instructions.
pub fn generate_skill_definition(template: &SkillTemplate) -> String {
    let mut lines = Vec::new();

    lines.push(format!("# {}", template.name));
    lines.push(String::new());
    lines.push(template.description.clone());
    lines.push(String::new());

    // Trigger patterns
    lines.push("## Triggers".to_string());
    lines.push(String::new());
    for pattern in &template.trigger_patterns {
        lines.push(format!("- `{pattern}`"));
    }
    lines.push(String::new());

    // Steps
    lines.push("## Steps".to_string());
    lines.push(String::new());
    for (i, step) in template.steps.iter().enumerate() {
        lines.push(format!("{}. {step}", i + 1));
    }
    lines.push(String::new());

    // Footer
    lines.push("---".to_string());
    lines.push("*Auto-generated by Simard skill builder from procedural memory.*".to_string());

    lines.join("\n")
}

// ---------------------------------------------------------------------------
// Installation
// ---------------------------------------------------------------------------

/// Install a skill by writing its definition to the skills directory.
///
/// Creates the skills directory if it does not exist. Returns the path
/// to the written file.
///
/// Refuses to overwrite an existing file to prevent accidental loss of
/// manually edited skills. If the file exists, returns an error.
pub fn install_skill(template: &SkillTemplate, skills_dir: &Path) -> SimardResult<PathBuf> {
    let file_name = format!("{}.md", template.name);
    let file_path = skills_dir.join(&file_name);

    if file_path.exists() {
        return Err(SimardError::ArtifactIo {
            path: file_path,
            reason: format!(
                "skill file '{}' already exists; remove it first to regenerate",
                file_name
            ),
        });
    }

    // Create directory if needed.
    if !skills_dir.exists() {
        std::fs::create_dir_all(skills_dir).map_err(|e| SimardError::ArtifactIo {
            path: skills_dir.to_path_buf(),
            reason: format!("failed to create skills directory: {e}"),
        })?;
    }

    let content = generate_skill_definition(template);
    std::fs::write(&file_path, &content).map_err(|e| SimardError::ArtifactIo {
        path: file_path.clone(),
        reason: format!("failed to write skill file: {e}"),
    })?;

    Ok(file_path)
}

/// List all installed skill files in a directory.
pub fn list_installed_skills(skills_dir: &Path) -> SimardResult<Vec<PathBuf>> {
    if !skills_dir.exists() {
        return Ok(Vec::new());
    }

    let mut skills = Vec::new();
    let entries = std::fs::read_dir(skills_dir).map_err(|e| SimardError::ArtifactIo {
        path: skills_dir.to_path_buf(),
        reason: format!("failed to read skills directory: {e}"),
    })?;

    for entry in entries {
        let entry = entry.map_err(|e| SimardError::ArtifactIo {
            path: skills_dir.to_path_buf(),
            reason: format!("failed to read directory entry: {e}"),
        })?;
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "md") {
            skills.push(path);
        }
    }

    skills.sort();
    Ok(skills)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugify_converts_spaces_and_special_chars() {
        assert_eq!(slugify("Build & Test"), "build-test");
        assert_eq!(slugify("run_tests_now"), "run-tests-now");
        assert_eq!(slugify("  hello  world  "), "hello-world");
    }

    #[test]
    fn procedure_to_template_maps_fields() {
        let proc = CognitiveProcedure {
            node_id: "proc_1".to_string(),
            name: "cargo build".to_string(),
            steps: vec!["run cargo build".to_string(), "check output".to_string()],
            prerequisites: vec!["rust installed".to_string()],
            usage_count: 5,
        };
        let template = procedure_to_template(&proc);
        assert_eq!(template.name, "cargo-build");
        assert_eq!(template.steps.len(), 2);
        assert!(
            template
                .trigger_patterns
                .contains(&"cargo build".to_string())
        );
        assert!(
            template
                .trigger_patterns
                .contains(&"rust installed".to_string())
        );
    }

    #[test]
    fn generate_skill_definition_includes_all_sections() {
        let template = SkillTemplate {
            name: "test-skill".to_string(),
            description: "A test skill".to_string(),
            steps: vec!["step one".to_string(), "step two".to_string()],
            trigger_patterns: vec!["test".to_string()],
        };
        let md = generate_skill_definition(&template);
        assert!(md.contains("# test-skill"));
        assert!(md.contains("A test skill"));
        assert!(md.contains("## Triggers"));
        assert!(md.contains("- `test`"));
        assert!(md.contains("## Steps"));
        assert!(md.contains("1. step one"));
        assert!(md.contains("2. step two"));
        assert!(md.contains("Auto-generated"));
    }

    #[test]
    fn install_skill_creates_file() {
        let dir = std::env::temp_dir().join("simard-test-skills-install");
        let _ = std::fs::remove_dir_all(&dir);

        let template = SkillTemplate {
            name: "test-install".to_string(),
            description: "Install test".to_string(),
            steps: vec!["do thing".to_string()],
            trigger_patterns: vec!["test".to_string()],
        };

        let path = install_skill(&template, &dir).unwrap();
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("# test-install"));

        // Second install should fail (no overwrite).
        let err = install_skill(&template, &dir).unwrap_err();
        assert!(err.to_string().contains("already exists"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn list_installed_skills_finds_md_files() {
        let dir = std::env::temp_dir().join("simard-test-skills-list");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        std::fs::write(dir.join("skill-a.md"), "# A").unwrap();
        std::fs::write(dir.join("skill-b.md"), "# B").unwrap();
        std::fs::write(dir.join("not-a-skill.txt"), "nope").unwrap();

        let skills = list_installed_skills(&dir).unwrap();
        assert_eq!(skills.len(), 2);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn list_installed_skills_empty_dir() {
        let dir = std::env::temp_dir().join("simard-test-skills-empty");
        let _ = std::fs::remove_dir_all(&dir);
        let skills = list_installed_skills(&dir).unwrap();
        assert!(skills.is_empty());
    }
}
