//! Auto-split BENCHMARK_SCENARIOS data — chunk 4 of 5.

use crate::runtime::RuntimeTopology;
use super::super::types::{BenchmarkClass, BenchmarkScenario};

pub(super) static SCENARIOS: [BenchmarkScenario; 31] = [
    BenchmarkScenario {
        id: "refactor-error-type-hierarchy-multiprocess-rusty-clawd",
        title: "Error type hierarchy refactoring on multi-process rusty-clawd",
        description: "Restructure error types to improve ergonomics and reduce boilerplate through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Analyze the error type hierarchy in the Simard codebase. Cover: (1) map the current SimardError variants and their usage frequency, (2) identify variants that are overly broad or overly narrow, (3) propose a restructured error hierarchy that groups related variants into sub-enums or uses thiserror more effectively, (4) show before/after for at least two error handling call sites. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "refactor-module-boundary-distributed-copilot",
        title: "Module boundary restructuring on distributed copilot-sdk",
        description: "Restructure module boundaries to reduce coupling and improve encapsulation through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Analyze module boundaries in the Simard codebase for coupling issues. Cover: (1) identify modules with high fan-in or fan-out (many cross-module imports), (2) find pub items that are only used by one other module (candidates for moving or inlining), (3) propose a restructured module layout that reduces cross-module dependencies, (4) describe the migration steps to restructure without breaking the public API. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "refactor-api-migration-distributed-terminal",
        title: "API migration planning on distributed terminal-shell",
        description: "Plan a backward-compatible API migration from a deprecated interface to a new one through the distributed topology with the terminal-shell base type.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Plan a staged API migration for a public interface in the Simard codebase. Cover: (1) identify a function or trait whose signature should change (e.g., adding a parameter, changing a return type), (2) design a backward-compatible migration with a deprecation period (old API delegates to new), (3) describe the versioned rollout: introduce new API, migrate callers, remove old API, (4) specify how to detect stale callers via compiler warnings or lint rules. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-modeling-pipeline-topology-multiprocess-rusty-clawd",
        title: "Data pipeline topology design on multi-process rusty-clawd",
        description: "Design a data pipeline topology for ETL-style processing of benchmark results through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::DataModeling,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a data pipeline for processing benchmark run results. Cover: (1) define pipeline stages (extract from JSON artifacts, transform/normalize scores, load into a summary store), (2) specify the data contract between each stage (input type, output type, error type), (3) design backpressure and batching strategy for large result sets, (4) describe how pipeline stages would be distributed across processes. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-modeling-stream-validation-distributed-copilot",
        title: "Streaming data validation on distributed copilot-sdk",
        description: "Design a streaming validation layer for incoming data records with schema enforcement and error quarantine through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::DataModeling,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design a streaming data validation pipeline. Cover: (1) define a validation schema for incoming MemoryRecord or EvidenceRecord payloads (required fields, type constraints, value ranges), (2) design a validation stage that emits valid records downstream and quarantines invalid ones with error annotations, (3) specify how schema evolution is handled (adding optional fields, deprecating fields), (4) describe monitoring and alerting for validation failure rates. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-migration-batch-etl-multiprocess-terminal",
        title: "Batch ETL migration on multi-process terminal-shell",
        description: "Design a batch ETL process to migrate historical benchmark data between storage formats through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::DataMigration,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a batch ETL migration for historical benchmark data. Cover: (1) extract phase: enumerate and read existing JSON report artifacts, (2) transform phase: normalize field names, fill defaults for missing fields, compute derived metrics, (3) load phase: write transformed records to a new storage format, (4) verification: checksum-based integrity checks and row-count reconciliation between source and target. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-migration-streaming-backfill-distributed-rusty-clawd",
        title: "Streaming backfill migration on distributed rusty-clawd",
        description: "Design a streaming backfill process to populate a new data store from an existing one without downtime through the distributed topology with the rusty-clawd base type.",
        class: BenchmarkClass::DataMigration,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::Distributed,
        objective: "Design a zero-downtime streaming backfill for migrating data across stores. Cover: (1) dual-write strategy: new writes go to both old and new stores during migration, (2) backfill cursor: track progress through historical records with resumable checkpoints, (3) consistency verification: compare record counts and checksums between stores, (4) cutover procedure: switch reads to the new store and decommission the old one. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    // --- Wave 10: DatabaseSchemaChange / CachingStrategy / FeatureFlagging /
    // RateLimiting / EventSourcing / ChaosEngineering ---
    BenchmarkScenario {
        id: "db-schema-additive-migration-local",
        title: "Database schema change: additive migration on local harness",
        description: "Plan an additive (backward-compatible) schema migration that adds a new optional column and backfills it on the single-process local harness.",
        class: BenchmarkClass::DatabaseSchemaChange,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Plan an additive schema migration. Cover: (1) the forward migration DDL adding a nullable column with a safe default, (2) application-level dual-read/dual-write phase so old and new code can coexist, (3) backfill strategy for existing rows in chunks with progress tracking, (4) the rollback plan and how to detect partial failures. Avoid destructive operations.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "db-schema-destructive-migration-multiprocess-terminal",
        title: "Database schema change: destructive column drop on multi-process terminal-shell",
        description: "Plan a multi-phase destructive schema change that removes a deprecated column without breaking in-flight clients through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::DatabaseSchemaChange,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Plan a destructive schema migration to drop a deprecated column. Cover: (1) expand/contract phasing: stop writing the column, stop reading the column, then drop it in a separate release, (2) per-version compatibility matrix showing which app versions tolerate which schema states, (3) verification queries to prove no live reader/writer remains, (4) rollback considerations and why drops are typically irreversible. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "db-schema-online-index-distributed-copilot",
        title: "Database schema change: online index build on distributed copilot-sdk",
        description: "Design an online index creation strategy that avoids long table locks on a high-traffic table through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::DatabaseSchemaChange,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design an online schema change that adds an index without downtime. Cover: (1) choice of online/concurrent index build (e.g., CREATE INDEX CONCURRENTLY in Postgres or pt-online-schema-change in MySQL), (2) lock-acquisition risk and how to minimize blocking, (3) replica lag monitoring and pause-on-lag policy during the build, (4) verification that the index is valid and being used by the planner. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "cache-aside-strategy-local",
        title: "Caching strategy: cache-aside pattern on local harness",
        description: "Design a cache-aside (lazy-load) caching layer for a read-heavy lookup on the single-process local harness.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a cache-aside read-through cache. Cover: (1) the read path: check cache, on miss load from source-of-truth and populate cache, (2) TTL selection and rationale tying freshness requirements to acceptable staleness, (3) negative-result caching to avoid stampedes on missing keys, (4) thundering-herd mitigation (singleflight/request coalescing) on concurrent misses.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "cache-write-through-multiprocess-rusty-clawd",
        title: "Caching strategy: write-through cache on multi-process rusty-clawd",
        description: "Design a write-through caching layer that keeps cache and primary store synchronously consistent through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a write-through cache. Cover: (1) the write path: synchronous update of cache and source-of-truth in a single logical operation, (2) failure handling when one of cache or source-of-truth fails (compensating actions, retry policy), (3) consistency guarantees offered to readers and edge cases under concurrent writers, (4) trade-off analysis vs write-back and cache-aside for this workload. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "cache-invalidation-distributed-copilot",
        title: "Caching strategy: invalidation policy on distributed copilot-sdk",
        description: "Design a cache-invalidation policy for a multi-region distributed cache with eventual consistency through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design cache invalidation across regions. Cover: (1) invalidation channel (pub/sub topic or change-data-capture stream) carrying invalidation events, (2) keyspace versioning or epoch tagging so stale entries are detectable on read, (3) bounded-staleness SLO and how it is measured, (4) handling partition or subscriber lag without serving indefinitely stale entries. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "feature-flag-percentage-rollout-local",
        title: "Feature flagging: percentage rollout on local harness",
        description: "Design a percentage-based progressive rollout for a new feature flag on the single-process local harness.",
        class: BenchmarkClass::FeatureFlagging,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a percentage-based feature rollout. Cover: (1) deterministic bucketing function (e.g., hash(user_id) mod 100) so a user's bucket is stable across requests, (2) ramp schedule (1% -> 10% -> 50% -> 100%) with health-check gates between steps, (3) telemetry needed to compare flagged-on vs flagged-off cohorts, (4) safe default behavior when the flag service is unreachable.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "feature-flag-kill-switch-multiprocess-terminal",
        title: "Feature flagging: emergency kill switch on multi-process terminal-shell",
        description: "Design an emergency disable switch that can rapidly turn off a misbehaving feature across all instances through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::FeatureFlagging,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design an emergency feature kill switch. Cover: (1) propagation latency budget from operator action to all processes seeing the new flag value, (2) fail-safe default when the flag store is unreachable (e.g., last-known-good cached locally), (3) audit trail for who flipped the switch, when, and why, (4) post-flip verification (metrics that should immediately move) and the procedure for re-enabling. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "feature-flag-cohort-experiment-distributed-copilot",
        title: "Feature flagging: cohort experiment on distributed copilot-sdk",
        description: "Design a cohort-based A/B experiment with stable user bucketing and result analysis through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::FeatureFlagging,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design an A/B cohort experiment behind a flag. Cover: (1) cohort assignment that is stable across sessions and devices for the same user, (2) primary success metric and at least one guardrail metric (e.g., latency, error rate) that can stop the experiment, (3) exposure logging so cohort membership at decision time is recoverable for analysis, (4) statistical stopping rule (sample size or significance threshold) to declare a winner. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "rate-limit-token-bucket-local",
        title: "Rate limiting: token bucket on local harness",
        description: "Design a per-key token-bucket rate limiter for a single-instance API on the single-process local harness.",
        class: BenchmarkClass::RateLimiting,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a token-bucket rate limiter. Cover: (1) bucket parameters (capacity, refill rate) and how to choose them from a target steady-state RPS and acceptable burst, (2) per-key state representation in memory (e.g., last-refill timestamp + token count), (3) the response on rejection (HTTP 429 plus Retry-After header semantics), (4) at least one concrete numeric example: bucket of N tokens, refill R/s, burst behavior over time.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "rate-limit-sliding-window-multiprocess-copilot",
        title: "Rate limiting: sliding window on multi-process copilot-sdk",
        description: "Design a sliding-window rate limiter that smooths bursts across window boundaries through the multi-process topology with the copilot-sdk base type.",
        class: BenchmarkClass::RateLimiting,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a sliding-window rate limiter. Cover: (1) the chosen variant (sliding-log vs sliding-window-counter) and the trade-off in memory vs precision, (2) how the algorithm avoids the boundary-burst problem of fixed windows, (3) per-key state size and eviction policy for inactive keys, (4) the response on rejection including a quota header (e.g., X-RateLimit-Remaining, X-RateLimit-Reset). Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "rate-limit-distributed-quota-distributed-rusty-clawd",
        title: "Rate limiting: distributed quota on distributed rusty-clawd",
        description: "Design a distributed quota system that enforces a global request budget across many instances through the distributed topology with the rusty-clawd base type.",
        class: BenchmarkClass::RateLimiting,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::Distributed,
        objective: "Design a distributed quota enforcer. Cover: (1) coordination model (centralized counter store such as Redis vs lease-based local sub-quotas), (2) consistency vs latency trade-off and the bounded over-allow allowance under network partitions, (3) per-instance fallback policy when the central store is unreachable (fail-open vs fail-closed and why), (4) how cross-region quota is partitioned and rebalanced. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "event-sourcing-store-design-local",
        title: "Event sourcing: event store design on local harness",
        description: "Design an append-only event store schema and event envelope for a small bounded context on the single-process local harness.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design an event store. Cover: (1) the event envelope (event_id, aggregate_id, sequence_number, event_type, payload, occurred_at, schema_version), (2) the append-only storage layout and the unique constraint that enforces per-aggregate ordering, (3) optimistic concurrency on append using expected sequence numbers, (4) at least one example aggregate with two event types and the resulting event log.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "event-sourcing-projection-rebuild-multiprocess-terminal",
        title: "Event sourcing: projection rebuild on multi-process terminal-shell",
        description: "Design a procedure to rebuild a read-model projection from the event log without downtime through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a projection-rebuild process. Cover: (1) build a new projection version side-by-side from the start of the event log while the old version still serves reads, (2) checkpointing strategy so a long rebuild can resume after a crash, (3) catch-up phase that consumes events appended during the rebuild before cutover, (4) atomic cutover that swaps reads to the new projection with a documented rollback path. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "event-sourcing-cross-region-replay-distributed-copilot",
        title: "Event sourcing: cross-region replay on distributed copilot-sdk",
        description: "Design event replay and replication across regions for disaster recovery and read-scaling through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design cross-region event replication. Cover: (1) global sequence ordering vs per-aggregate ordering and which guarantees are preserved across regions, (2) idempotent consumer design so replays do not double-apply effects, (3) handling event-schema evolution during replay (upcasters or versioned handlers), (4) recovery objective (RPO/RTO) and how the replay procedure satisfies it. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "chaos-blast-radius-analysis-local",
        title: "Chaos engineering: blast-radius analysis on local harness",
        description: "Perform a blast-radius analysis for a candidate chaos experiment before any fault is injected on the single-process local harness.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Perform a blast-radius analysis for a proposed chaos experiment. Cover: (1) the steady-state hypothesis (what metric defines normal) and the abort threshold that halts the experiment, (2) the minimum viable scope (single instance, single shard) and the planned escalation if results are clean, (3) explicit list of users, data, and downstream services that could be impacted, (4) the rollback procedure and on-call sign-off requirements before the experiment runs.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "chaos-fault-injection-multiprocess-rusty-clawd",
        title: "Chaos engineering: fault injection plan on multi-process rusty-clawd",
        description: "Design a fault-injection experiment that introduces controlled latency and packet loss between processes through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design a fault-injection experiment. Cover: (1) the specific faults injected (e.g., +200ms latency, 1% packet loss, dependency error responses) and the tooling used, (2) the steady-state hypothesis and the failure-mode hypothesis being tested, (3) blast-radius controls (target subset, time bound, automatic abort signal), (4) the observability needed to attribute observed effects to the injected fault rather than coincidence. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "chaos-game-day-distributed-terminal",
        title: "Chaos engineering: game day exercise on distributed terminal-shell",
        description: "Plan a cross-team game day that exercises a regional outage and validates failover through the distributed topology with the terminal-shell base type.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Plan a game day exercise that simulates a regional failure. Cover: (1) the scenario script (which region is taken offline, how, and for how long), (2) participant roles (incident commander, scribe, operators per service) and the communication channel, (3) success criteria tied to recovery objectives (RPO/RTO) and a measurable abort signal, (4) the post-exercise debrief format that produces concrete action items and a blameless write-up. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    // --- Wave 7: deepen coverage across priority classes (issue #1177) ---
    BenchmarkScenario {
        id: "a11y-focus-trap-modal-local",
        title: "Accessibility: focus trap audit on modal dialogs",
        description: "Audit a modal-dialog component for keyboard focus trapping behavior so screen-reader users cannot tab outside the open modal.",
        class: BenchmarkClass::AccessibilityReview,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Audit a modal dialog implementation. Cover: (1) the focus trap entry behavior (initial focus on the first focusable element or the dialog container), (2) Tab and Shift+Tab cycling within the dialog without escaping to the underlying page, (3) Esc key closure restoring focus to the invoking element, (4) aria-modal=true and role=dialog presence. Report each finding with the exact element selector or attribute path.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "api-design-pagination-cursor-local",
        title: "API design: cursor pagination contract",
        description: "Design a cursor-based pagination contract for a list endpoint, balancing stability under concurrent writes against client simplicity.",
        class: BenchmarkClass::ApiDesign,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design cursor pagination for GET /items. Cover: (1) opaque cursor encoding (base64 of (sort_key, id)) and rationale vs offset pagination, (2) page size limits and default, (3) stability under inserts/deletes during pagination and how clients detect drift, (4) the response envelope (items, next_cursor, has_more) and error semantics for invalid cursors.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "cache-stampede-mitigation-multiprocess-rusty-clawd",
        title: "Caching strategy: stampede mitigation on multi-process rusty-clawd",
        description: "Design stampede mitigation for a high-fan-out cache miss path on the multi-process rusty-clawd backend.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design cache stampede mitigation. Cover: (1) singleflight request coalescing per key, (2) probabilistic early expiration to spread refresh load, (3) jittered TTLs to avoid synchronized expiry, (4) bounded waiter queue and timeout semantics. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "chaos-network-partition-distributed-terminal",
        title: "Chaos engineering: network partition drill on distributed terminal-shell",
        description: "Plan a network partition chaos drill against a distributed deployment using the terminal-shell base type to drive fault injection commands.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Plan a partition drill that splits two regions for 5 minutes. Cover: (1) the injection mechanism (iptables DROP or service mesh fault rule) with exact command, (2) blast radius and pre-flight safety checks, (3) measurable success criteria tied to read-availability and write-rejection rate, (4) abort plan and rollback verification. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 5,
    },
    BenchmarkScenario {
        id: "cicd-cache-key-strategy-local",
        title: "CI/CD: cargo build cache key strategy",
        description: "Design a CI cache key strategy for cargo builds in this repository to balance hit rate against staleness.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design the cache key for a GitHub Actions cargo job in this repo. Cover: (1) the key components (Cargo.lock hash, rustc version, OS, target) and rationale, (2) restore_keys fallback chain for partial hits, (3) the paths cached (~/.cargo/registry, target/) and any exclusions for size, (4) cache eviction strategy or size budget. Reference Cargo.toml and Cargo.lock at the repo root.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "concurrency-arc-mutex-poisoning-local",
        title: "Concurrency analysis: Arc<Mutex> poisoning audit",
        description: "Audit Arc<Mutex<T>> usages in src/ for poisoning handling and lock-hold-across-await patterns.",
        class: BenchmarkClass::ConcurrencyAnalysis,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Scan src/ for Arc<Mutex<T>> and tokio::sync::Mutex usages. Cover: (1) any .lock() result handling and whether PoisonError is propagated or swallowed, (2) any std::sync::Mutex held across .await points (a deadlock hazard), (3) candidate sites where RwLock would reduce contention, (4) at least one cited file:line for each finding category.",
        expected_min_runtime_evidence: 3,
    },
];
