//! Auto-split BENCHMARK_SCENARIOS data — chunk 3 of 5.

use crate::runtime::RuntimeTopology;
use super::super::types::{BenchmarkClass, BenchmarkScenario};

pub(super) static SCENARIOS: [BenchmarkScenario; 31] = [
    BenchmarkScenario {
        id: "security-audit-multiprocess-copilot",
        title: "Security audit on multi-process copilot-sdk",
        description: "Exercise a security-audit benchmark through the multi-process topology with the copilot-sdk base type.",
        class: BenchmarkClass::SecurityAudit,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Audit the runtime and session modules for security-relevant patterns: (1) untrusted input handling, (2) error messages that leak internals, (3) unsafe blocks, (4) privilege boundaries. Confirm multi-process transport is active in the runtime report.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "refactoring-distributed-terminal-shell",
        title: "Refactoring scenario on distributed terminal-shell",
        description: "Exercise a refactoring benchmark through the distributed topology with the terminal-shell base type.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Identify a refactoring opportunity in the gym module (extract helper, reduce duplication, or simplify a match arm). Propose the change and verify that distributed transport appears in the runtime evidence.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "error-handling-multiprocess-rusty-clawd",
        title: "Error handling on multi-process rusty-clawd",
        description: "Exercise an error-handling benchmark through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::ErrorHandling,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Trace the error propagation path from a runtime subsystem through the gym executor. Verify: (1) errors are not silently swallowed, (2) context is preserved across module boundaries, (3) the multi-process transport is reflected in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "config-management-distributed-copilot",
        title: "Config management on distributed copilot-sdk",
        description: "Exercise a config-management benchmark through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::ConfigManagement,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Audit configuration surfaces (environment variables, feature flags, topology parameters) and verify they are documented and validated. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "code-review-multiprocess-terminal-shell",
        title: "Code review on multi-process terminal-shell",
        description: "Exercise a code-review benchmark through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::CodeReview,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Perform a structured code review of the gym executor module. Evaluate: (1) function length and complexity, (2) error handling consistency, (3) naming conventions, (4) separation of concerns. Verify multi-process transport is active in the runtime report.",
        expected_min_runtime_evidence: 4,
    },
    // --- Wave 7: new BenchmarkClass variants (DataMigration, CicdPipeline,
    // DependencyUpgrade, ReleaseManagement). Each class has at least one
    // non-default topology and at least one non-local-harness base_type.
    BenchmarkScenario {
        id: "data-migration-schema-version-bump",
        title: "Data migration schema version bump",
        description: "Plan a backward-compatible schema/data migration between two versions of a persisted record. Scored on whether the analysis names old and new fields, addresses backfill, and identifies a rollback path.",
        class: BenchmarkClass::DataMigration,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Inspect a serializable struct in src/session or src/memory. Propose a schema migration that adds a new optional field while preserving deserialization of existing records. Describe: (1) the old vs. new schema, (2) how existing data is read (default values, serde defaults), (3) a backfill or lazy upgrade strategy, (4) a rollback path if the migration must be reverted.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-migration-multiprocess-rusty-clawd",
        title: "Data migration on multi-process rusty-clawd",
        description: "Exercise a data-migration benchmark through the multi-process topology with the rusty-clawd base type so distributed migration steps and runtime evidence are exercised together.",
        class: BenchmarkClass::DataMigration,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Plan a data migration that must run across multiple processes (e.g., session records persisted by one node and consumed by another). Identify: (1) the schema delta, (2) ordering constraints between writers and readers, (3) compatibility windows during rollout, (4) confirm the multi-process transport is reflected in the runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "data-migration-distributed-copilot",
        title: "Data migration on distributed copilot-sdk",
        description: "Exercise a data-migration benchmark through the distributed topology with the copilot-sdk base type, focusing on coordination of schema upgrades across distributed nodes.",
        class: BenchmarkClass::DataMigration,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Design a phased migration of a stored record format across distributed nodes. Address: (1) versioned read paths, (2) feature-flagged write paths, (3) compatibility window strategy, (4) deprecation timeline. Verify the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-workflow-author",
        title: "Author a GitHub Actions workflow",
        description: "Author a minimal but correct GitHub Actions workflow file for a Rust crate. Scored on whether the workflow names jobs, pins actions to versions, runs cargo fmt/check/test, and uses a sensible matrix or trigger.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Draft a .github/workflows/ci.yml that: (1) triggers on push and pull_request, (2) defines at least one job named build with steps for cargo fmt --check, cargo check --lib, and cargo test --lib, (3) pins actions/checkout and dtolnay/rust-toolchain to specific versions, (4) caches the cargo registry. Describe each section and why it is structured that way.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-multiprocess-copilot",
        title: "CI/CD pipeline review on multi-process copilot-sdk",
        description: "Review and improve a CI/CD pipeline through the multi-process topology with the copilot-sdk base type so workflow analysis happens alongside cross-process runtime evidence.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Inspect the existing GitHub Actions workflows in .github/workflows. Identify: (1) jobs that lack timeouts or concurrency limits, (2) action versions that are unpinned (uses floating tags), (3) opportunities for caching or matrix testing, (4) steps that could be parallelized. Confirm the multi-process transport appears in the runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-debug-failure-rusty-clawd",
        title: "Debug a failing CI/CD pipeline on rusty-clawd",
        description: "Diagnose a failing CI workflow run through the multi-process topology with the rusty-clawd base type. Scored on root-cause identification and remediation.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Given a hypothetical failing workflow run, walk through the diagnostic steps: (1) inspect the failed job and its step logs, (2) classify the failure (flaky test, dependency drift, environment issue, code regression), (3) propose a fix and a re-run strategy, (4) suggest a guard (timeout, retry, cache key change) that prevents recurrence. Confirm the multi-process transport is active in the runtime report.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "dependency-upgrade-major-bump",
        title: "Major-version dependency upgrade analysis",
        description: "Plan a major-version upgrade of a Cargo dependency. Scored on whether the analysis surfaces breaking-change call sites, identifies an upgrade order, and proposes a verification strategy.",
        class: BenchmarkClass::DependencyUpgrade,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Pick a non-trivial dependency from Cargo.toml. Plan a major-version upgrade by: (1) listing changelog/breaking-change categories from the new release, (2) enumerating call sites in the Simard source that would need updating, (3) sequencing the upgrade across dependent crates, (4) describing the cargo check / cargo test verification gates. Output a concrete step-by-step plan.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "dependency-upgrade-multiprocess-copilot",
        title: "Dependency upgrade on multi-process copilot-sdk",
        description: "Exercise a dependency-upgrade benchmark through the multi-process topology with the copilot-sdk base type so upgrade impact is analyzed alongside cross-process runtime behavior.",
        class: BenchmarkClass::DependencyUpgrade,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Analyze how a hypothetical major bump of a transport-related dependency would ripple through the multi-process runtime. Identify: (1) trait or API surface changes, (2) impacted modules under src/runtime, (3) compatibility risk for in-flight sessions, (4) a staged rollout strategy. Confirm the multi-process transport is reflected in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "dependency-upgrade-distributed-rusty-clawd",
        title: "Dependency upgrade on distributed rusty-clawd",
        description: "Exercise a dependency-upgrade benchmark through the distributed topology with the rusty-clawd base type, focusing on coordinated rollout across distributed nodes.",
        class: BenchmarkClass::DependencyUpgrade,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::Distributed,
        objective: "Plan a coordinated dependency upgrade across distributed runtime nodes. Address: (1) wire-format compatibility during partial rollout, (2) feature-flag gating, (3) regression testing matrix, (4) rollback procedure. Verify the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "release-management-changelog-and-tag",
        title: "Release management: changelog, version bump, tag",
        description: "Author a release flow: changelog entry, version bump, and git tag. Scored on whether the plan covers semantic-versioning impact, generates a coherent changelog grouped by type, and proposes a tag/release notes flow.",
        class: BenchmarkClass::ReleaseManagement,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Plan a release for the Simard crate covering: (1) the next semver level (patch/minor/major) and why, (2) Cargo.toml version bump location and downstream crate updates, (3) a CHANGELOG section grouped by Added/Changed/Fixed/Deprecated, (4) the git tag and GitHub release notes template. Output the concrete steps an operator would run.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "release-management-multiprocess-copilot",
        title: "Release management on multi-process copilot-sdk",
        description: "Exercise a release-management benchmark through the multi-process topology with the copilot-sdk base type so release coordination is exercised alongside cross-process runtime evidence.",
        class: BenchmarkClass::ReleaseManagement,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Coordinate a release that touches both the runtime and the operator-facing CLI. Cover: (1) version bump propagation across workspace crates, (2) changelog entries split by audience (operators, integrators), (3) tagging and release-asset publication, (4) post-release verification (smoke run, gym suite). Confirm the multi-process transport is reflected in the runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "release-management-distributed-terminal-shell",
        title: "Release management on distributed terminal-shell",
        description: "Exercise a release-management benchmark through the distributed topology with the terminal-shell base type, focusing on cutover sequencing across distributed nodes.",
        class: BenchmarkClass::ReleaseManagement,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Plan the cutover of a release across distributed runtime nodes. Address: (1) tag and artifact distribution, (2) phased node rollout order, (3) compatibility window with the previous version, (4) rollback and post-release monitoring. Verify the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    // --- Wave 8: AccessibilityReview / InternationalizationReview / IncidentResponse ---
    BenchmarkScenario {
        id: "a11y-aria-audit-local",
        title: "Accessibility review: ARIA and semantic markup audit",
        description: "Audit a sample UI surface for ARIA role correctness, alt text, label association, and screen reader friendliness on the single-process local harness.",
        class: BenchmarkClass::AccessibilityReview,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Audit a UI surface for accessibility. Cover: (1) ARIA roles, states, and properties used (or missing), (2) image alt text and form label associations, (3) screen reader landmark structure, (4) cite at least one specific WCAG 2.1 success criterion (e.g., 1.1.1, 4.1.2). Propose concrete remediations.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "a11y-keyboard-nav-multiprocess-copilot",
        title: "Accessibility review: keyboard navigation on multi-process copilot-sdk",
        description: "Review keyboard navigation, focus order, and visible focus indicators through the multi-process topology with the copilot-sdk base type.",
        class: BenchmarkClass::AccessibilityReview,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Review keyboard navigation across an interactive surface. Cover: (1) tab/shift-tab focus order, (2) visible focus indicator and contrast against adjacent colors, (3) keyboard traps and skip-to-content affordances, (4) WCAG success criteria 2.1.1, 2.4.3, and 2.4.7. Propose remediations and confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "a11y-color-contrast-distributed-terminal",
        title: "Accessibility review: color contrast on distributed terminal-shell",
        description: "Audit color contrast ratios and non-color affordances across themes through the distributed topology with the terminal-shell base type.",
        class: BenchmarkClass::AccessibilityReview,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Audit color usage for accessibility. Cover: (1) computed contrast ratios for foreground/background pairs against WCAG AA (4.5:1 normal, 3:1 large) and AAA targets, (2) non-color affordances for status (icons, text), (3) high-contrast/dark theme parity, (4) cite WCAG 1.4.3 and 1.4.11. Propose remediations and confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "i18n-string-extraction-local",
        title: "Internationalization review: hardcoded string extraction",
        description: "Audit a module for hardcoded user-facing strings and propose an extraction-to-message-catalog plan on the single-process local harness.",
        class: BenchmarkClass::InternationalizationReview,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Find user-facing hardcoded strings and design a localization plan. Cover: (1) inventory of hardcoded message literals and their call sites, (2) proposed message catalog format (e.g., ICU MessageFormat, gettext .po, fluent .ftl), (3) translation key naming convention and fallback locale strategy, (4) at least one example before/after for a non-trivial message.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "i18n-locale-routing-multiprocess-rusty-clawd",
        title: "Internationalization review: locale routing on multi-process rusty-clawd",
        description: "Design locale negotiation, fallback, and per-request locale routing through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::InternationalizationReview,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design locale routing for a multi-process service. Cover: (1) locale negotiation from Accept-Language and explicit user preference, (2) language tag normalization (BCP 47, e.g., en-US, pt-BR) and CLDR-backed fallback chain, (3) per-request locale propagation across processes, (4) cache key partitioning by locale. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "i18n-pluralization-rtl-distributed-copilot",
        title: "Internationalization review: pluralization and RTL on distributed copilot-sdk",
        description: "Address plural rules, bidirectional (RTL) layout, and locale-aware number/date/currency formatting through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::InternationalizationReview,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Address advanced i18n concerns. Cover: (1) CLDR plural categories (zero/one/two/few/many/other) and how messages express them, (2) RTL/bidi layout mirroring for languages like Arabic and Hebrew, (3) locale-aware date format, number format, and currency format, (4) at least one concrete example per concern. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "incident-response-postmortem-local",
        title: "Incident response: blameless postmortem authoring",
        description: "Author a blameless postmortem for a simulated production incident on the single-process local harness.",
        class: BenchmarkClass::IncidentResponse,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Author a blameless postmortem. Cover: (1) reconstructed incident timeline (alert paged, mitigation started, resolved), (2) root cause and contributing factors distinguished from triggers, (3) customer impact and severity, (4) prioritized follow-up action items with owners. Avoid blame; focus on systemic prevention.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "incident-response-runbook-multiprocess-terminal",
        title: "Incident response: runbook authoring on multi-process terminal-shell",
        description: "Draft an operational runbook for a recurring failure mode through the multi-process topology with the terminal-shell base type.",
        class: BenchmarkClass::IncidentResponse,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Draft a runbook for an on-call responder. Cover: (1) detection signals and alert query, (2) step-by-step triage and mitigation commands, (3) escalation path and communication template, (4) verification and rollback steps. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "incident-response-pager-rotation-distributed-copilot",
        title: "Incident response: pager rotation and follow-up on distributed copilot-sdk",
        description: "Plan an on-call pager rotation, incident command structure, and follow-up tracking through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::IncidentResponse,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Plan distributed incident response. Cover: (1) on-call pager rotation and handoff procedure, (2) incident commander/scribe/communications role assignments, (3) cross-region escalation and runbook distribution, (4) postmortem follow-up tracking and prevention metrics. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    // --- Wave 9: PerformanceAnalysis / Refactoring / DataModeling / DataMigration topology diversity ---
    BenchmarkScenario {
        id: "perf-hotpath-profiling-multiprocess-copilot",
        title: "Hot-path profiling on multi-process copilot-sdk",
        description: "Profile a request-handling hot path to identify CPU-bound bottlenecks through the multi-process topology with the copilot-sdk base type.",
        class: BenchmarkClass::PerformanceAnalysis,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Profile the request-handling path in the Simard runtime. Cover: (1) identify the top three CPU-consuming functions on the critical path using flame-graph reasoning, (2) measure or estimate the percentage of wall-clock time each consumes, (3) propose targeted optimizations (algorithmic, data-structure, or batching changes) for the top bottleneck, (4) describe how to validate the improvement with before/after benchmarks. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "perf-serialization-overhead-distributed-terminal",
        title: "Serialization overhead analysis on distributed terminal-shell",
        description: "Analyze serialization and deserialization overhead in cross-boundary data exchange through the distributed topology with the terminal-shell base type.",
        class: BenchmarkClass::PerformanceAnalysis,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::Distributed,
        objective: "Analyze serialization overhead in the Simard codebase. Cover: (1) identify all serde round-trip points where data crosses module or process boundaries, (2) estimate payload sizes for representative objects (BenchmarkRunReport, RuntimeHandoffSnapshot), (3) compare current format (JSON) cost against alternatives (bincode, MessagePack) in terms of size and speed, (4) propose a migration path for the highest-cost serialization site. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "perf-lock-contention-multiprocess-rusty-clawd",
        title: "Lock contention analysis on multi-process rusty-clawd",
        description: "Identify lock contention and synchronization bottlenecks in shared-state access through the multi-process topology with the rusty-clawd base type.",
        class: BenchmarkClass::PerformanceAnalysis,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Analyze synchronization primitives in the Simard codebase. Cover: (1) inventory all Mutex, RwLock, and Arc usages and their protected data, (2) identify potential contention points where multiple threads or tasks compete for the same lock, (3) assess whether any locks are held across await points or I/O operations, (4) propose lock-free or reduced-contention alternatives (e.g., sharding, per-thread state, channels). Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "perf-startup-latency-distributed-copilot",
        title: "Startup latency breakdown on distributed copilot-sdk",
        description: "Break down application startup latency into initialization phases and identify optimization targets through the distributed topology with the copilot-sdk base type.",
        class: BenchmarkClass::PerformanceAnalysis,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Analyze startup latency of the Simard runtime. Cover: (1) enumerate initialization phases (config loading, registry population, transport setup, prompt asset loading), (2) estimate or measure the cost of each phase, (3) identify which phases can be parallelized or deferred (lazy initialization), (4) propose a concrete startup optimization plan with expected latency reduction. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "refactor-trait-consolidation-multiprocess-copilot",
        title: "Trait consolidation refactoring on multi-process copilot-sdk",
        description: "Identify related traits that can be consolidated into a unified interface through the multi-process topology with the copilot-sdk base type.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Identify traits in the Simard codebase that share overlapping responsibilities and could be consolidated. Cover: (1) find trait pairs with similar method signatures or shared implementors, (2) analyze whether consolidation would reduce boilerplate without losing semantic clarity, (3) propose a merged trait definition with before/after code, (4) list all implementors that would need updating and the mechanical changes required. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
];
