//! Auto-split BENCHMARK_SCENARIOS data — chunk 5 of 5.

use super::super::types::{BenchmarkClass, BenchmarkScenario};
use crate::runtime::RuntimeTopology;

pub(super) static SCENARIOS: [BenchmarkScenario; 29] = [
    BenchmarkScenario {
        id: "db-schema-add-nullable-column-local",
        title: "Database schema change: add nullable column safely",
        description: "Plan a backward-compatible schema migration that adds a nullable column to a high-traffic table without locking.",
        class: BenchmarkClass::DatabaseSchemaChange,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Plan adding a nullable column `archived_at TIMESTAMPTZ` to a 50M-row table. Cover: (1) the DDL ordering (ADD COLUMN nullable, deploy code that tolerates NULL, optional backfill, optional NOT NULL), (2) why a default value would force a table rewrite on older Postgres versions, (3) backfill batching strategy (batch size, sleep, idempotency), (4) rollback plan if the column needs to be removed.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "debugging-flaky-test-bisect-local",
        title: "Debugging: bisect a flaky test",
        description: "Plan a systematic approach to identify the root cause of a flaky test that fails 1 in 50 runs.",
        class: BenchmarkClass::Debugging,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Plan how to debug a test that passes most of the time but fails ~2% of runs with a timeout. Cover: (1) reproduction strategy (loop with --test-threads, env var sweep, randomized seed capture), (2) hypotheses ordered by likelihood (timing, shared state, ordering, external dependency), (3) instrumentation to add (tracing, captured panic backtrace, RUST_BACKTRACE=full), (4) the verification gate before declaring fixed (N consecutive green runs).",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "dep-analysis-feature-flag-bloat-local",
        title: "Dependency analysis: feature flag bloat audit",
        description: "Audit Cargo.toml dependencies for unused features that bloat compile times.",
        class: BenchmarkClass::DependencyAnalysis,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Audit Cargo.toml dependencies for unnecessary default features. Cover: (1) which dependencies use default-features = true and whether all defaults are actually exercised, (2) at least three candidates where default-features = false plus an explicit features list would reduce build time, (3) the methodology (cargo tree -e features, cargo bloat, manual audit) and its limitations, (4) a recommended ordered list of which to disable first.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "dep-upgrade-tokio-major-multiprocess-rusty-clawd",
        title: "Dependency upgrade: tokio major-version bump on multi-process rusty-clawd",
        description: "Plan a tokio major-version upgrade across the workspace including breaking-change triage on the multi-process rusty-clawd backend.",
        class: BenchmarkClass::DependencyUpgrade,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Plan upgrading tokio from 1.x to a hypothetical 2.0. Cover: (1) the changelog triage process and which CHANGELOG sections to read first, (2) the at-risk surface area in this repo (spawn, select!, sync primitives) with at least three cited file:line references, (3) staged rollout (single-crate dev branch, run full test matrix, then workspace-wide), (4) rollback criteria. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "docs-architecture-decision-record-local",
        title: "Documentation: write an architecture decision record",
        description: "Author an ADR for a non-trivial design choice in the gym subsystem following the Nygard ADR template.",
        class: BenchmarkClass::Documentation,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Write an ADR for the choice to model BENCHMARK_SCENARIOS as a const array of BenchmarkScenario in src/gym/scenarios.rs. Cover: (1) Context (what problem this solves), (2) Decision (the chosen approach), (3) Status (Accepted), (4) Consequences (positives like compile-time checking, negatives like recompile cost on edits, alternatives considered like a runtime registry). Cite at least two file paths under src/gym/.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "event-sourcing-snapshot-cadence-multiprocess-rusty-clawd",
        title: "Event sourcing: snapshot cadence on multi-process rusty-clawd",
        description: "Design snapshot cadence for an event-sourced aggregate balancing replay cost against snapshot storage cost.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design the snapshot strategy for an event-sourced aggregate that receives ~1000 events per day. Cover: (1) the snapshot trigger (every N events, every T seconds, or on-demand), (2) snapshot serialization format and versioning to survive code evolution, (3) replay path on aggregate load (latest snapshot + tail events), (4) snapshot retention and pruning. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "feature-flag-kill-switch-local",
        title: "Feature flagging: emergency kill switch design",
        description: "Design an emergency kill switch flag that disables a problematic code path within seconds globally.",
        class: BenchmarkClass::FeatureFlagging,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a kill switch for a write-amplifying code path. Cover: (1) flag evaluation latency budget (target sub-second propagation) and how it is achieved (push vs pull, TTL on cached flag value), (2) default-on vs default-off semantics during partial outage, (3) audit logging of every flip with operator identity, (4) testing the flag works without depending on the failing path it protects.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "incident-response-comms-template-local",
        title: "Incident response: stakeholder comms template",
        description: "Author an incident communications template covering initial notification, status updates, and resolution.",
        class: BenchmarkClass::IncidentResponse,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Author an incident communications template suite. Cover: (1) the initial notification template (impact statement, scope, ETA, who to contact) sent within 5 minutes, (2) the periodic status update cadence and template (every 30 min for SEV2, every 15 for SEV1), (3) the resolution notification including next-steps for the postmortem, (4) the audience matrix (engineering vs customer vs exec) showing what content goes where.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "i18n-date-time-formatting-local",
        title: "Internationalization: locale-aware date and time formatting audit",
        description: "Audit a hypothetical UI for hardcoded date and time formats that ignore the user's locale.",
        class: BenchmarkClass::InternationalizationReview,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Audit date and time rendering. Cover: (1) any format strings that hardcode month names or MM/DD/YYYY ordering, (2) timezone handling (display in user TZ vs UTC and how the conversion is done), (3) relative time rendering (\"3 hours ago\") and its locale-aware library, (4) calendar systems beyond Gregorian where required by user base. Provide at least one cited file:line per finding category.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "migration-planning-blue-green-cutover-distributed-copilot",
        title: "Migration planning: blue/green cutover on distributed copilot-sdk",
        description: "Plan a blue/green cutover for a stateful service migration on the distributed copilot-sdk backend.",
        class: BenchmarkClass::MigrationPlanning,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Plan a blue/green cutover for a stateful service. Cover: (1) data replication strategy from blue to green during the soak phase and how lag is measured, (2) the traffic shift mechanism (DNS, load balancer weight, service mesh) and shift increments, (3) write-path correctness during the shift (idempotency, dual-write avoidance), (4) rollback decision tree with measurable abort thresholds. Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "observability-slo-error-budget-local",
        title: "Observability: SLO and error-budget instrumentation",
        description: "Design SLO and error-budget instrumentation for a request-handling code path.",
        class: BenchmarkClass::ObservabilityInstrumentation,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design SLO instrumentation for a request handler. Cover: (1) the SLI definition (success ratio: 2xx + non-server-fault 4xx over total) and counter metric names, (2) the SLO target (e.g. 99.9% over 30 days) and the corresponding error budget in minutes per month, (3) burn-rate alert thresholds (multi-window: 1h fast burn, 6h slow burn) with rationale, (4) a dashboard panel sketch enumerating the queries.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "rate-limiting-token-bucket-local",
        title: "Rate limiting: token bucket per-tenant policy",
        description: "Design a token bucket rate limiter applied per-tenant to a write endpoint.",
        class: BenchmarkClass::RateLimiting,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a per-tenant token bucket rate limiter. Cover: (1) bucket capacity and refill rate selection tied to declared tenant tier, (2) where state lives (in-memory per-instance, shared cache) and the consistency trade-off, (3) the on-limit response (429 with Retry-After header, queueing, or shedding) and rationale, (4) observability (metrics per tenant, alarm on systemic 429 rate).",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "release-management-canary-promotion-multiprocess-terminal",
        title: "Release management: canary promotion gate on multi-process terminal-shell",
        description: "Define an automated canary promotion gate evaluating health metrics before full rollout, driven via the terminal-shell base type.",
        class: BenchmarkClass::ReleaseManagement,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Define a canary promotion gate. Cover: (1) the canary slice (e.g. 1% of traffic for 30 minutes) and how traffic is shifted, (2) the health metrics evaluated (error rate, p95 latency, saturation) with explicit thresholds, (3) the auto-rollback trigger and how the operator is notified, (4) the promotion or abort decision and audit trail. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "safe-code-change-extract-constant-local",
        title: "Safe code change: extract a magic number to a named constant",
        description: "Identify a magic number in src/ and plan its extraction to a named const with descriptive name and doc comment.",
        class: BenchmarkClass::SafeCodeChange,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Identify one magic numeric literal in src/gym/ that would benefit from a named constant. Plan the extraction. Cover: (1) the file:line of the literal and its current usage, (2) the proposed const name, type, and documentation comment, (3) any other call sites that should also use the new constant, (4) verification that the change is purely a refactor (cargo check + cargo test --lib).",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "session-quality-evidence-pruning-local",
        title: "Session quality: evidence pruning policy",
        description: "Design an evidence pruning policy for long-running sessions that bounds memory while preserving operator-visible signal.",
        class: BenchmarkClass::SessionQuality,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design an evidence pruning policy for a session that may emit 10k+ records. Cover: (1) the retention rule (keep last N + every Mth older + all error/warn records), (2) how pruning preserves causal chains so the timeline is still readable, (3) the bounded memory budget and the worst-case retained count, (4) the operator-visible indicator that pruning occurred (e.g. an evidence record stating \"pruned 4221 older records\"). Cite types in src/gym/types.rs where relevant.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "a11y-screen-reader-live-region-multiprocess-rusty-clawd",
        title: "Accessibility: ARIA live region audit on multi-process rusty-clawd",
        description: "Audit dynamic content updates for ARIA live region usage so screen readers announce changes.",
        class: BenchmarkClass::AccessibilityReview,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Audit dynamic UI updates (toasts, validation errors, async result panels). Cover: (1) presence of aria-live with the appropriate politeness (polite vs assertive) per update type, (2) avoidance of role=alert spam during non-critical updates, (3) ensuring the announced text is meaningful (not just \"updated\"), (4) one cited element selector per finding. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "api-design-error-envelope-multiprocess-copilot",
        title: "API design: error envelope schema on multi-process copilot-sdk",
        description: "Design a stable error envelope schema for a public REST API on the multi-process copilot-sdk backend.",
        class: BenchmarkClass::ApiDesign,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design the error response envelope. Cover: (1) the JSON schema (code: stable string, message: human, details: optional structured, request_id: tracing correlator), (2) HTTP status mapping and the rule that 4xx vs 5xx is determined by client-fault vs server-fault, (3) error-code stability commitments and the deprecation process, (4) localization strategy for the human message. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "concurrency-channel-backpressure-multiprocess-terminal",
        title: "Concurrency analysis: channel backpressure audit on multi-process terminal-shell",
        description: "Audit unbounded channel use in a worker pipeline and plan bounded-channel migration with backpressure.",
        class: BenchmarkClass::ConcurrencyAnalysis,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Audit channel usage. Cover: (1) any unbounded channels that could OOM under producer surge, (2) the bounded-capacity replacement and how capacity was chosen (steady-state queue depth p99), (3) the backpressure propagation path (try_send vs send, what the producer does on full), (4) shutdown ordering so no message is lost. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "debugging-memory-leak-bisect-multiprocess-rusty-clawd",
        title: "Debugging: bisect a slow memory leak on multi-process rusty-clawd",
        description: "Plan how to localize a slow memory leak that grows ~10MB/hour in a long-running process.",
        class: BenchmarkClass::Debugging,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::MultiProcess,
        objective: "Plan how to localize a 10MB/hour leak. Cover: (1) the measurement method (RSS over time, heap profiler such as jemalloc heap dump, dhat, or valgrind massif) and why it suits Rust, (2) bisect strategy (toggle subsystems, capture before/after profiles), (3) likely suspects (Arc cycle, growing cache without eviction, leaked task) and the diagnostic for each, (4) verification that the fix holds (24h soak with flat RSS). Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "dep-upgrade-security-cve-triage-local",
        title: "Dependency upgrade: security CVE triage",
        description: "Triage a freshly disclosed CVE in a transitive dependency and decide on the upgrade or mitigation path.",
        class: BenchmarkClass::DependencyUpgrade,
        identity: "simard-gym",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Triage a hypothetical CVE in a transitive crate. Cover: (1) identifying whether the vulnerable code path is reachable from this repo (cargo tree -i, then call-graph reasoning), (2) the upgrade path (direct dep bump vs cargo update -p vs patch override), (3) interim mitigation if the upgrade is blocked (config flag, input sanitization), (4) the disclosure timeline and the artifact produced (changelog entry, customer notification draft).",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "feature-flag-cleanup-distributed-copilot",
        title: "Feature flagging: stale flag cleanup on distributed copilot-sdk",
        description: "Plan the cleanup of stale feature flags that have been at 100% rollout for over six months.",
        class: BenchmarkClass::FeatureFlagging,
        identity: "simard-gym",
        base_type: "copilot-sdk",
        topology: RuntimeTopology::Distributed,
        objective: "Plan stale-flag cleanup. Cover: (1) detection query (flags at 100% for >180 days with no recent toggles), (2) the safe deletion sequence (delete the conditional first, then the flag definition, then the flag-evaluation infra entry), (3) verification per removal (test the formerly-disabled branch is unreachable), (4) the recurring policy (quarterly review, ownership tag required at flag creation). Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "rate-limiting-distributed-coordination-distributed-rusty-clawd",
        title: "Rate limiting: distributed coordination on distributed rusty-clawd",
        description: "Design a distributed rate limiter shared across N replicas with bounded coordination cost.",
        class: BenchmarkClass::RateLimiting,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::Distributed,
        objective: "Design a distributed rate limiter. Cover: (1) the algorithm choice (centralized counter via Redis INCR, sliding-window log, or token-bucket-with-leases) and per-request coordination cost, (2) failure mode if the coordination store is unavailable (fail-open vs fail-closed, default local cap), (3) clock-skew tolerance for sliding-window approaches, (4) tests for the boundary conditions (exactly-at-limit, just-over). Confirm the distributed topology backend appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "session-quality-deterministic-replay-multiprocess-terminal",
        title: "Session quality: deterministic replay on multi-process terminal-shell",
        description: "Design deterministic session replay so an operator can re-run a recorded session and reproduce the same outcome.",
        class: BenchmarkClass::SessionQuality,
        identity: "simard-gym",
        base_type: "terminal-shell",
        topology: RuntimeTopology::MultiProcess,
        objective: "Design deterministic session replay. Cover: (1) what is captured (inputs, RNG seeds, timestamps, externally-fetched data) versus what is recomputed, (2) the boundary between deterministic core and non-deterministic edges (clock, network) and how edges are stubbed on replay, (3) the storage format and size budget per session, (4) a verification harness that detects replay divergence at the first differing record. Confirm the multi-process transport appears in runtime evidence.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "bug-localize-from-cargo-test-output",
        title: "Bug localization from cargo test failure output",
        description: "Given a verbatim cargo test failure block, the agent must identify the source file and function that contains the offending code path so an operator can begin a targeted fix.",
        class: BenchmarkClass::BugFix,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Below is a verbatim `cargo test` failure block. Read it carefully, then name (1) the source file path and (2) the function (or test) that contains the offending code path. Output exactly two lines: `file: <path>` and `function: <name>`.\n\n---- begin cargo test output ----\nrunning 1 test\ntest gym::tests_scenarios::benchmark_scenarios_returns_nine_scenarios ... FAILED\n\nfailures:\n\n---- gym::tests_scenarios::benchmark_scenarios_returns_nine_scenarios stdout ----\nthread 'gym::tests_scenarios::benchmark_scenarios_returns_nine_scenarios' panicked at src/gym/tests_scenarios.rs:18:5:\nassertion `left == right` failed\n  left: 149\n right: 147\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n\nfailures:\n    gym::tests_scenarios::benchmark_scenarios_returns_nine_scenarios\n\ntest result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out\n\nerror: test failed, to find out more, run `cargo test --lib -- gym::tests_scenarios::benchmark_scenarios_returns_nine_scenarios`\n----  end cargo test output  ----",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "long-context-needle-in-haystack",
        title: "Long-context needle search in scenarios source",
        description: "Exercise long-context retrieval by asking the agent to scan src/gym/scenarios.rs for a specific marker comment and report its line number plus the enclosing scenario id.",
        class: BenchmarkClass::RepoExploration,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Open the file `src/gym/scenarios.rs`. Locate the unique marker comment `// NEEDLE-XYZ-GYM-MARKER` in that file. Report exactly two lines: `line: <1-based line number>` and `enclosing_scenario_id: <id of the BenchmarkScenario that the marker is nearest to, or `none` if the marker sits outside any scenario literal>`.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "memory-recall-consolidated-episode",
        title: "Memory recall: summarize most recent consolidated episode",
        description: "Exercise the agent's ability to use prior episode and consolidated memory context. The agent must locate the most recent consolidated episode in its memory store and summarize its source_label and slot_type so an operator can confirm cross-turn recall is working.",
        class: BenchmarkClass::SessionQuality,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Use prior episode and consolidated memory context to answer the following question: recall the most recent consolidated episode currently held in your cognitive memory store and summarize it. Output exactly three lines: `episode_id: <id>`, `source_label: <source_label of that episode>`, and `slot_type: <slot_type of that episode>`. If no consolidated episode is available, output `episode_id: none`, `source_label: none`, `slot_type: none` and explain in one additional line why memory recall returned no results.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "multi-file-rename-public-api",
        title: "Multi-file refactor: rename a public API symbol across modules",
        description: "Plan a coordinated rename of a public API symbol that is referenced by multiple modules and tests, so an operator can apply the change without breaking downstream call sites.",
        class: BenchmarkClass::Refactoring,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Plan renaming the public function `benchmark_scenarios` (in `src/gym/scenarios.rs`) to `gym_benchmark_scenarios` across the entire crate. Cover: (1) the exhaustive list of files that must change (definition site plus every `use`/call site under `src/`), found via grep for the existing identifier, (2) the ordered edit sequence so the crate stays compilable between commits (definition + re-exports first, then call sites), (3) the verification command (`cargo check --lib`) that proves no stale references remain, (4) preservation of behavior — the function body, return type, and visibility must be unchanged. Show before/after for at least one call site.",
        expected_min_runtime_evidence: 4,
    },
    BenchmarkScenario {
        id: "plan-decomposition-vague-goal",
        title: "Plan decomposition: turn a vague operator goal into atomic steps",
        description: "Exercise plan-decomposition quality by asking the agent to convert a deliberately vague operator request into an ordered list of concrete, atomic, individually-verifiable steps.",
        class: BenchmarkClass::SessionQuality,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "An operator says: \"make the gym suite better\". Decompose that vague goal into an ordered list of 5-8 atomic steps that an engineer agent could execute one-at-a-time. Each step MUST: (1) name a single concrete action (e.g. `run_shell_command`, `structured_text_replace`, `cargo_test`), (2) name the exact target artefact (file path, command, or scenario id) the action operates on, (3) state a one-sentence expected outcome, (4) state a verification command whose exit-zero proves the step worked. Reject any step whose target would be prose or another multi-step plan. Produce the list as a numbered Markdown list.",
        expected_min_runtime_evidence: 3,
    },
    BenchmarkScenario {
        id: "failure-recovery-dirty-worktree",
        title: "Failure recovery: resume work after a dirty-worktree git failure",
        description: "Exercise failure-recovery by giving the agent a verbatim git error from an attempted branch switch on a dirty worktree, and requiring an ordered recovery plan that preserves the operator's uncommitted changes.",
        class: BenchmarkClass::Debugging,
        identity: "simard-engineer",
        base_type: "local-harness",
        topology: RuntimeTopology::SingleProcess,
        objective: "Below is a verbatim git failure an operator hit while trying to switch branches mid-task. Produce an ordered recovery plan (3-5 steps) that (a) preserves the uncommitted edits, (b) lets the operator complete the branch switch, (c) restores the edits onto the new branch, and (d) leaves the worktree clean. For each step give the exact `git` command and a one-line rationale. Explicitly reject `git checkout -- .` or `git reset --hard` as recovery options because they discard work.\n\n---- begin git output ----\n$ git switch main\nerror: Your local changes to the following files would be overwritten by checkout:\n\tsrc/gym/scenarios.rs\n\tsrc/gym/tests_scenarios.rs\nPlease commit your changes or stash them before you switch branches.\nAborting\n----  end git output  ----",
        expected_min_runtime_evidence: 3,
    },
];
