//! Auto-split BENCHMARK_SCENARIOS data — chunk 9.
//!
//! Wave 11: deeper coverage for previously underrepresented classes
//! (issue #1548). Adds 22 new scenarios across six classes:
//!   - KnowledgeRecall    (+5) — tools, user prefs, cross-session depth
//!   - SelfIntrospection  (+3) — L6–L8: goal-status recall, rationale
//!                               comparison, observe-phase discrimination
//!   - ChaosEngineering   (+3) — Simard-specific chaos patterns
//!   - CicdPipeline       (+4) — Simard CI/CD and release patterns
//!   - CachingStrategy    (+3) — Simard memory-cache and LRU patterns
//!   - EventSourcing      (+4) — OODA cycle-report and event-store patterns

use super::super::types::{BenchmarkClass, BenchmarkScenario};
use crate::runtime::RuntimeTopology;

pub(super) static SCENARIOS: [BenchmarkScenario; 22] = [
    // ── KnowledgeRecall ──────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "knowledge-recall-tool-gh-cli-pr",
        title: "Knowledge recall: creating PRs with gh CLI in Simard worktrees",
        description: "Verify the agent can recall the preferred way to create a pull request from a Simard engineer worktree — using the gh CLI rather than manually constructing a GitHub API URL — and cite the co-authored-by trailer convention.",
        class: BenchmarkClass::KnowledgeRecall,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Recall the preferred CLI tool and command for creating a pull request from a Simard engineer worktree, and state the required co-authored-by trailer that must appear at the end of every commit message.",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "knowledge-recall-tool-cargo-test-lib",
        title: "Knowledge recall: running subset of Rust tests with cargo test --lib",
        description: "Verify the agent can recall that Simard's test suite is run with 'cargo test --lib -- <module>' to target a specific module, not 'cargo test -- --test <name>' or just 'cargo test'.",
        class: BenchmarkClass::KnowledgeRecall,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Recall the exact cargo subcommand and flags used to run only the gym-related tests in Simard's library (not integration tests), and explain why the --lib flag is used.",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "knowledge-recall-user-no-markdown-planning",
        title: "Knowledge recall: user preference against markdown planning files",
        description: "Verify the agent can recall the user's stated preference that planning notes and todos should not be written as markdown files in the repository — only session-state files (e.g. plan.md under ~/.copilot/session-state/) are permitted.",
        class: BenchmarkClass::KnowledgeRecall,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Recall the user-stated preference about where planning notes and todo tracking should live, and state whether markdown files may be created in the repository root for planning purposes.",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "knowledge-recall-repo-prompt-assets-hot-reload",
        title: "Knowledge recall: prompt_assets hot-reload mechanism",
        description: "Verify the agent can recall that Simard's prompt assets under prompt_assets/simard/*.md are re-hashed every OODA cycle without a daemon restart — a hot-reload mechanism that enables prompt iteration without recompilation.",
        class: BenchmarkClass::KnowledgeRecall,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Recall how Simard's prompt assets are loaded at runtime: what directory they live in, how they are referenced in source code (include_str! vs runtime read), and whether changing a prompt asset requires a daemon restart.",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "knowledge-recall-cross-session-ooda-brain-mandate",
        title: "Knowledge recall: cross-session mandate for prompt-driven OODA brain",
        description: "Verify the agent can recall the architectural mandate — stored across sessions — that Simard's OODA brain must be prompt-driven (prompt_assets/simard/*.md + LLM trait) rather than hard-coded Rust match arms.",
        class: BenchmarkClass::KnowledgeRecall,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Recall the user-mandated architectural constraint on Simard's OODA decision logic: which component must be prompt-driven, what files hold the prompts, and what Rust trait decouples the LLM call from the OODA phase implementation.",
        expected_min_runtime_evidence: 2,
    },
    // ── SelfIntrospection ────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "self-introspection-l6-goal-status-recall",
        title: "Self-introspection L6: goal status recall from cycle report",
        description: "Verify the agent can read an embedded cycle-report JSON and correctly report the status assigned to a named goal by the observe phase.",
        class: BenchmarkClass::SelfIntrospection,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Given the synthetic cycle report `{\"cycle\":9,\"goal_id\":\"self-serve-dashboard-improvement\",\"phase\":\"observe\",\"judgment\":{\"status\":\"in-progress\",\"commit_count\":3,\"prompt_version\":\"\"}}`, state the observe-phase status assigned to the self-serve-dashboard-improvement goal in cycle 9, and identify whether the observe phase used the LLM brain or deterministic fallback (empty prompt_version → deterministic).",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "self-introspection-l7-rationale-comparison",
        title: "Self-introspection L7: decide-phase rationale comparison across goals",
        description: "Verify the agent can compare decide-phase rationales from two different goals in the same cycle and identify which goal was prioritised and why.",
        class: BenchmarkClass::SelfIntrospection,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Given two synthetic cycle-10 decide judgments — `{\"goal_id\":\"add-more-gym-benchmark-scenarios\",\"decision\":\"skip\",\"rationale\":\"blocked on clippy in open worktree\",\"prompt_version\":\"eee555000666\"}` and `{\"goal_id\":\"self-serve-dashboard-improvement\",\"decision\":\"dispatch_engineer\",\"rationale\":\"dashboard has no playwright coverage yet; engineer worktree is clean\",\"prompt_version\":\"eee555000666\"}` — state which goal the decide brain chose to advance in cycle 10 and why it skipped the other. Cite src/ooda_brain/ as the brain source.",
        expected_min_runtime_evidence: 2,
    },
    BenchmarkScenario {
        id: "self-introspection-l8-observe-phase-discrimination",
        title: "Self-introspection L8: observe-phase determinism vs LLM discrimination",
        description: "Verify the agent understands that Simard's observe phase is intentionally deterministic (no LLM call) and that this is a design choice, not an oversight.",
        class: BenchmarkClass::SelfIntrospection,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Given the synthetic multi-phase cycle report `{\"cycle\":11,\"judgments\":[{\"phase\":\"observe\",\"prompt_version\":\"\"},{\"phase\":\"orient\",\"prompt_version\":\"fff666000777\"},{\"phase\":\"decide\",\"prompt_version\":\"fff666000777\"},{\"phase\":\"act\",\"prompt_version\":\"\"}]}`, explain why the observe phase always has an empty prompt_version, cite the OODA prompt-driven migration history (PRs #1458, #1469, #1471), and state which phase was intentionally left deterministic by design.",
        expected_min_runtime_evidence: 2,
    },
    // ── ChaosEngineering ─────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "chaos-engineering-daemon-restart-mid-cycle",
        title: "Chaos engineering: daemon restart mid-OODA-cycle",
        description: "Verify the agent can design a chaos experiment that kills the Simard daemon in the middle of an OODA cycle and verify that goal state survives the restart via the persistence layer.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Design a chaos experiment that kills the Simard daemon (SIGKILL) immediately after the orient phase writes its judgment and before act is executed, then restarts the daemon. Specify what state should be preserved and how to verify it was not lost.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "chaos-engineering-worktree-disk-full",
        title: "Chaos engineering: engineer worktree creation failure under disk pressure",
        description: "Verify the agent can reason about what happens when the engineer worktree creation step fails due to disk full, and propose a recovery path that does not corrupt the goal state.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Describe the failure mode when 'git worktree add' in the OODA engineer-spawn path fails due to ENOSPC (disk full). Identify which goal state field would be left in an inconsistent state and propose a recovery strategy that avoids permanently marking the goal as assigned when no live engineer exists.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "chaos-engineering-memory-store-corruption",
        title: "Chaos engineering: cognitive memory store corruption at startup",
        description: "Verify the agent can propose a resilience pattern for the scenario where the SQLite cognitive memory store is partially corrupted and the daemon fails to start.",
        class: BenchmarkClass::ChaosEngineering,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Describe how Simard should handle startup failure caused by a corrupted SQLite memory store under ~/.simard/. Propose a resilience pattern: what the daemon should do (start with empty memory, repair, refuse to start), what the trade-off is, and which files are involved.",
        expected_min_runtime_evidence: 1,
    },
    // ── CicdPipeline ─────────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "cicd-pipeline-verify-workflow-gate",
        title: "CI/CD pipeline: verify.yml gate structure",
        description: "Verify the agent can describe the structure of Simard's verify.yml CI workflow — what jobs it runs, the order of the gates, and which gate is the final merge prerequisite.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Describe the structure of Simard's .github/workflows/verify.yml: list the major job names, their dependency order, and identify which job is the required merge gate that all PRs must pass.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-release-binary-publish",
        title: "CI/CD pipeline: release.yml binary publish workflow",
        description: "Verify the agent understands how Simard's release workflow builds and publishes the release binary — the target triple, the triggering event, and the artifact destination.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Explain how Simard's release.yml workflow builds and publishes the simard binary: what triggers the workflow (tag push vs branch merge), the Rust target triple used, and where the binary artifact ends up.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-pre-push-hook-stages",
        title: "CI/CD pipeline: local pre-push hook stages and skip mechanism",
        description: "Verify the agent can enumerate the stages of Simard's local pre-push hook and explain the approved mechanism to skip the cargo-test stage for known-flaky tests.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Enumerate the stages run by Simard's local pre-push hook (e.g., clippy, fmt, test). Explain the approved environment-variable mechanism to skip the cargo-test stage for known-flaky tests, and confirm that --no-verify is forbidden.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "cicd-pipeline-docs-build-strict",
        title: "CI/CD pipeline: mkdocs strict build gate",
        description: "Verify the agent understands that the docs CI job runs mkdocs with --strict, causing broken cross-document links to fail the build, and can explain why links from docs/ to files outside the docs/ tree are prohibited.",
        class: BenchmarkClass::CicdPipeline,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Explain why the Simard docs CI job fails when a documentation page contains a relative link to a file outside the docs/ tree (e.g., pointing to prompt_assets/). Cite where mkdocs strict mode is configured and what the error message looks like.",
        expected_min_runtime_evidence: 1,
    },
    // ── CachingStrategy ──────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "caching-strategy-once-lock-scenario-registry",
        title: "Caching strategy: OnceLock-based benchmark scenario registry",
        description: "Verify the agent can identify the OnceLock-based caching pattern used in the gym scenario registry and explain why it is preferred over re-allocating the Vec on every benchmark run.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Identify where Simard's gym scenario registry uses std::sync::OnceLock to cache the full scenario Vec, explain the trade-off between lazy initialisation and eager loading, and state what would happen if OnceLock were replaced with a plain static Vec.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "caching-strategy-working-memory-eviction",
        title: "Caching strategy: working-memory eviction policy in cognitive memory",
        description: "Verify the agent can describe the eviction policy used by Simard's working-memory store — specifically how old or low-priority entries are removed during consolidation.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Describe how Simard's cognitive memory subsystem handles working-memory eviction: what triggers a consolidation pass, what the consolidate_episodes parameter controls, and which entries are promoted to long-term storage versus discarded.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "caching-strategy-prompt-version-hash-cache",
        title: "Caching strategy: prompt_version sha256 hash caching across cycles",
        description: "Verify the agent can explain why Simard re-hashes prompt assets each OODA cycle rather than caching the hash across cycles, and what the trade-off is between freshness and CPU cost.",
        class: BenchmarkClass::CachingStrategy,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Explain the caching strategy used for Simard's prompt_version field: is the sha256 hash of the prompt asset computed once at startup and cached, or re-computed each OODA cycle? State the trade-off and identify the source file where the hash is computed.",
        expected_min_runtime_evidence: 1,
    },
    // ── EventSourcing ────────────────────────────────────────────────────────
    BenchmarkScenario {
        id: "event-sourcing-cycle-report-append-only",
        title: "Event sourcing: OODA cycle report as append-only event log",
        description: "Verify the agent can explain how Simard's cycle_reports/ directory functions as an append-only event log for the OODA loop, and how historical judgments can be replayed for SelfIntrospection scenarios.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Explain how Simard's cycle_reports/ directory acts as an append-only event log: what each file represents, how cycle number is encoded in the filename, and how the SelfIntrospection gym scenarios use this log to test longitudinal self-knowledge without a live daemon.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "event-sourcing-memory-episode-store",
        title: "Event sourcing: cognitive memory episode store as event stream",
        description: "Verify the agent understands that Simard's memory episode store is an append-only log of cognitive events that are later consolidated into long-term memory.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Describe how Simard's memory episode store behaves as an event stream: how new observations are appended, what triggers a consolidation pass, and what the schema of an episode record looks like (fields: session_id, slot_type, source_label).",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "event-sourcing-goal-state-transitions",
        title: "Event sourcing: goal state as a sequence of OODA phase events",
        description: "Verify the agent can model a Simard goal's lifecycle as an event-sourced state machine where each OODA phase transition is an event and the current state is derived by replaying the event log.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Model a Simard goal's lifecycle using event sourcing: list the sequence of OODA phase events that move a goal from 'seeded' to 'engineer dispatched' to 'merged', identify the field in the goal record that tracks current assignment (assigned_to), and explain how the dispatch dedup guard uses this field as a derived-state check.",
        expected_min_runtime_evidence: 1,
    },
    BenchmarkScenario {
        id: "event-sourcing-pr-merge-as-terminal-event",
        title: "Event sourcing: PR merge as terminal event in goal lifecycle",
        description: "Verify the agent can explain how a merged PR acts as the terminal event in a Simard goal's lifecycle, triggering goal completion and memory consolidation.",
        class: BenchmarkClass::EventSourcing,
        identity: "simard-gym",
        base_type: "rusty-clawd",
        topology: RuntimeTopology::SingleProcess,
        objective: "Explain how a merged pull request acts as the terminal event for a Simard goal: what the OODA observe phase detects (merged PR on the goal branch), what goal-state transition it triggers, and what memory operations are performed at goal completion (consolidation_persistence call).",
        expected_min_runtime_evidence: 1,
    },
];
